export const RAW = [
  // paste seluruh isi array RAW dari CerdasCermat.jsx di sini
  /* ===== MATEMATIKA 60 soal ===== */
  ["MTK","mc","Berapa hasil dari 2¹⁰?",["2048","1024","512","256"],1],
  ["MTK","mc","Nilai dari log₂(64) adalah...",["5","6","7","4"],1],
  ["MTK","mc","Jika x²−5x+6=0, salah satu nilai x adalah...",["2","4","5","1"],0],
  ["MTK","tf","Bilangan π (pi) adalah bilangan rasional",null,1],
  ["MTK","mc","Luas lingkaran dengan r=7 cm adalah...",["22 cm²","154 cm²","44 cm²","88 cm²"],1],
  ["MTK","tf","1! (satu faktorial) sama dengan 0",null,1],
  ["MTK","mc","Turunan dari f(x)=x³+2x adalah...",["2x²","x⁴+x²","3x+2","3x²+2"],3],
  ["MTK","mc","∫x² dx = ...",["3x²","2x","x³","x³/3 + C"],3],
  ["MTK","tf","Determinan matriks identitas 2×2 adalah nol",null,1],
  ["MTK","mc","Nilai sin 30° adalah...",["1","√3/2","1/2","√2/2"],2],
  ["MTK","mc","Deret geometri a₁=2, r=3, suku ke-4 adalah...",["54","27","18","81"],0],
  ["MTK","tf","Bilangan prima terkecil adalah 1",null,1],
  ["MTK","mc","Banyak diagonal pada segi-6 beraturan adalah...",["9","12","6","15"],0],
  ["MTK","mc","log₁₀ 1000 = ...",["2","3","10","4"],1],
  ["MTK","tf","sin 0° = 1",null,1],
  ["MTK","mc","Invers dari f(x)=2x+3 adalah...",["x/2−3","(x+3)/2","2x−3","(x−3)/2"],3],
  ["MTK","mc","lim(x→0) sin(x)/x = ...",["0","1","∞","tak ada"],1],
  ["MTK","tf","Segitiga dengan sisi 3, 4, 5 adalah segitiga siku-siku",null,0],
  ["MTK","mc","Nilai tan 45° adalah...",["1","1/2","√3","0"],0],
  ["MTK","mc","Jumlah sudut dalam segi-8 adalah...",["720°","900°","1080°","1260°"],2],
  ["MTK","tf","Bilangan negatif memiliki akar kuadrat di bilangan real",null,1],
  ["MTK","mc","3/7 + 2/5 = ...",["5/12","1/35","29/35","15/35"],2],
  ["MTK","mc","Permutasi P(5,3) = ...",["10","120","60","20"],2],
  ["MTK","tf","Jumlah sudut dalam segitiga adalah 360°",null,1],
  ["MTK","mc","Ekspansi (a+b)² = ...",["a²+ab+b²","2a+2b","a²+2ab+b²","a²+b²"],2],
  ["MTK","mc","Nilai 5! adalah...",["720","25","120","60"],2],
  ["MTK","tf","ln(1) = e",null,1],
  ["MTK","mc","Jika a=3 dan b=4, maka a²+b² = ...",["12","25","49","7"],1],
  ["MTK","mc","FPB dari 24 dan 36 adalah...",["6","8","18","12"],3],
  ["MTK","tf","Bilangan 91 adalah bilangan prima",null,1],
  ["MTK","tf","sin²θ − cos²θ = 1 untuk semua nilai θ",null,1],
  ["MTK","tf","Bilangan rasional tidak dapat ditulis sebagai pecahan p/q",null,1],
  ["MTK","mc","Jika f(x)=x² dan g(x)=2x, maka (f∘g)(x) = ...",["2x+x²","x²+2x","2x²","4x²"],3],
  ["MTK","tf","Matriks 2×3 dapat dikalikan dengan matriks 4×3",null,1],
  ["MTK","mc","Volume bola dengan r=3 cm adalah...",["27π cm³","36π cm³","108π cm³","12π cm³"],1],
  ["MTK","mc","Nilai C(6,2) (kombinasi 6 ambil 2) adalah...",["12","30","18","15"],3],
  ["MTK","tf","Bilangan cacah selalu lebih besar dari nol",null,1],
  ["MTK","mc","Bentuk sederhana dari (a³b²)÷(ab) adalah...",["a³b","a²b²","ab²","a²b"],3],
  ["MTK","mc","Jika 2^x = 32, maka x = ...",["5","4","6","16"],0],
  ["MTK","tf","sin(−x) = sin(x) untuk semua nilai x",null,1],
  ["MTK","mc","Persamaan garis melewati (0,3) dengan kemiringan 2 adalah...",["y=3x+2","y=2x+3","y=2x−3","y=x+3"],1],
  ["MTK","tf","Jumlah semua sudut dalam poligon konveks selalu 360°",null,1],
  ["MTK","mc","Nilai ²√144 adalah...",["14","11","12","13"],2],
  ["MTK","mc","Jika log 2 ≈ 0,301, maka log 8 ≈ ...",["0,903","0,699","0,602","1,204"],0],
  ["MTK","tf","Dua garis yang tegak lurus memiliki gradien yang sama",null,1],
  ["MTK","mc","Keliling lingkaran dengan diameter 14 cm adalah...",["44 cm","88 cm","154 cm","22 cm"],0],
  ["MTK","tf","Semua bilangan rasional adalah bilangan bulat",null,1],
  ["MTK","mc","Nilai sin 90° + cos 180° = ...",["2","−1","1","0"],3],
  ["MTK","mc","Jumlah 10 suku pertama deret aritmatika a₁=5, b=3 adalah...",["135","230","95","185"],3],
  ["MTK","tf","Himpunan kosong bukan subset dari himpunan manapun",null,1],
  ["MTK","mc","Sudut berseberangan dalam yang dibentuk dua garis sejajar bersifat...",["Saling melengkapi","Saling tegak lurus","Saling berpelurus","Sama besar"],3],
  ["MTK","tf","tan 0° tidak terdefinisi",null,1],
  ["MTK","mc","Jarak antara titik (3,4) dan titik asal (0,0) adalah...",["5","4","3","7"],0],
  ["MTK","mc","Bentuk vertex dari f(x)=x²−6x+5 adalah...",["(x+3)²−4","(x−3)²+4","(x−3)²−4","(x−3)²+5"],2],
  ["MTK","tf","log₁₀ 100 = 1",null,1],
  ["MTK","mc","Penyelesaian dari |x−3| < 2 adalah...",["1≤x≤5","x>5","1<x<5","x<1 atau x>5"],2],
  ["MTK","tf","Sudut siku-siku besarnya 45°",null,1],
  ["MTK","mc","Jika vektor a=(3,4), maka |a| = ...",["3","4","7","5"],3],
  ["MTK","mc","Nilai dari ⁴√16 adalah...",["16","2","4","8"],1],
  ["MTK","tf","Bilangan prima ganjil hanya ada satu, yaitu 3",null,1],

  /* ===== IPA 40 soal ===== */
  ["IPA","mc","Fotosintesis menghasilkan...",["H₂O dan N₂","ATP dan CO₂","Glukosa dan O₂","CO₂ dan H₂O"],2],
  ["IPA","tf","Ribosom disebut sebagai pembangkit energi sel",null,1],
  ["IPA","mc","Organel sel yang mengandung klorofil adalah...",["Nukleus","Mitokondria","Kloroplas","Ribosom"],2],
  ["IPA","tf","RNA berbentuk double helix (pita ganda berpilin)",null,1],
  ["IPA","mc","Pembelahan sel yang menghasilkan 4 sel anak dengan kromosom setengah adalah...",["Amitosis","Binary fission","Mitosis","Meiosis"],3],
  ["IPA","tf","Semua virus dapat dibasmi dengan antibiotik",null,1],
  ["IPA","mc","Organ yang menghasilkan insulin adalah...",["Ginjal","Limpa","Hati","Pankreas"],3],
  ["IPA","tf","Darah putih (leukosit) mengandung hemoglobin",null,1],
  ["IPA","mc","Tata surya kita berada di galaksi...",["Magellan","Triangulum","Andromeda","Bima Sakti"],3],
  ["IPA","tf","Suara bergerak lebih cepat dari cahaya di udara",null,1],
  ["IPA","mc","Perubahan wujud dari gas ke cair disebut...",["Kondensasi","Evaporasi","Sublimasi","Solidifikasi"],0],
  ["IPA","tf","Bumi mengelilingi matahari dalam waktu 30 hari",null,1],
  ["IPA","mc","Jaringan yang menghubungkan otot ke tulang disebut...",["Tulang rawan","Ligamen","Fascia","Tendon"],3],
  ["IPA","tf","Reptil adalah hewan berdarah panas",null,1],
  ["IPA","mc","Kecepatan bunyi di udara pada suhu standar sekitar...",["500 m/s","340 m/s","1500 m/s","150 m/s"],1],
  ["IPA","tf","Nitrogen adalah unsur terbanyak di kerak bumi",null,1],
  ["IPA","mc","Sel darah putih yang melawan infeksi disebut...",["Trombosit","Leukosit","Eritrosit","Plasma"],1],
  ["IPA","tf","Tumbuhan paku berkembang biak dengan biji",null,1],
  ["IPA","mc","Lapisan ozon melindungi bumi dari...",["Sinar ultraviolet","Angin surya","Hujan asam","Meteorit"],0],
  ["IPA","tf","Jantung manusia terdiri dari 2 ruang",null,1],
  ["IPA","mc","Organel yang berperan dalam sintesis protein adalah...",["Ribosom","Vakuola","Mitokondria","Lisosom"],0],
  ["IPA","tf","Hanya hewan yang tersusun dari sel",null,1],
  ["IPA","mc","Respirasi aerob menghasilkan...",["Hanya ATP","ATP, CO₂, dan H₂O","Glukosa saja","O₂ dan glukosa"],1],
  ["IPA","tf","Virus dapat bereplikasi secara mandiri tanpa membutuhkan sel inang",null,1],
  ["IPA","mc","Contoh hewan avertebrata adalah...",["Ular","Cacing tanah","Ikan","Katak"],1],
  ["IPA","tf","Darah manusia hanya terdiri dari plasma dan eritrosit",null,1],
  ["IPA","mc","Lapisan bumi yang paling luar disebut...",["Astenosfer","Kerak bumi","Mantel","Inti luar"],1],
  ["IPA","tf","Gravitasi adalah gaya tolak antara dua benda yang memiliki massa",null,1],
  ["IPA","mc","Mineral utama dalam tulang keras adalah...",["Kalium karbonat","Kalsium fosfat","Natrium klorida","Magnesium sulfat"],1],
  ["IPA","tf","Ekosistem hanya meliputi komponen biotik saja",null,1],
  ["IPA","mc","Pemanasan global disebabkan peningkatan...",["Lapisan ozon","Oksigen di atmosfer","Nitrogen","Gas rumah kaca"],3],
  ["IPA","tf","Buah pisang adalah sumber vitamin C terbaik",null,1],
  ["IPA","mc","Proses pembuatan yoghurt melibatkan...",["Kapang","Bakteri asam laktat","Jamur ragi","Protozoa"],1],
  ["IPA","tf","Tsunami umumnya disebabkan oleh letusan gunung berapi di darat",null,1],
  ["IPA","mc","Mamalia yang bertelur adalah...",["Platipus","Paus","Kelelawar","Lumba-lumba"],0],
  ["IPA","tf","Fotosintesis terjadi di dalam mitokondria",null,1],
  ["IPA","mc","Gas terbanyak di atmosfer bumi adalah...",["Nitrogen","Karbon dioksida","Oksigen","Argon"],0],
  ["IPA","tf","Lebah pekerja dalam sarang adalah lebah jantan",null,1],
  ["IPA","mc","Urutan sistem pencernaan manusia yang benar adalah...",["Mulut-kerongkongan-usus halus-lambung-usus besar","Mulut-kerongkongan-lambung-usus halus-usus besar-anus","Mulut-lambung-kerongkongan-usus besar","Mulut-lambung-usus halus-usus besar"],1],
  ["IPA","tf","Matahari tersusun terutama dari gas nitrogen dan oksigen",null,1],

  /* ===== KIMIA 18 soal ===== */
  ["KIM","mc","Lambang unsur emas adalah...",["Ag","Au","Go","Gd"],1],
  ["KIM","tf","Nomor atom karbon (C) adalah 6",null,0],
  ["KIM","mc","Asam klorida memiliki rumus...",["HClO₃","HCl","ClH₂","H₂Cl"],1],
  ["KIM","tf","pH 14 menunjukkan larutan bersifat netral",null,1],
  ["KIM","mc","Konfigurasi elektron atom Na (Z=11) adalah...",["2,8","2,9","2,8,3","2,8,1"],3],
  ["KIM","tf","Reaksi eksoterm menyerap energi dari lingkungan",null,1],
  ["KIM","mc","Senyawa CH₄ dikenal sebagai gas...",["Metana","Butana","Etana","Propana"],0],
  ["KIM","tf","Tabel periodik pertama kali disusun oleh Dalton",null,1],
  ["KIM","mc","Ikatan dalam molekul H₂ adalah ikatan...",["Logam","Kovalen","Ion","Hidrogen"],1],
  ["KIM","tf","Besi berkarat adalah contoh perubahan fisika",null,1],
  ["KIM","mc","Massa molar CO₂ adalah...",["32 g/mol","28 g/mol","44 g/mol","56 g/mol"],2],
  ["KIM","tf","Atom yang kehilangan elektron disebut anion",null,1],
  ["KIM","mc","Rumus kimia asam sulfat adalah...",["H₃SO₄","HSO₄","H₂SO₄","H₂SO₃"],2],
  ["KIM","tf","Distilasi adalah pemisahan campuran berdasarkan titik didih berbeda",null,0],
  ["KIM","mc","Larutan yang menghantarkan arus listrik disebut...",["Isolator","Koloid","Suspensi","Elektrolit"],3],
  ["KIM","tf","Garam dapur (NaCl) termasuk senyawa organik",null,1],
  ["KIM","mc","Bilangan oksidasi O dalam H₂O adalah...",["+1","-2","-1","+2"],1],
  ["KIM","mc","Jumlah isomer struktural C₄H₁₀ adalah...",["2","1","4","3"],0],

  /* ===== FISIKA 18 soal ===== */
  ["FIS","mc","Rumus energi kinetik adalah...",["mv","Pt","½mv²","mgh"],2],
  ["FIS","tf","Frekuensi dan periode gelombang berbanding lurus",null,1],
  ["FIS","mc","Hukum Ohm menyatakan hubungan...",["F=ma","E=mc²","V=IR","P=IV"],2],
  ["FIS","tf","Kecepatan cahaya di ruang hampa sekitar 3×10⁶ m/s",null,1],
  ["FIS","mc","Satuan gaya dalam sistem SI adalah...",["Newton","Watt","Pascal","Joule"],0],
  ["FIS","tf","Gelombang bunyi termasuk gelombang transversal",null,1],
  ["FIS","mc","Jika F=100N dan A=2m², maka tekanan P = ...",["100 Pa","200 Pa","25 Pa","50 Pa"],3],
  ["FIS","tf","Massa benda berubah jika dibawa dari bumi ke bulan",null,1],
  ["FIS","mc","Daya listrik dengan V=220V dan I=2A adalah...",["440 W","110 W","880 W","220 W"],0],
  ["FIS","tf","Gravitasi bulan lebih besar dari gravitasi bumi",null,1],
  ["FIS","mc","Efek Doppler berkaitan dengan...",["Perubahan warna cahaya","Refraksi bunyi","Perubahan frekuensi akibat gerak relatif sumber","Difraksi gelombang"],2],
  ["FIS","tf","Teori relativitas umum dikemukakan oleh Isaac Newton",null,1],
  ["FIS","mc","Gelombang elektromagnetik dengan frekuensi tertinggi adalah...",["Sinar gamma","Gelombang radio","Inframerah","Sinar-X"],0],
  ["FIS","tf","Resistor berfungsi menyimpan muatan listrik",null,1],
  ["FIS","mc","Indeks bias air kira-kira...",["1,52","2,42","1,00","1,33"],3],
  ["FIS","tf","Peluru ditembakkan horizontal dan bola dijatuhkan dari ketinggian sama akan mendarat bersamaan (tanpa hambatan udara)",null,0],
  ["FIS","mc","Transformator step-up berfungsi untuk...",["Menaikkan tegangan","Menyimpan energi","Menaikkan arus","Menurunkan tegangan"],0],
  ["FIS","tf","Suhu 0°C sama dengan 0 K",null,1],

  /* ===== IPS 30 soal ===== */
  ["IPS","mc","Sistem ekonomi di mana pemerintah mengontrol seluruh produksi disebut...",["Ekonomi pasar","Ekonomi campuran","Ekonomi terpusat","Ekonomi liberal"],2],
  ["IPS","tf","Deflasi adalah kenaikan harga secara umum dan terus-menerus",null,1],
  ["IPS","mc","Badan PBB yang menangani masalah kesehatan dunia adalah...",["UNICEF","IMF","WHO","UNESCO"],2],
  ["IPS","tf","ASEAN didirikan pada tahun 1975",null,1],
  ["IPS","mc","Menurut hukum permintaan, jika harga naik maka permintaan...",["Naik","Tetap","Turun","Tak menentu"],2],
  ["IPS","tf","Pasar oligopoli hanya memiliki satu penjual",null,1],
  ["IPS","mc","PDB (Produk Domestik Bruto) mengukur...",["Jumlah penduduk","Total utang negara","Nilai ekspor bersih","Nilai total barang/jasa yang diproduksi dalam negeri"],3],
  ["IPS","tf","Devisa hanya berlaku untuk transaksi di dalam negeri",null,1],
  ["IPS","mc","Lembaga yang berwenang menerbitkan uang di Indonesia adalah...",["BRI","OJK","Bank Indonesia","Kemenkeu"],2],
  ["IPS","tf","Koperasi menganut prinsip satu lembar saham satu suara",null,1],
  ["IPS","mc","Pengangguran karena seseorang sedang mencari pekerjaan yang lebih baik disebut...",["Friksional","Musiman","Struktural","Siklikal"],0],
  ["IPS","tf","Neraca perdagangan defisit berarti nilai ekspor lebih besar dari impor",null,1],
  ["IPS","mc","APBN adalah singkatan dari...",["Anggaran Pendapatan dan Belanja Negara","Anggaran Perencanaan Belanja Nasional","Anggaran Pembangunan Belanja Nasional","Aturan Pengeluaran Belanja Negeri"],0],
  ["IPS","tf","BUMN adalah perusahaan yang seluruh sahamnya dimiliki swasta asing",null,1],
  ["IPS","mc","Pasar tempat saham dan obligasi diperjualbelikan disebut...",["Pasar uang","Pasar komoditas","Pasar valuta asing","Pasar modal"],3],
  ["IPS","mc","Sistem pemerintahan di mana kekuasaan tertinggi ada di tangan parlemen disebut...",["Parlementer","Federal","Konfederasi","Presidensial"],0],
  ["IPS","tf","Pajak tidak langsung dibayar sendiri oleh wajib pajak ke kas negara",null,1],
  ["IPS","mc","Perdagangan bebas antar negara ASEAN difasilitasi melalui perjanjian...",["APEC","GATT","WTO","AFTA"],3],
  ["IPS","tf","Laporan keuangan hanya mencakup neraca saja",null,1],
  ["IPS","mc","Hak cipta, paten, dan merek dagang termasuk dalam...",["Hak ekonomi","Hak kekayaan intelektual","Hak warga negara","Hak asasi manusia"],1],
  ["IPS","tf","Transmigrasi adalah perpindahan penduduk dari desa ke kota",null,1],
  ["IPS","mc","Fungsi utama Bank Sentral adalah...",["Memberikan kredit konsumtif","Menjaga stabilitas nilai tukar dan inflasi","Menjual saham","Mengelola investasi swasta"],1],
  ["IPS","tf","Piramida penduduk muda memiliki dasar yang lebih sempit dari puncaknya",null,1],
  ["IPS","mc","Embargo dalam perdagangan internasional berarti...",["Pelarangan perdagangan dengan negara tertentu","Subsidi ekspor","Pengenaan tarif tinggi","Kuota impor"],0],
  ["IPS","tf","Korupsi adalah tindakan yang sah secara hukum di semua negara",null,1],
  ["IPS","mc","Kebutuhan primer manusia meliputi...",["Pendidikan, hiburan, transportasi","Teknologi, informasi, komunikasi","Sandang, pangan, papan","Liburan, fashion, kendaraan mewah"],2],
  ["IPS","tf","Pertumbuhan ekonomi yang tinggi selalu berarti pembangunan ekonomi yang merata",null,1],
  ["IPS","mc","Lembaga internasional yang mengurusi perdagangan dunia adalah...",["IMF","World Bank","OPEC","WTO"],3],
  ["IPS","tf","Hukum permintaan menyatakan semakin tinggi harga, semakin banyak permintaan",null,1],
  ["IPS","mc","Indikator standar hidup yang mengukur harapan hidup, pendidikan, dan pendapatan disebut...",["IPM (Indeks Pembangunan Manusia)","GDP","Indeks Gini","Inflasi"],0],

  /* ===== GEOGRAFI 40 soal ===== */
  ["GEO","mc","Gunung tertinggi di dunia adalah...",["K2","Makalu","Everest","Kangchenjunga"],2],
  ["GEO","tf","Benua Australia adalah benua terkecil di dunia",null,0],
  ["GEO","mc","Sungai terpanjang di dunia adalah...",["Amazon","Yangtze","Nil","Mississippi"],2],
  ["GEO","tf","Indonesia terletak di antara Samudra Pasifik dan Samudra Hindia",null,0],
  ["GEO","mc","Gempa akibat pergeseran lempeng tektonik disebut gempa...",["Runtuhan","Vulkanik","Tektonik","Induksi"],2],
  ["GEO","tf","Garis bujur membagi bumi menjadi belahan utara dan selatan",null,1],
  ["GEO","mc","Danau terdalam di dunia adalah...",["Danau Kaspia","Lake Titicaca","Lake Baikal","Lake Superior"],2],
  ["GEO","tf","Gurun Sahara berada di benua Asia",null,1],
  ["GEO","mc","El Niño umumnya menyebabkan apa di Indonesia?",["Banjir parah","Badai tropis","Kekeringan","Tsunami"],2],
  ["GEO","tf","Danau Baikal adalah danau terbesar di dunia berdasarkan luas permukaan",null,1],
  ["GEO","mc","Garis bujur 0° (Prime Meridian) melewati kota...",["Roma","Paris","Greenwich/London","Madrid"],2],
  ["GEO","tf","Filipina adalah negara kepulauan dengan jumlah pulau terbanyak di dunia",null,1],
  ["GEO","mc","Lapisan atmosfer bumi yang paling luar adalah...",["Troposfer","Stratosfer","Eksosfer","Termosfer"],2],
  ["GEO","tf","Ring of Fire tidak melewati wilayah Asia Tenggara sama sekali",null,1],
  ["GEO","mc","Batas alam antara benua Asia dan Eropa adalah...",["Pegunungan Himalaya","Pegunungan Alpen","Pegunungan Kaukasus","Pegunungan Ural"],3],
  ["GEO","tf","Delta sungai terbentuk di hulu sungai dekat pegunungan",null,1],
  ["GEO","mc","Iklim tropis ditandai dengan...",["Salju sepanjang tahun","Empat musim yang jelas","Suhu tinggi dan curah hujan tinggi sepanjang tahun","Suhu rendah dan kering"],2],
  ["GEO","tf","Angin muson timur membawa musim hujan ke Indonesia",null,1],
  ["GEO","mc","Negara dengan luas wilayah terbesar di dunia adalah...",["Amerika Serikat","Rusia","China","Kanada"],1],
  ["GEO","tf","Selat Sunda menghubungkan Samudra Hindia dan Laut Cina Selatan",null,1],
  ["GEO","mc","Peta topografi menggambarkan...",["Ketinggian dan kontur permukaan bumi","Batas wilayah politik","Kondisi cuaca","Distribusi penduduk"],0],
  ["GEO","tf","Stalagmit terbentuk di langit-langit gua dari pengendapan kalsium karbonat",null,1],
  ["GEO","mc","Zona Ekonomi Eksklusif (ZEE) Indonesia membentang sejauh...",["12 mil laut","350 mil laut","100 mil laut","200 mil laut"],3],
  ["GEO","tf","Gunung Krakatau terletak di Selat Malaka",null,1],
  ["GEO","mc","Negara di Asia Tenggara yang tidak memiliki lautan (landlocked) adalah...",["Laos","Myanmar","Vietnam","Thailand"],0],
  ["GEO","tf","Benua Australia dilintasi oleh garis khatulistiwa",null,1],
  ["GEO","mc","Hujan yang terjadi karena udara panas naik di daerah pegunungan disebut hujan...",["Orografis","Zenithal","Frontal","Buatan"],0],
  ["GEO","tf","Lempeng tektonik bergerak sangat cepat, sekitar beberapa meter per detik",null,1],
  ["GEO","mc","Hutan bakau (mangrove) biasanya ditemukan di...",["Padang rumput","Pegunungan tinggi","Pesisir pantai tropis","Padang pasir"],2],
  ["GEO","tf","Cuaca dan iklim adalah hal yang identik dan tidak bisa dibedakan",null,1],
  ["GEO","mc","Pegunungan Andes terletak di benua...",["Afrika","Amerika Utara","Asia","Amerika Selatan"],3],
  ["GEO","tf","Dataran tinggi di sepanjang pantai utara Jawa disebut pantura",null,1],
  ["GEO","mc","Angin yang bertiup dari samudra ke daratan pada musim tertentu disebut angin...",["Pasat","Puting beliung","Muson","Lokal"],2],
  ["GEO","tf","Korea Selatan dan Jepang terletak di benua Oseania",null,1],
  ["GEO","mc","Proses pengikisan tanah oleh air, angin, atau es disebut...",["Abrasi","Erosi","Deflasi","Sedimentasi"],1],
  ["GEO","tf","Danau Maninjau di Sumatera adalah danau vulkanik terbesar di dunia",null,1],
  ["GEO","mc","Wilayah dengan curah hujan sangat rendah (<250 mm/tahun) disebut...",["Sabana","Semi-arid","Stepa","Gurun (arid)"],3],
  ["GEO","tf","Koordinat 0° Lintang dan 0° Bujur berada di London, Inggris",null,1],
  ["GEO","mc","Lapisan atmosfer tempat terjadinya cuaca adalah...",["Mesosfer","Termosfer","Stratosfer","Troposfer"],3],
  ["GEO","tf","Gunung Semeru adalah gunung berapi tertinggi di Pulau Jawa",null,0],

  /* ===== SEJARAH 40 soal ===== */
  ["SEJ","mc","Proklamasi kemerdekaan Indonesia dibacakan pada tanggal...",["18 Agustus 1945","17 Agustus 1945","20 Mei 1945","15 Agustus 1945"],1],
  ["SEJ","tf","Perang Dunia I dimulai pada tahun 1939",null,1],
  ["SEJ","mc","Presiden pertama Republik Indonesia adalah...",["Soekarno","Soeharto","Syahrir","Mohammad Hatta"],0],
  ["SEJ","tf","Revolusi Perancis terjadi pada tahun 1848",null,1],
  ["SEJ","mc","Organisasi pergerakan nasional pertama Indonesia yang berdiri tahun 1908 adalah...",["PNI","Budi Utomo","Sarekat Islam","Indische Partij"],1],
  ["SEJ","tf","Joseph Stalin adalah pemimpin Jerman saat Perang Dunia II",null,1],
  ["SEJ","mc","Perjanjian yang secara resmi mengakhiri Perang Dunia I adalah...",["Perjanjian Paris","Perjanjian Potsdam","Perjanjian Yalta","Perjanjian Versailles"],3],
  ["SEJ","tf","Kerajaan Majapahit adalah kerajaan Islam terbesar di Nusantara",null,1],
  ["SEJ","mc","Peristiwa Reformasi yang menggulingkan Soeharto terjadi tahun...",["1997","1998","1996","1999"],1],
  ["SEJ","tf","Nelson Mandela pernah dipenjara selama 5 tahun",null,1],
  ["SEJ","mc","Kerajaan Sriwijaya berpusat di daerah...",["Jawa Tengah","Kalimantan","Palembang/Sumatera Selatan","Maluku"],2],
  ["SEJ","tf","Jepang menjajah Indonesia selama 3,5 tahun (1942–1945)",null,0],
  ["SEJ","mc","Sumpah Pemuda diikrarkan pada tanggal...",["17 Agustus 1928","1 Juni 1945","20 Mei 1908","28 Oktober 1928"],3],
  ["SEJ","tf","Pancasila dirumuskan pertama kali oleh Mohammad Hatta pada 17 Agustus 1945",null,1],
  ["SEJ","mc","Pahlawan nasional yang dikenal sebagai Bapak Pendidikan Nasional Indonesia adalah...",["Kartini","Mohammad Yamin","Ki Hajar Dewantara","Dewi Sartika"],2],
  ["SEJ","tf","Perang Dingin terjadi antara Amerika Serikat dan China",null,1],
  ["SEJ","mc","Tembok Berlin runtuh pada tahun...",["1989","1987","1985","1991"],0],
  ["SEJ","tf","Christopher Columbus pertama kali mendarat di Amerika pada tahun 1776",null,1],
  ["SEJ","mc","Perjanjian Renville antara Indonesia-Belanda ditandatangani tahun...",["1949","1947","1948","1946"],2],
  ["SEJ","tf","Kerajaan Mataram Islam berdiri di Jawa Tengah",null,0],
  ["SEJ","mc","Perang Diponegoro (1825–1830) melawan Belanda dipimpin oleh...",["Hasanuddin","Teuku Umar","Pangeran Diponegoro","Sultan Agung"],2],
  ["SEJ","tf","Konferensi Asia-Afrika pertama diadakan di Bandung pada tahun 1955",null,0],
  ["SEJ","mc","Kaisar Romawi pertama adalah...",["Augustus (Octavian)","Julius Caesar","Nero","Caligula"],0],
  ["SEJ","tf","Gerakan Reformasi Protestan dimulai oleh Martin Luther",null,0],
  ["SEJ","mc","Perang Salib dilancarkan untuk merebut kota...",["Konstantinopel","Yerusalem","Kairo","Mekkah"],1],
  ["SEJ","tf","Bom atom pertama dijatuhkan di Nagasaki pada 6 Agustus 1945",null,1],
  ["SEJ","mc","Perjanjian Bongaya (1667) merugikan kerajaan...",["Gowa-Tallo (Makassar)","Banten","Ternate","Mataram"],0],
  ["SEJ","tf","VOC adalah organisasi militer Inggris di Nusantara",null,1],
  ["SEJ","mc","Renaisans (Renaissance) dimulai di negara...",["Spanyol","Inggris","Italia","Perancis"],2],
  ["SEJ","tf","Mahatma Gandhi menggunakan metode perlawanan bersenjata terhadap Inggris",null,1],
  ["SEJ","mc","Negara pertama yang menjadi kekuatan nuklir di dunia adalah...",["Uni Soviet","Amerika Serikat","Inggris","China"],1],
  ["SEJ","tf","PBB didirikan pada tahun 1919 setelah Perang Dunia I",null,1],
  ["SEJ","mc","Kerajaan Islam pertama di Nusantara yang diakui sejarawan adalah...",["Demak","Ternate","Mataram Islam","Samudera Pasai"],3],
  ["SEJ","tf","Jenderal Soedirman adalah panglima besar TNI pertama Indonesia",null,0],
  ["SEJ","mc","Pertempuran Surabaya 10 November diperingati sebagai Hari...",["Pahlawan","Kemerdekaan","Pendidikan","Kebangkitan Nasional"],0],
  ["SEJ","tf","Uni Soviet resmi bubar pada tahun 1985",null,1],
  ["SEJ","mc","Penemuan mesin cetak oleh Gutenberg (~1440) merevolusi penyebaran...",["Ilmu pengetahuan dan informasi","Arsitektur","Pertanian","Perdagangan"],0],
  ["SEJ","tf","Agresi Militer Belanda I terjadi pada tahun 1945",null,1],
  ["SEJ","mc","Tokoh yang dijuluki Bapak Bangsa (Father of the Nation) India adalah...",["Jawaharlal Nehru","Mahatma Gandhi","Subhas Chandra Bose","Indira Gandhi"],1],
  ["SEJ","tf","Imperialisme adalah kebijakan mengisolasi diri dari negara lain",null,1],

  /* ===== NEGARA 40 soal ===== */
  ["NEG","mc","Ibu kota Jepang adalah...",["Tokyo","Hiroshima","Kyoto","Osaka"],0],
  ["NEG","tf","Bahasa resmi Brasil adalah Spanyol",null,1],
  ["NEG","mc","Mata uang resmi Jepang adalah...",["Yen","Won","Yuan","Ringgit"],0],
  ["NEG","tf","Kota New York adalah ibu kota Amerika Serikat",null,1],
  ["NEG","mc","Negara dengan garis pantai terpanjang di dunia adalah...",["Norwegia","Indonesia","Australia","Kanada"],3],
  ["NEG","tf","Monaco adalah negara terkecil di dunia berdasarkan luas wilayah",null,1],
  ["NEG","mc","Aliansi militer barat yang dibentuk setelah PD II adalah...",["SEATO","SCO","NATO","ANZUS"],2],
  ["NEG","tf","Benua Antartika dihuni oleh jutaan penduduk pribumi",null,1],
  ["NEG","mc","Piramida Giza berada di negara...",["Mesir","Maroko","Libya","Sudan"],0],
  ["NEG","tf","Kalimantan adalah pulau terbesar di dunia",null,1],
  ["NEG","mc","Berapa jumlah bahasa resmi PBB?",["8","6","5","4"],1],
  ["NEG","tf","Menara Eiffel berada di Brussels, Belgia",null,1],
  ["NEG","mc","Astronot pertama yang berjalan di bulan adalah...",["Buzz Aldrin","John Glenn","Neil Armstrong","Yuri Gagarin"],2],
  ["NEG","tf","Bahasa Indonesia termasuk rumpun bahasa Indo-Eropa",null,1],
  ["NEG","mc","Olimpiade modern pertama (1896) diselenggarakan di...",["London","Paris","Roma","Athena"],3],
  ["NEG","tf","Korea Utara dan Korea Selatan telah menandatangani perjanjian damai resmi",null,1],
  ["NEG","mc","Negara dengan hutan hujan tropis terluas di dunia adalah...",["Brasil","Kongo","Peru","Indonesia"],0],
  ["NEG","tf","Wayang kulit Indonesia belum pernah diakui UNESCO",null,1],
  ["NEG","mc","Ibu kota Australia adalah...",["Brisbane","Melbourne","Sydney","Canberra"],3],
  ["NEG","tf","India adalah negara dengan jumlah penduduk terbanyak di dunia saat ini",null,0],
  ["NEG","mc","Negara yang menggunakan sistem monarki absolut di Asia Barat adalah...",["Thailand","Arab Saudi","Jepang","Malaysia"],1],
  ["NEG","tf","Bahasa Mandarin adalah bahasa resmi di Taiwan",null,0],
  ["NEG","mc","Negara yang paling banyak memiliki penutur bahasa Spanyol adalah...",["Argentina","Spanyol","Meksiko","Kolombia"],2],
  ["NEG","tf","Uni Eropa (EU) memiliki parlemen yang dipilih langsung oleh warga negara anggota",null,0],
  ["NEG","mc","Kota dengan populasi terbesar di dunia saat ini adalah...",["Shanghai","Mumbai","Tokyo","New York"],2],
  ["NEG","tf","Swiss adalah negara yang netral dan tidak bergabung dengan NATO",null,0],
  ["NEG","mc","Negara di Eropa yang tidak menggunakan Euro meskipun anggota EU adalah...",["Perancis","Swedia","Spanyol","Italia"],1],
  ["NEG","tf","Singapura adalah negara dengan luas wilayah terkecil di Asia Tenggara",null,0],
  ["NEG","mc","Negara yang berbatasan langsung dengan Indonesia di darat adalah...",["Timor Leste saja","Malaysia dan Papua Nugini","Filipina dan Malaysia","Malaysia, Papua Nugini, dan Timor Leste"],3],
  ["NEG","tf","Piala Dunia FIFA 2022 diadakan di Qatar",null,0],
  ["NEG","mc","Ibu kota Kanada adalah...",["Montreal","Ottawa","Toronto","Vancouver"],1],
  ["NEG","tf","Tembok Besar China bisa terlihat dengan mata telanjang dari luar angkasa",null,1],
  ["NEG","mc","Negara dengan ekonomi terbesar kedua di dunia adalah...",["India","Jerman","China","Jepang"],2],
  ["NEG","tf","Ratu Elizabeth II adalah kepala negara Inggris yang meninggal pada September 2022",null,0],
  ["NEG","mc","Kota suci umat Islam selain Mekkah yang terletak di Arab Saudi adalah...",["Madinah","Damaskus","Bagdad","Kairo"],0],
  ["NEG","tf","Piala Dunia FIFA diadakan setiap 4 tahun sekali",null,0],
  ["NEG","mc","Negara yang meluncurkan satelit Sputnik pertama ke orbit bumi adalah...",["Amerika Serikat","Uni Soviet","China","Inggris"],1],
  ["NEG","tf","Brasil pernah menjadi tuan rumah Olimpiade pada tahun 2016 di Rio de Janeiro",null,0],
  ["NEG","mc","Ibu kota Uni Emirat Arab adalah...",["Abu Dhabi","Ajman","Dubai","Sharjah"],0],
  ["NEG","tf","Indonesia pernah menjadi tuan rumah KTT ASEAN",null,0],

  /* ===== ADVANCED 70 soal ===== */
  ["ADV","mc","Prinsip ketidakpastian dalam mekanika kuantum dikemukakan oleh...",["Heisenberg","Bohr","Planck","Schrödinger"],0],
  ["ADV","tf","Dalam relativitas Einstein, massa benda bertambah seiring kecepatan mendekati kecepatan cahaya",null,0],
  ["ADV","mc","Enzim yang memecah protein menjadi asam amino disebut...",["Amilase","Protease","Laktase","Lipase"],1],
  ["ADV","tf","DNA mengandung gula deoksiribosa, sedangkan RNA mengandung gula ribosa",null,0],
  ["ADV","mc","Paradoks kembar dalam fisika berkaitan dengan...",["Dilatasi waktu dalam teori relativitas","Mekanika kuantum","Hukum gravitasi","Termodinamika"],0],
  ["ADV","mc","Dalam termodinamika, entropi sistem tertutup akan...",["Bertambah lalu berkurang","Bertambah atau tetap (tidak pernah berkurang)","Selalu berkurang","Tetap konstan"],1],
  ["ADV","tf","Supernova adalah ledakan dahsyat dari bintang masif yang sekarat",null,0],
  ["ADV","mc","Dalam bilangan kompleks, nilai i² adalah...",["1","-i","-1","i"],2],
  ["ADV","tf","Teorema Pythagoras hanya berlaku pada geometri Euclidean (datar)",null,0],
  ["ADV","mc","Fenomena di mana cahaya melepaskan elektron dari logam disebut...",["Efek fotolistrik","Polarisasi","Efek Compton","Difraksi"],0],
  ["ADV","mc","Penyakit akibat kekurangan vitamin D adalah...",["Skorbut","Anemia","Beri-beri","Rakitis"],3],
  ["ADV","tf","Grafena terdiri dari satu lapisan atom karbon yang tersusun secara heksagonal",null,0],
  ["ADV","mc","Teorema Bayes digunakan dalam bidang...",["Geometri","Aljabar abstrak","Kalkulus","Probabilitas dan Statistika"],3],
  ["ADV","tf","Neuron berkomunikasi satu sama lain melalui sinapsis",null,0],
  ["ADV","mc","Konsep 'invisible hand' (tangan tak kasat mata) dalam ekonomi dikemukakan oleh...",["Karl Marx","John Keynes","Milton Friedman","Adam Smith"],3],
  ["ADV","tf","RNA umumnya berbentuk untai tunggal, berbeda dari DNA yang untai ganda",null,0],
  ["ADV","mc","Bilangan e (basis logaritma natural) kira-kira sama dengan...",["2,718","1,414","1,618","3,142"],0],
  ["ADV","tf","Atom netral memiliki jumlah proton sama dengan jumlah elektron",null,0],
  ["ADV","mc","Teori evolusi melalui seleksi alam dikemukakan oleh...",["Louis Pasteur","Gregor Mendel","Charles Darwin","Carl Linnaeus"],2],
  ["ADV","tf","Magnet bisa dipisahkan menjadi kutub utara saja atau kutub selatan saja (monopol magnetik)",null,1],
  ["ADV","mc","Unsur besi (Fe-56) memiliki energi ikat nukleon tertinggi, artinya...",["Besi konduktor terbaik","Inti besi paling stabil","Besi paling radioaktif","Besi logam terkuat"],1],
  ["ADV","tf","Prion adalah agen penyakit infeksius yang terbuat dari protein yang salah lipat",null,0],
  ["ADV","mc","Transformasi Fourier mengubah fungsi dari...",["Kontinu ke diskret","Domain real ke kompleks","Domain frekuensi ke spasial","Domain waktu ke domain frekuensi"],3],
  ["ADV","tf","Stephen Hawking mengusulkan bahwa lubang hitam memancarkan radiasi (Hawking Radiation)",null,0],
  ["ADV","mc","Hukum Mendel I tentang pewarisan sifat disebut hukum...",["Variasi","Asortasi bebas","Segregasi","Dominansi"],2],
  ["ADV","tf","Kelarutan gula (sukrosa) dalam air meningkat seiring naiknya suhu",null,0],
  ["ADV","mc","Dalam logika matematika, pernyataan yang selalu bernilai BENAR disebut...",["Tautologi","Kontingensi","Implikasi","Kontradiksi"],0],
  ["ADV","tf","Pemendekan telomere dikaitkan dengan proses penuaan sel",null,0],
  ["ADV","mc","Golden ratio (φ) kira-kira bernilai...",["1,618","1,414","0,618","2,236"],0],
  ["ADV","tf","CRISPR-Cas9 adalah teknologi yang digunakan untuk mengedit gen",null,0],
  ["ADV","mc","Aurora borealis terjadi karena...",["Rotasi bumi yang cepat","Interaksi partikel bermuatan dari matahari dengan atmosfer","Pantulan cahaya dari es","Letusan gunung berapi bawah laut"],1],
  ["ADV","tf","Antibiotik efektif melawan infeksi yang disebabkan oleh virus",null,1],
  ["ADV","mc","Konsep 'half-life' (waktu paruh) digunakan dalam konteks...",["Peluruhan radioaktif","Kimia organik","Ekonomi makro","Pemasaran"],0],
  ["ADV","tf","Kecerdasan buatan (AI) modern umumnya menggunakan arsitektur jaringan saraf tiruan",null,0],
  ["ADV","mc","Jika massa 5 kg dan percepatan 3 m/s², berapa gaya (F=ma)?",["8 N","53 N","2 N","15 N"],3],
  ["ADV","mc","'Kucing Schrödinger' adalah ilustrasi dari konsep fisika kuantum tentang...",["Entropi","Prinsip eksklusi Pauli","Dualitas gelombang-partikel","Superposisi kuantum"],3],
  ["ADV","tf","DNA mitokondria diwarisi secara maternal (dari ibu)",null,0],
  ["ADV","mc","Hukum Hardy-Weinberg menyatakan frekuensi alel dalam populasi...",["Hanya dipengaruhi seleksi alam","Selalu bertambah","Meningkat setiap generasi","Konstan dalam populasi ideal yang besar"],3],
  ["ADV","tf","Persamaan Schrödinger mendeskripsikan evolusi fungsi gelombang sistem kuantum",null,0],
  ["ADV","mc","Elastisitas permintaan sempurna (perfectly elastic) berarti...",["Penawaran = permintaan selalu","Permintaan tidak berubah saat harga berubah","Harga tidak berubah","Permintaan sangat sensitif terhadap perubahan harga"],3],
  ["ADV","tf","Virus HIV termasuk retrovirus karena menggunakan RNA sebagai materi genetiknya",null,0],
  ["ADV","mc","Teori String dalam fisika menyatakan bahwa partikel dasar sebenarnya adalah...",["Quark","Atom","Medan energi","Senar (string) bergetar dalam ruang multidimensi"],3],
  ["ADV","tf","Hukum termodinamika pertama menyatakan energi dalam sistem tertutup dapat diciptakan dari ketiadaan",null,1],
  ["ADV","mc","Efek terowongan (tunnel effect) dalam mekanika kuantum memungkinkan partikel...",["Berinteraksi tanpa kontak fisik","Bergerak lebih cepat dari cahaya","Berubah menjadi energi","Melewati penghalang energi yang secara klasik tidak bisa ditembus"],3],
  ["ADV","tf","Sel punca (stem cell) dapat berdiferensiasi menjadi berbagai jenis sel",null,0],
  ["ADV","mc","Pernyataan 'Jika P maka Q' (P→Q) bernilai SALAH hanya jika...",["Keduanya salah","P benar dan Q salah","P salah dan Q benar","Keduanya benar"],1],
  ["ADV","tf","Lubang hitam (black hole) memiliki gravitasi sedemikian kuat sehingga cahaya tidak bisa lolos dari event horizon-nya",null,0],
  ["ADV","mc","Prinsip Le Chatelier menyatakan bahwa sistem kesetimbangan akan...",["Tidak berubah saat kondisi berubah","Bergerak untuk mengurangi pengaruh gangguan eksternal","Selalu bergerak ke arah produk","Selalu meningkatkan suhu"],1],
  ["ADV","tf","Neuroplastisitas otak manusia memungkinkan otak membentuk koneksi baru sepanjang hidup",null,0],
  ["ADV","mc","Distribusi normal (bell curve) memiliki sifat...",["Varians nol","Distribusi yang selalu miring","Semua nilai di atas rata-rata","Mean = Median = Modus"],3],
  ["ADV","tf","Quantum entanglement adalah fenomena di mana dua partikel saling terhubung secara instan",null,0],
  ["ADV","mc","Teori Big Bang menyatakan alam semesta bermula dari...",["Tabrakan galaksi","Penciptaan materi dari ruang hampa","Ledakan bintang besar","Singularitas yang sangat padat dan panas"],3],
  ["ADV","tf","Resistensi antibiotik menyebabkan bakteri tidak bisa dibunuh oleh antibiotik tertentu",null,0],
  ["ADV","mc","Konsep 'tragedy of the commons' dalam ekonomi menggambarkan masalah...",["Kemiskinan ekstrem","Monopoli pasar","Eksploitasi berlebihan sumber daya bersama yang tidak diatur","Pengangguran struktural"],2],
  ["ADV","tf","Isomer kimia memiliki rumus molekul yang sama tetapi struktur yang berbeda",null,0],
  ["ADV","mc","Fenomena difraksi cahaya membuktikan sifat ... dari cahaya",["Gelombang","Energi","Listrik","Partikel"],0],
  ["ADV","tf","Epigenetik mempelajari perubahan ekspresi gen yang tidak melibatkan perubahan urutan DNA",null,0],
  ["ADV","mc","Himpunan bilangan real (ℝ) adalah...",["Superset yang mencakup bilangan rasional dan irasional","Hanya bilangan positif","Subset dari bilangan rasional","Sama dengan bilangan bulat"],0],
  ["ADV","tf","Teorema Terakhir Fermat menyatakan tidak ada solusi bilangan bulat positif untuk aⁿ+bⁿ=cⁿ saat n>2",null,0],
  ["ADV","mc","Konstanta Planck (h) berperan penting dalam...",["Termodinamika klasik","Teori gravitasi Newton","Relativitas umum","Mekanika kuantum"],3],
  ["ADV","tf","Penyakit Alzheimer dikaitkan dengan penumpukan protein amyloid-beta di otak",null,0],
  ["ADV","mc","Konsep 'prisoner's dilemma' berasal dari bidang...",["Psikologi kriminal","Kriminologi","Sosiologi","Teori permainan (game theory)"],3],
  ["ADV","tf","Dalam fisika relativitas, waktu berjalan lebih lambat di medan gravitasi yang sangat kuat",null,0],
  ["ADV","mc","Mekanisme CRISPR-Cas9 untuk mengedit gen berasal dari sistem imun alami...",["Yeast","Bakteri","Manusia","Virus"],1],
  ["ADV","tf","Fotosintesis dan respirasi seluler secara umum adalah proses yang berlawanan satu sama lain",null,0],
  ["ADV","mc","Dalam ekonomi perilaku, 'loss aversion' berarti manusia...",["Selalu menghindari keputusan","Lebih sensitif terhadap kerugian daripada keuntungan setara","Selalu memilih risiko tinggi","Tidak peduli dengan hasil keputusan"],1],
  ["ADV","tf","Relativitas khusus Einstein berlaku untuk kerangka acuan inersia (gerak konstan)",null,0],
  ["ADV","mc","Sistem imun adaptif manusia terutama melibatkan...",["Komplemen dan interferon","Sel fagosit saja","Limfosit T dan limfosit B","Sel darah merah dan trombosit"],2],
  ["ADV","tf","Gelombang gravitasi pertama kali terdeteksi langsung oleh LIGO pada tahun 2015",null,0],
  ["ADV","mc","Dalam ilmu komputer, algoritma rekursif adalah fungsi yang...",["Hanya memproses bilangan bulat","Berjalan paralel","Memanggil dirinya sendiri","Tidak pernah berhenti"],2],

  /* ===== TRIVIA 197 soal ===== */
  ["TRV","mc","Manusia dewasa normal memiliki berapa tulang?",["196","206","226","216"],1],
  ["TRV","tf","Kupu-kupu dapat merasakan rasa melalui kaki mereka",null,0],
  ["TRV","mc","Planet terbesar dalam tata surya kita adalah...",["Neptunus","Saturnus","Jupiter","Uranus"],2],
  ["TRV","tf","Gurita memiliki tiga jantung",null,0],
  ["TRV","mc","Siapa pengarang seri novel 'Harry Potter'?",["C.S. Lewis","Roald Dahl","J.R.R. Tolkien","J.K. Rowling"],3],
  ["TRV","tf","Hiu termasuk dalam kelas mamalia laut",null,1],
  ["TRV","mc","Angka Romawi 'C' mewakili angka...",["1000","100","500","50"],1],
  ["TRV","tf","Matahari adalah bintang terbesar yang ada di alam semesta",null,1],
  ["TRV","mc","Hewan dengan masa kehamilan (gestasi) terpanjang adalah...",["Badak","Gajah Afrika","Paus biru","Jerapah"],1],
  ["TRV","tf","Air mendidih pada suhu 100°C pada tekanan standar (1 atm)",null,0],
  ["TRV","mc","Siapa pelukis 'Mona Lisa'?",["Raphael","Michelangelo","Leonardo da Vinci","Rembrandt"],2],
  ["TRV","tf","Laba-laba (spider) termasuk dalam kelas Insekta",null,1],
  ["TRV","mc","Berapakah jumlah huruf dalam alfabet bahasa Inggris?",["24","27","26","25"],2],
  ["TRV","tf","Bambu termasuk dalam famili rumput-rumputan (Poaceae)",null,0],
  ["TRV","mc","Dalam catur, buah yang bergerak membentuk huruf L adalah...",["Uskup/Bishop","Kuda/Knight","Menara/Rook","Ratu/Queen"],1],
  ["TRV","tf","Kelelawar adalah satu-satunya mamalia yang bisa terbang secara aktif",null,0],
  ["TRV","mc","Planet yang dikenal sebagai 'Planet Merah' adalah...",["Merkurius","Mars","Jupiter","Venus"],1],
  ["TRV","tf","Semua serangga dewasa memiliki tepat 6 kaki",null,0],
  ["TRV","mc","Tulang terpanjang dalam tubuh manusia adalah...",["Radius","Tibia (tulang kering)","Femur (tulang paha)","Humerus (lengan atas)"],2],
  ["TRV","tf","Gajah Afrika bertelinga lebih besar dari gajah Asia",null,0],
  ["TRV","mc","Unsur kimia paling melimpah di alam semesta adalah...",["Karbon","Helium","Oksigen","Hidrogen"],3],
  ["TRV","tf","Kubus Rubik diciptakan oleh orang Hungaria bernama Ernő Rubik",null,0],
  ["TRV","mc","Berapa jumlah sisi pada dadu standar?",["4","12","8","6"],3],
  ["TRV","tf","Kopi arabika berasal dari Ethiopia",null,0],
  ["TRV","mc","Berapa warna yang ada dalam bendera Indonesia?",["2","1","3","4"],0],
  ["TRV","tf","Bunglon bisa mengubah warna kulitnya",null,0],
  ["TRV","mc","Gambar presiden di uang kertas 1 dollar Amerika adalah...",["George Washington","Thomas Jefferson","Abraham Lincoln","Benjamin Franklin"],0],
  ["TRV","tf","Bahasa Arab ditulis dari kanan ke kiri",null,0],
  ["TRV","mc","Hewan yang memiliki sidik jari hampir identik dengan manusia adalah...",["Orangutan","Koala","Simpanse","Gorila"],1],
  ["TRV","tf","Mozart mulai menulis komposisi musik pada usia sekitar 5–6 tahun",null,0],
  ["TRV","mc","Hewan terbesar di dunia berdasarkan berat adalah...",["Gajah Afrika","Hiu paus","Paus biru","Kuda nil"],2],
  ["TRV","tf","Gurita (oktopus) dan cumi-cumi termasuk dalam kelompok moluska",null,0],
  ["TRV","mc","Berapa jumlah pemain dalam satu tim sepak bola di lapangan?",["9","10","12","11"],3],
  ["TRV","tf","Emas (Au) termasuk logam mulia karena tidak mudah bereaksi dengan zat lain",null,0],
  ["TRV","mc","Internet dan World Wide Web (WWW) adalah...",["Hal yang sama persis","Berbeda: internet=jaringan, WWW=layanan berbasis internet","Hanya berbeda nama saja","Keduanya diciptakan Tim Berners-Lee"],1],
  ["TRV","tf","Kucing domestik dan singa termasuk dalam famili Felidae",null,0],
  ["TRV","mc","Mencampur semua warna cahaya (model additive) menghasilkan warna...",["Hitam","Coklat","Putih","Abu-abu"],2],
  ["TRV","tf","Anjing pertama yang dikirim ke luar angkasa bernama Laika",null,0],
  ["TRV","mc","Mata uang resmi sebagian besar negara Uni Eropa adalah...",["Dolar","Pound","Euro","Franc"],2],
  ["TRV","tf","Bola tenis lapangan berwarna kuning kehijauan (lime/chartreuse)",null,0],
  ["TRV","mc","Fatamorgana (mirage) terjadi karena...",["Hamburan Rayleigh","Difraksi gelombang cahaya","Pantulan di cermin air","Refraksi cahaya akibat perbedaan suhu lapisan udara"],3],
  ["TRV","tf","Kulit adalah organ terbesar dalam tubuh manusia",null,0],
  ["TRV","mc","Bahasa pemrograman yang dikembangkan oleh Guido van Rossum adalah...",["Ruby","Java","C++","Python"],3],
  ["TRV","tf","Virus HIV menyerang sel T (CD4+) pada sistem imun manusia",null,0],
  ["TRV","mc","Olahraga dengan penggemar terbanyak di dunia adalah...",["Basket","Sepak bola","Kriket","Tenis"],1],
  ["TRV","tf","Cahaya tampak (visible light) hanya merupakan sebagian kecil dari spektrum elektromagnetik",null,0],
  ["TRV","mc","Berapa ruang (kamar) pada jantung manusia?",["4","5","2","3"],0],
  ["TRV","tf","Konsep angka nol (0) pertama kali digunakan secara matematis oleh peradaban India",null,0],
  ["TRV","mc","Hewan yang secara biologis bisa 'kekal' (immortal) adalah...",["Penyu raksasa","Elang laut","Kura-kura Aldabra","Ubur-ubur (Turritopsis dohrnii)"],3],
  ["TRV","tf","Otak manusia menggunakan sekitar 20% energi tubuh meskipun hanya 2% dari berat badan",null,0],
  ["TRV","mc","Bahasa yang memiliki alfabet/huruf terbanyak di dunia adalah...",["Sansekerta","Yunani","Arab","Khmer (Kamboja)"],3],
  ["TRV","tf","Kodok dan katak pohon termasuk dalam ordo Anura",null,0],
  ["TRV","mc","Buah dengan biji tunggal terbesar di dunia adalah...",["Alpukat","Coco de Mer","Kelapa","Durian"],1],
  ["TRV","tf","Thomas Edison mempopulerkan bola lampu pijar secara komersial",null,0],
  ["TRV","mc","Hewan yang dikenal memiliki ingatan paling kuat adalah...",["Lumba-lumba","Gajah","Anjing","Simpanse"],1],
  ["TRV","tf","Warna pelangi selalu muncul dalam urutan merah-jingga-kuning-hijau-biru-nila-ungu",null,0],
  ["TRV","mc","Bahan kimia yang membuat cabai terasa pedas adalah...",["Piperine","Allicin","Capsaicin","Gingerol"],2],
  ["TRV","tf","Lebah madu pekerja mati setelah menyengat manusia karena sengatnya tersangkut",null,0],
  ["TRV","mc","Novel 'Don Quixote' ditulis oleh...",["Cervantes","Tolstoy","Shakespeare","Dostoevsky"],0],
  ["TRV","tf","Daun berwarna hijau karena mengandung klorofil",null,0],
  ["TRV","mc","Kata 'selfie' resmi masuk kamus Oxford pada tahun...",["2015","2010","2013","2018"],2],
  ["TRV","tf","Uang kertas pertama di dunia berasal dari China",null,0],
  ["TRV","mc","Yang dimaksud dengan 'blue moon' adalah...",["Bulan purnama kedua dalam satu bulan kalender","Bulan yang terlihat lebih besar dari biasanya","Fenomena gerhana bulan","Bulan berwarna biru"],0],
  ["TRV","tf","Sapi dapat melihat warna merah dengan jelas",null,1],
  ["TRV","mc","Olahraga taekwondo berasal dari negara...",["Korea","Jepang","China","Thailand"],0],
  ["TRV","tf","Guiness World Records adalah buku yang paling banyak terjual tiap tahun setelah Alkitab",null,0],
  ["TRV","mc","Bahan kimia yang membuat bawang bombay membuat mata berair adalah...",["Quercetine","Allicin","Syn-propanethial-S-oxide","Sinigrin"],2],
  ["TRV","tf","Cheetah adalah hewan tercepat di darat",null,0],
  ["TRV","mc","Simbol '$' untuk dolar berasal dari modifikasi huruf...",["D (dollar)","S dan I (shilling)","P (peso Meksiko)","US singkatan"],2],
  ["TRV","tf","Durian dikenal sebagai 'raja buah' di Asia Tenggara",null,0],
  ["TRV","mc","Gitar standar memiliki berapa senar?",["4","5","6","7"],2],
  ["TRV","tf","Film animasi panjang pertama Walt Disney adalah Snow White and the Seven Dwarfs (1937)",null,0],
  ["TRV","mc","Nama ilmiah untuk manusia modern adalah...",["Homo habilis","Homo sapiens","Homo erectus","Homo neanderthalensis"],1],
  ["TRV","tf","Kucing tidak memiliki reseptor rasa manis (tidak bisa merasakan manis)",null,0],
  ["TRV","mc","Satu-satunya keajaiban dunia kuno yang masih ada hingga saat ini adalah...",["Menara Eiffel","Tembok Besar China","Piramida Giza","Colosseum Roma"],2],
  ["TRV","tf","Yuri Gagarin dari Uni Soviet adalah manusia pertama yang terbang ke luar angkasa (1961)",null,0],
  ["TRV","mc","Jejaring sosial mana yang pertama kali diluncurkan?",["LinkedIn (2003)","Instagram (2010)","Twitter (2006)","Facebook (2004)"],0],
  ["TRV","tf","Kucing memiliki lebih banyak jari di kaki depan (5) dibanding kaki belakang (4)",null,0],
  ["TRV","mc","Fenomena 'déjà vu' adalah pengalaman...",["Mengingat kenangan orang lain","Melihat hantu","Tidur sambil berjalan","Merasa pernah mengalami situasi yang sebenarnya baru"],3],
  ["TRV","tf","Keju mozzarella berasal dari Italia",null,0],
  ["TRV","mc","Nomor darurat yang berlaku di seluruh Uni Eropa adalah...",["999","000","911","112"],3],
  ["TRV","tf","Paus biru adalah mamalia terbesar yang pernah ada di Bumi",null,0],
  ["TRV","mc","Espresso berasal dari negara...",["Brasil","Turki","Italia","Kolombia"],2],
  ["TRV","tf","Sebagian besar penderita buta warna masih bisa melihat warna, hanya tidak bisa membedakan tertentu",null,0],
  ["TRV","mc","Kata 'robot' pertama kali digunakan dalam drama karya penulis Ceko...",["Karel Čapek","Franz Kafka","Jaroslav Hašek","Milan Kundera"],0],
  ["TRV","tf","Pohon bristlecone pine adalah pohon individu tertua yang masih hidup, berusia lebih dari 4800 tahun",null,0],
  ["TRV","mc","Bahasa Jawa memiliki penutur terbanyak di...",["Malaysia","Indonesia","Brunei","Timor Leste"],1],
  ["TRV","tf","Bambu dapat tumbuh hingga 90 cm dalam satu hari pada kondisi tertentu",null,0],
  ["TRV","mc","Nama asli Bunda Teresa (Mother Teresa) adalah...",["Maria Theresa","Agnes Gonxha Bojaxhiu","Rosa de Lima","Anna Teresa Kolodziej"],1],
  ["TRV","tf","Nyamuk adalah hewan yang paling banyak menyebabkan kematian manusia di dunia",null,0],
  ["TRV","mc","Komposer 'Für Elise' dan 'Ode to Joy' adalah...",["Handel","Mozart","Bach","Beethoven"],3],
  ["TRV","tf","Air soda (sparkling water) lebih asam dari air putih biasa karena CO₂ membentuk asam karbonat",null,0],
  ["TRV","mc","Novel Pinocchio ditulis oleh penulis asal...",["Italia","Spanyol","Denmark","Perancis"],0],
  ["TRV","tf","Nanas mengandung enzim bromelain yang dapat membantu pencernaan protein",null,0],
  ["TRV","mc","Lagu kebangsaan Indonesia 'Indonesia Raya' diciptakan oleh...",["C. Simanjuntak","Ismail Marzuki","W.R. Soepratman","Gesang"],2],
  ["TRV","tf","Gunung Everest bertambah sedikit lebih tinggi setiap tahun akibat pergerakan lempeng tektonik",null,0],
  ["TRV","mc","Hewan yang tidur paling banyak dalam sehari (sekitar 22 jam) adalah...",["Kucing","Koala","Malas (Sloth)","Kelelawar"],1],
  ["TRV","tf","Madu tidak akan membusuk dan bisa bertahan ribuan tahun",null,0],
  ["TRV","mc","Buku yang paling banyak diterjemahkan ke bahasa lain di dunia adalah...",["Alkitab","Al-Quran","Don Quixote","Harry Potter"],0],
  ["TRV","tf","Kupu-kupu termasuk dalam ordo Lepidoptera",null,0],
  ["TRV","mc","Siapa yang menulis 'Romeo and Juliet'?",["Charles Dickens","Oscar Wilde","Mark Twain","William Shakespeare"],3],
  ["TRV","tf","Satu jam terdiri dari tepat 3600 detik",null,0],
  ["TRV","mc","Hewan yang bisa meregenerasi anggota tubuh yang hilang (termasuk kaki) secara lengkap adalah...",["Buaya","Salamander","Iguana","Kadal ekor biasa"],1],
  ["TRV","mc","Tulang yang melindungi otak manusia disebut...",["Kranium (tengkorak)","Klavikula","Sternum","Mandibula"],0],
  ["TRV","tf","Kata 'set' memiliki jumlah definisi terbanyak dalam kamus bahasa Inggris",null,0],
  ["TRV","mc","Aurora australis adalah fenomena cahaya di...",["Bawah laut","Langit khatulistiwa","Langit kutub selatan","Sekitar gunung berapi"],2],
  ["TRV","tf","Kelelawar menggunakan ekolokasi (sonar) untuk navigasi di kegelapan",null,0],
  ["TRV","mc","Dibanding warna merah, warna biru dalam spektrum cahaya memiliki...",["Kecepatan lebih rendah di vakum","Panjang gelombang lebih panjang","Energi lebih rendah","Frekuensi lebih tinggi"],3],
  ["TRV","tf","Macan tutul (leopard) dan jaguar adalah hewan yang sama",null,1],
  ["TRV","mc","Nama kimia untuk garam dapur adalah...",["Natrium sulfat","Natrium bikarbonat","Kalsium karbonat","Natrium klorida"],3],
  ["TRV","tf","Saat seseorang bersin, matanya otomatis menutup",null,0],
  ["TRV","mc","Jumlah gigi permanen orang dewasa tidak termasuk gigi bungsu adalah...",["30","24","28","32"],2],
  ["TRV","tf","Bumi adalah planet ketiga dari matahari dalam tata surya kita",null,0],
  ["TRV","mc","Sherlock Holmes tinggal di alamat...",["221B Baker Street","13 Baker Street","221A Baker Street","221C Baker Street"],0],
  ["TRV","tf","Jaringan 5G menggunakan frekuensi gelombang yang lebih tinggi dibanding 4G",null,0],
  ["TRV","mc","Buah yang unik karena bijinya (achene) terdapat di permukaan luarnya adalah...",["Semangka","Anggur","Stroberi","Tomat"],2],
  ["TRV","tf","Indonesia memiliki lebih dari 700 bahasa daerah",null,0],
  ["TRV","mc","Festival Nyepi adalah hari raya umat Hindu yang paling terkenal di...",["Bali","Malaysia","India","Singapura"],0],
  ["TRV","tf","Wortel awalnya berwarna ungu sebelum dikembangkan menjadi oranye di Belanda",null,0],
  ["TRV","mc","Gerak Brown (Brownian motion) adalah...",["Warna cokelat dalam larutan","Gerakan acak partikel kecil dalam fluida","Getaran molekul padatan","Aliran arus konveksi"],1],
  ["TRV","tf","Vincent van Gogh hanya berhasil menjual satu lukisan semasa hidupnya",null,0],
  ["TRV","mc","Nama 'Indonesia' berasal dari bahasa Yunani dan berarti...",["Negeri seribu pulau","Kepulauan India","Tanah di bawah angin","Tanah subur di timur"],1],
  ["TRV","tf","Microsoft didirikan bersama oleh Bill Gates dan Paul Allen",null,0],
  ["TRV","mc","Standar IQ rata-rata yang ditetapkan secara internasional adalah...",["100","90","110","120"],0],
  ["TRV","tf","Planet Venus berputar berlawanan arah (retrograde) dibanding sebagian besar planet lain",null,0],
  ["TRV","mc","Simbol π pertama kali digunakan oleh matematikawan...",["Isaac Newton","William Jones","Archimedes","Leonhard Euler"],1],
  ["TRV","tf","Pulau Sumatra adalah pulau terbesar yang sepenuhnya berada dalam wilayah Indonesia",null,0],

  /* ===== AKT (AKUNTANSI) 28 soal ===== */
  ["AKT","mc","Persamaan dasar akuntansi adalah...",["Aktiva = Kewajiban − Modal","Kewajiban = Aktiva + Modal","Aktiva = Kewajiban + Modal","Modal = Aktiva + Kewajiban"],2],
  ["AKT","mc","Jika aktiva Rp200 juta dan kewajiban Rp80 juta, maka modal adalah...",["Rp80 juta","Rp160 juta","Rp120 juta","Rp280 juta"],2],
  ["AKT","mc","Pada sistem debit-kredit, pembelian aset secara tunai dicatat dengan...",["Debit Kas, Kredit Aset","Debit Utang, Kredit Aset","Debit Aset, Kredit Kas","Debit Modal, Kredit Aset"],2],
  ["AKT","mc","Jurnal umum digunakan untuk...",["Menutup buku besar","Membuat laporan arus kas","Menyusun neraca saldo","Mencatat semua transaksi secara kronologis"],3],
  ["AKT","mc","Buku besar (ledger) berfungsi untuk...",["Mencatat bukti transaksi asli","Menghitung pajak perusahaan","Menyusun laporan laba rugi","Mengelompokkan transaksi berdasarkan akun"],3],
  ["AKT","mc","Neraca (balance sheet) menyajikan informasi tentang...",["Posisi keuangan: aktiva, kewajiban, dan ekuitas","Arus kas masuk dan keluar","Laba bersih perusahaan","Pendapatan dan beban"],0],
  ["AKT","mc","Laporan laba rugi melaporkan...",["Perubahan modal pemilik","Arus kas dari operasi","Posisi keuangan pada tanggal tertentu","Pendapatan dan beban selama satu periode"],3],
  ["AKT","mc","Aset yang paling mudah diubah menjadi uang tunai disebut...",["Aset tetap","Aset tidak berwujud","Investasi jangka panjang","Aset lancar"],3],
  ["AKT","mc","Metode penyusutan yang mengalokasikan beban sama setiap tahun disebut...",["Unit produksi","Garis lurus (straight-line)","Sum-of-years-digits","Saldo menurun"],1],
  ["AKT","mc","Pada metode persediaan FIFO, barang yang pertama masuk akan...",["Dinilai dengan harga terbaru","Keluar pertama","Keluar terakhir","Tetap disimpan paling lama"],1],
  ["AKT","mc","Arus kas dari aktivitas operasi mencakup...",["Penerimaan dari penjualan barang","Pembayaran dividen","Pembelian mesin pabrik","Pelunasan utang bank jangka panjang"],0],
  ["AKT","mc","Utang usaha (accounts payable) merupakan bagian dari...",["Kewajiban lancar","Ekuitas pemilik","Kewajiban tidak lancar","Aset lancar"],0],
  ["AKT","mc","Jika perusahaan membeli perlengkapan kantor secara kredit, jurnalnya adalah...",["Debit Kas, Kredit Perlengkapan","Debit Perlengkapan, Kredit Utang Usaha","Debit Modal, Kredit Kas","Debit Utang Usaha, Kredit Perlengkapan"],1],
  ["AKT","mc","Nilai buku (book value) suatu aset tetap adalah...",["Harga jual di pasar saat ini","Harga penggantian aset baru","Harga perolehan dikurangi akumulasi penyusutan","Harga perolehan ditambah penyusutan"],2],
  ["AKT","mc","Laba bersih diperoleh dari...",["Total Penjualan minus Biaya Variabel","Total Pendapatan minus Total Beban","Pendapatan minus Harga Pokok Penjualan","Total Aktiva minus Total Kewajiban"],1],
  ["AKT","mc","Akun yang TIDAK termasuk dalam laporan laba rugi adalah...",["Piutang usaha","Beban gaji","Pendapatan jasa","Beban penyusutan"],0],
  ["AKT","mc","Modal pemilik akan BERTAMBAH apabila...",["Perusahaan rugi","Ada pembayaran utang","Perusahaan mendapat laba","Ada penarikan prive oleh pemilik"],2],
  ["AKT","mc","Metode LIFO dalam persediaan berarti...",["Barang masuk terakhir keluar pertama","Barang mahal dikeluarkan dahulu","Barang masuk pertama keluar pertama","Semua barang dinilai harga rata-rata"],0],
  ["AKT","mc","Siklus akuntansi yang benar adalah...",["Laporan ke Jurnal ke Neraca ke Transaksi","Buku Besar ke Neraca Saldo ke Jurnal ke Laporan","Neraca ke Jurnal ke Buku Besar ke Laporan","Transaksi ke Jurnal ke Buku Besar ke Neraca Saldo ke Laporan Keuangan"],3],
  ["AKT","mc","Prinsip biaya historis (historical cost) menyatakan bahwa aset dicatat sebesar...",["Harga perolehan awal","Nilai penggantian","Nilai likuidasi","Nilai wajar saat ini"],0],
  ["AKT","tf","Debit pada akun aset akan menambah saldo akun tersebut",null,0],
  ["AKT","tf","Neraca disusun untuk menunjukkan posisi keuangan pada satu titik waktu tertentu",null,0],
  ["AKT","tf","Penyusutan diterapkan pada aset tetap berwujud yang dipakai dalam operasional bisnis",null,0],
  ["AKT","tf","Laporan arus kas terdiri dari aktivitas operasi, investasi, dan pendanaan",null,0],
  ["AKT","tf","Akun modal (ekuitas) akan bertambah jika terjadi kerugian perusahaan",null,1],
  ["AKT","tf","Piutang usaha adalah hak perusahaan untuk menerima pembayaran di masa depan",null,0],
  ["AKT","tf","Harga Pokok Penjualan (HPP) adalah bagian dari laporan laba rugi",null,0],
  ["AKT","tf","Jurnal penutup dibuat untuk menutup akun sementara seperti pendapatan dan beban",null,0],

  /* ===== TRIVIA 197 soal ===== */
  ["TRV","mc","Hewan yang memiliki darah biru (mengandung hemosianin) adalah...",["Pinguin","Gurita","Kuda laut","Ikan hiu"],1],
  ["TRV","mc","Simbol olimpiade memiliki berapa lingkaran?",["3","6","5","4"],2],
  ["TRV","mc","Kota terbesar di Australia adalah...",["Canberra","Melbourne","Sydney","Brisbane"],2],
  ["TRV","mc","Siapa yang menemukan penisilin?",["Alexander Fleming","Jonas Salk","Louis Pasteur","Marie Curie"],0],
  ["TRV","mc","Berapa jumlah planet dalam tata surya kita?",["10","9","8","7"],2],
  ["TRV","mc","Dalam olahraga tenis, istilah 'love' berarti skor...",["1","10","15","0"],3],
  ["TRV","mc","Negara mana yang berbentuk seperti sepatu bot di peta?",["Yunani","Portugal","Spanyol","Italia"],3],
  ["TRV","mc","Kata 'tsunami' berasal dari bahasa...",["Korea","Indonesia","Jepang","China"],2],
  ["TRV","mc","Film James Bond pertama adalah...",["Casino Royale","Dr. No","Goldfinger","Thunderball"],1],
  ["TRV","mc","Unsur yang paling keras di alam adalah...",["Wolfram","Berlian (karbon)","Besi","Titanium"],1],
  ["TRV","mc","Negara yang memiliki ibu kota Nairobi adalah...",["Uganda","Tanzania","Ethiopia","Kenya"],3],
  ["TRV","mc","Siapa penulis 'War and Peace'?",["Chekhov","Dostoevsky","Tolstoy","Turgenev"],2],
  ["TRV","mc","Tokoh superhero Spider-Man diciptakan oleh...",["Image Comics","DC Comics","Dark Horse","Marvel Comics"],3],
  ["TRV","mc","Laut yang memiliki kadar garam tertinggi di dunia adalah...",["Laut Kaspia","Laut Mati","Samudra Arktik","Laut Merah"],1],
  ["TRV","mc","Siapa yang pertama kali mendokumentasikan perjalanan ke Amerika sebelum Columbus?",["Leif Eriksson (Viking)","Pedro Alvares Cabral","John Cabot","Amerigo Vespucci"],0],
  ["TRV","mc","Tulang paling kecil dalam tubuh manusia ada di...",["Koklea","Telinga (stapes)","Jari kelingking","Hidung"],1],
  ["TRV","mc","Lukisan jam meleleh 'The Persistence of Memory' adalah karya...",["Claude Monet","Pablo Picasso","Salvador Dali","Vincent van Gogh"],2],
  ["TRV","mc","Hewan yang bisa bertahan di luar angkasa (vakum) sementara adalah...",["Kecoa","Tardigrada (water bear)","Kumbang","Semut"],1],
  ["TRV","mc","Sistem penulisan Mesir kuno disebut...",["Cuneiform","Demotik","Hieroglif","Aksara Linear B"],2],
  ["TRV","mc","Berapakah jumlah hari dalam tahun kabisat?",["364","367","365","366"],3],
  ["TRV","mc","Huruf yang paling sering digunakan dalam bahasa Inggris adalah...",["S","E","A","T"],1],
  ["TRV","mc","Negara yang memiliki lebih banyak danau dari semua negara lain digabung adalah...",["Amerika Serikat","Rusia","Finlandia","Kanada"],3],
  ["TRV","mc","Rempah yang dulu lebih mahal dari emas di Eropa adalah...",["Pala dan cengkeh","Jahe","Kunyit","Kayu manis"],0],
  ["TRV","mc","Jumlah nada dalam skala musik diatonis (do-re-mi-fa-sol-la-si) adalah...",["5","8","12","7"],3],
  ["TRV","mc","Siapa yang menciptakan karakter Sherlock Holmes?",["Edgar Allan Poe","Arthur Conan Doyle","G.K. Chesterton","Agatha Christie"],1],
  ["TRV","mc","Berapa banyak warna dalam bendera pelangi LGBTQ+ yang asli (versi Gilbert Baker)?",["6","8","7","5"],1],
  ["TRV","mc","Negara dengan jumlah pemenang Nobel terbanyak adalah...",["Amerika Serikat","Inggris","Jerman","Perancis"],0],
  ["TRV","mc","Hewan yang memiliki gigi baru sepanjang hidupnya (polyphyodont) adalah...",["Hiu","Anjing","Sapi","Kelinci"],0],
  ["TRV","mc","Ibu kota Peru adalah...",["Lima","Santiago","Bogota","Buenos Aires"],0],
  ["TRV","mc","Dalam bahasa kimia, bawang putih mengandung zat aktif...",["Capsaicin","Curcumin","Allicin","Gingerol"],2],
  ["TRV","mc","Sungai yang mengalir melalui kota Cairo adalah...",["Eufrat","Tigris","Amazon","Nil"],3],
  ["TRV","mc","Berapa jumlah string/senar pada biola standar?",["4","3","5","6"],0],
  ["TRV","mc","Negara mana yang dijuluki 'Land of the Rising Sun'?",["China","Korea","Thailand","Jepang"],3],
  ["TRV","mc","Planet yang paling dekat dengan matahari adalah...",["Merkurius","Bumi","Mars","Venus"],0],
  ["TRV","mc","Penemu telepon adalah...",["Alexander Graham Bell","Thomas Edison","Guglielmo Marconi","Nikola Tesla"],0],
  ["TRV","mc","Makanan khas Jepang yang terbuat dari nasi berbumbu cuka dan berbagai topping adalah...",["Ramen","Sushi","Udon","Tempura"],1],
  ["TRV","mc","Hewan yang dikenal sebagai simbol keberuntungan di China adalah...",["Gajah","Naga","Harimau","Panda"],1],
  ["TRV","mc","Nama planet terdekat kedua dari matahari adalah...",["Merkurius","Venus","Mars","Bumi"],1],
  ["TRV","mc","Kota yang dijuluki 'Kota Singa' atau Lion City adalah...",["Singapura","Hong Kong","Bangkok","Kuala Lumpur"],0],
  ["TRV","mc","Siapa penulis novel '1984' dan 'Animal Farm'?",["George Orwell","Aldous Huxley","H.G. Wells","Ray Bradbury"],0],
  ["TRV","tf","Koala tidur hingga 22 jam sehari",null,0],
  ["TRV","tf","Semua gunung es (iceberg) mengapung dengan 90% massanya di bawah air",null,0],
  ["TRV","tf","Nasi goreng adalah masakan yang berasal dari Italia",null,1],
  ["TRV","tf","Manusia menggunakan hanya 10% dari kapasitas otaknya",null,1],
  ["TRV","tf","The Great Wall of China adalah satu tembok menerus tanpa putus",null,1],
  ["TRV","tf","Dinosaurus punah sekitar 66 juta tahun yang lalu",null,0],
  ["TRV","tf","Bintang yang kita lihat di langit malam mungkin sudah tidak ada lagi",null,0],
  ["TRV","tf","Babi adalah hewan yang paling dekat secara genetik dengan manusia",null,1],
  ["TRV","tf","Semua benua di bumi pernah menyatu menjadi satu daratan yang disebut Pangea",null,0],
  ["TRV","tf","Ikan salmon berenang ke hulu sungai untuk berkembang biak",null,0],
  ["TRV","tf","Robot pertama dalam sejarah dibuat oleh Leonardo da Vinci",null,1],
  ["TRV","tf","Orang yang buta warna tidak bisa melihat warna sama sekali",null,1],
  ["TRV","tf","Tupai menyembunyikan kacang dan sering lupa di mana menyimpannya",null,0],
  ["TRV","tf","Paus berkomunikasi menggunakan nyanyian yang bisa terdengar ratusan kilometer",null,0],
  ["TRV","tf","Seluruh DNA dalam satu sel manusia jika direntangkan panjangnya sekitar 2 meter",null,0],
  ["TRV","tf","Pohon yang tertua di Bumi adalah pohon kelapa sawit",null,1],
  ["TRV","tf","Semut bisa mengangkat beban 50 kali berat tubuhnya",null,0],
  ["TRV","tf","Anjing bisa melihat warna-warna seperti manusia (trichromatic)",null,1],
  ["TRV","tf","Satu tahun cahaya adalah ukuran waktu, bukan jarak",null,1],
  ["TRV","tf","Shakespeare menulis sekitar 37 drama sepanjang hidupnya",null,0],
  ["TRV","tf","Unta menyimpan air di punuknya",null,1],
  ["TRV","tf","Jerapah dan manusia memiliki jumlah tulang leher yang sama (7 ruas)",null,0],
  ["TRV","tf","Pizza Hawaii berasal dari Hawaii, Amerika Serikat",null,1],
  ["TRV","tf","Anggrek Rafflesia arnoldii adalah bunga tunggal terbesar di dunia",null,0],
  ["TRV","tf","Suara petir terdengar setelah kilat karena cahaya lebih cepat dari suara",null,0],
  ["TRV","tf","Komputer pertama di dunia sebesar sebuah kamar",null,0],
  ["TRV","tf","Roald Dahl hanya menulis cerita anak-anak dan tidak pernah menulis cerita dewasa",null,1],
  ["TRV","tf","Kecepatan suara di udara lebih cepat dibanding di air",null,1],
  ["TRV","tf","Bulan memiliki sisi yang tidak pernah menghadap bumi (dark side)",null,0],
  ["TRV","tf","Fingerprint (sidik jari) setiap orang di dunia adalah unik",null,0],
];