export const RAW = [
  /* ===== MATEMATIKA (MTK) 50 soal ===== */
  ["MTK","mc","Berapakah hasil dari 12 + 8?",["18","19","22","20"],3],
  ["MTK","mc","Berapakah hasil dari 35 - 17?",["18","16","17","20"],0],
  ["MTK","mc","Berapakah hasil dari 6 x 7?",["36","42","40","48"],1],
  ["MTK","mc","Berapakah hasil dari 81 : 9?",["8","7","9","10"],2],
  ["MTK","mc","Berapakah hasil dari 15 + 26?",["39","40","42","41"],3],
  ["MTK","mc","Berapakah hasil dari 50 - 23?",["27","26","28","33"],0],
  ["MTK","mc","Berapakah hasil dari 8 x 5?",["35","40","45","48"],1],
  ["MTK","mc","Berapakah hasil dari 72 : 8?",["6","8","9","10"],2],
  ["MTK","mc","Berapakah hasil dari 14 + 19?",["31","32","34","33"],3],
  ["MTK","mc","Berapakah hasil dari 9 x 9?",["81","72","80","90"],0],
  ["MTK","mc","Berapakah 1/2 dari 40?",["10","20","15","25"],1],
  ["MTK","mc","Berapakah 1/4 dari 100?",["20","30","25","40"],2],
  ["MTK","mc","Berapakah 10% dari 200?",["10","30","40","20"],3],
  ["MTK","mc","Berapakah 25% dari 80?",["20","15","25","40"],0],
  ["MTK","mc","Berapakah hasil dari 2/5 + 1/5?",["1/5","3/5","2/10","4/5"],1],
  ["MTK","mc","Berapakah hasil dari 3/4 - 1/4?",["1/4","2/4","1/2","3/4"],2],
  ["MTK","mc","Berapakah hasil dari 0,5 + 0,25?",["0,25","0,5","1,25","0,75"],3],
  ["MTK","mc","Berapakah hasil dari 1,2 + 2,3?",["3,5","3,3","3,4","4,5"],0],
  ["MTK","mc","Jika satu lusin berisi 12 barang, berapa barang dalam 3 lusin?",["24","36","30","42"],1],
  ["MTK","mc","Jika harga 1 buku Rp4.000, berapa harga 5 buku?",["Rp16.000","Rp18.000","Rp20.000","Rp25.000"],2],
  ["MTK","mc","Sebuah persegi memiliki sisi 6 cm. Berapa kelilingnya?",["12 cm","18 cm","36 cm","24 cm"],3],
  ["MTK","mc","Sebuah persegi memiliki sisi 7 cm. Berapa luasnya?",["49 cm2","14 cm2","28 cm2","56 cm2"],0],
  ["MTK","mc","Persegi panjang memiliki panjang 10 cm dan lebar 4 cm. Berapa luasnya?",["14 cm2","40 cm2","20 cm2","80 cm2"],1],
  ["MTK","mc","Segitiga memiliki alas 8 cm dan tinggi 5 cm. Berapa luasnya?",["13 cm2","30 cm2","20 cm2","40 cm2"],2],
  ["MTK","mc","Lingkaran memiliki jari-jari 7 cm. Jika pi = 22/7, berapa kelilingnya?",["22 cm","49 cm","154 cm","44 cm"],3],
  ["MTK","mc","Rata-rata dari 6, 8, dan 10 adalah...",["8","7","9","10"],0],
  ["MTK","mc","Median dari data 3, 5, 7 adalah...",["3","5","6","7"],1],
  ["MTK","mc","Modus dari data 2, 4, 4, 5, 6 adalah...",["2","5","4","6"],2],
  ["MTK","mc","Jika x + 5 = 12, maka x = ...",["5","6","8","7"],3],
  ["MTK","mc","Jika 3x = 21, maka x = ...",["7","6","8","9"],0],
  ["MTK","mc","Jika x - 4 = 9, maka x = ...",["5","13","12","14"],1],
  ["MTK","mc","Bilangan ganjil setelah 17 adalah...",["18","20","19","21"],2],
  ["MTK","mc","Bilangan genap sebelum 30 adalah...",["26","29","32","28"],3],
  ["MTK","mc","Faktor dari 18 adalah...",["6","5","7","8"],0],
  ["MTK","mc","Kelipatan 7 yang lebih dekat ke 30 adalah...",["21","28","27","35"],1],
  ["MTK","tf","Hasil dari 9 + 6 adalah 15",null,0],
  ["MTK","tf","Semua bilangan genap habis dibagi 2",null,0],
  ["MTK","tf","1 kilogram sama dengan 100 gram",null,1],
  ["MTK","tf","Sudut siku-siku besarnya 90 derajat",null,0],
  ["MTK","tf","Segitiga memiliki empat sisi",null,1],
  ["MTK","tf","Bilangan prima hanya memiliki dua faktor, yaitu 1 dan dirinya sendiri",null,0],
  ["MTK","tf","Hasil dari 7 x 8 adalah 54",null,1],
  ["MTK","tf","Pecahan 1/2 sama nilainya dengan 2/4",null,0],
  ["MTK","tf","Luas persegi dihitung dengan sisi x sisi",null,0],
  ["MTK","tf","Angka Romawi X bernilai 5",null,1],
  ["MTK","tf","100 cm sama dengan 1 meter",null,0],
  ["MTK","tf","Bilangan 0 termasuk bilangan ganjil",null,1],
  ["MTK","tf","Dalam satu jam ada 60 menit",null,0],
  ["MTK","tf","Hasil dari 36 : 6 adalah 5",null,1],
  ["MTK","tf","Grafik batang dapat digunakan untuk membandingkan data",null,0],

  /* ===== IPA (IPA) 50 soal ===== */
  ["IPA","mc","Manakah dari organel berikut yang memiliki DNA-nya sendiri di luar nukleus sel hewan?",["Ribosom","Aparatus Golgi","Mitokondria","Lisosom"],2],
  ["IPA","mc","Proses pembelahan sel yang menghasilkan sel anak dengan variasi genetik akibat crossing over adalah...",["Mitosis","Amitosis","Meiosis I","Meiosis II"],2],
  ["IPA","mc","Hormon yang memicu pelepasan sel telur (ovulasi) dari ovarium pada wanita adalah...",["Progesteron","Estrogen","LH (Luteinizing Hormone)","FSH"],2],
  ["IPA","mc","Manakah dari hewan berikut yang bernapas menggunakan paru-paru buku?",["Laba-laba","Cacing tanah","Ikan mas","Belalang"],0],
  ["IPA","mc","Zat warna empedu yang memberi warna kuning pada urine dan feses merupakan hasil perombakan dari...",["Sel darah putih","Hemoglobin sel darah merah","Trombosit","Albumin plasma"],1],
  ["IPA","mc","Dalam klasifikasi makhluk hidup, kelompok tumbuhan lumut (Bryophyta) dibedakan dari paku-pakuan (Pteridophyta) karena lumut tidak memiliki...",["Klorofil","Spora","Berkas pengangkut (xilem dan floem)","Rhizoid"],2],
  ["IPA","mc","Bagian bunga yang berkembang menjadi daging buah pada buah sejati adalah...",["Bakal biji (ovulum)","Bakal buah (ovarium)","Kepala putik","Kelopak bunga"],1],
  ["IPA","mc","Manakah dari penyakit berikut yang disebabkan oleh infeksi bakteri, bukan virus?",["TBC (Tuberkulosis)","Campak","Influenza","Demam berdarah"],0],
  ["IPA","mc","Pada tumbuhan C4, fiksasi karbon pertama kali terjadi di sel mesofil dengan menghasilkan senyawa berkarbon 4, yaitu...",["Asam sitrat","Asam oksaloasetat","Asam fosfogliserat (PGA)","RUDP"],1],
  ["IPA","mc","Dalam ekologi, hubungan antara tanaman anggrek yang menempel pada pohon mangga diklasifikasikan sebagai...",["Mutualisme","Komensalisme","Parasitisme","Predasi"],1],
  ["IPA","mc","Bagian lambung sapi (ruminansia) yang dianggap homolog dengan lambung manusia karena menyekresikan asam lambung dan enzim pencernaan adalah...",["Rumen","Retikulum","Omasum","Abomasum"],3],
  ["IPA","mc","Pembuluh darah yang membawa darah kaya oksigen dari paru-paru kembali ke serambi kiri jantung adalah...",["Vena kava superior","Arteri pulmonalis","Vena pulmonalis","Aorta"],2],
  ["IPA","mc","Manakah dari asam amino berikut yang dikategorikan sebagai asam amino esensial bagi tubuh manusia?",["Alanin","Asam glutamat","Lisin","Glisin"],2],
  ["IPA","mc","Teknik rekayasa genetika yang digunakan untuk menyalin miliaran salinan segmen DNA tertentu secara cepat di laboratorium adalah...",["PCR (Polymerase Chain Reaction)","Elektroforesis gel","DNA Sekuensing","Kloning terapeutik"],0],
  ["IPA","mc","Zat neurotransmitter yang dilepaskan di celah sinapsis untuk merangsang kontraksi otot lurik adalah...",["Dopamin","Asetilkolin","Serotonin","Adrenalin"],1],
  ["IPA","mc","Hukum Mendel II (Asortasi Bebas) dapat diamati pada persilangan dengan menggunakan...",["Satu sifat beda (monohibrid)","Dua sifat beda (dihibrid) atau lebih","Persilangan balik (backcross)","Persilangan resiprokal"],1],
  ["IPA","mc","Sel darah putih yang berfungsi memproduksi antibodi untuk melawan patogen spesifik adalah...",["Neutrofil","Monosit","Limfosit B","Eosinofil"],2],
  ["IPA","mc","Pada pernapasan dada manusia, inspirasi terjadi ketika otot antartulang rusuk berkontraksi, yang mengakibatkan...",["Tekanan udara paru-paru meningkat","Volume rongga dada membesar dan tekanan udara paru-paru mengecil","Diafragma mendatar","Volume rongga dada mengecil"],1],
  ["IPA","mc","Penyakit autoimun di mana sistem imun merusak lapisan pelindung saraf (selubung mielin) di otak dan sumsum tulang belakang adalah...",["Multiple Sclerosis","Lupus","Rheumatoid Arthritis","Diabetes Tipe 1"],0],
  ["IPA","mc","Manakah dari tumbuhan berikut yang merupakan contoh tumbuhan insektivora (pemakan serangga)?",["Kantong semar","Paku tanduk rusa","Bunga bangkai","Tali putri"],0],
  ["IPA","tf","Pada transkripsi DNA, rantai mRNA disintesis dari arah 3' ke 5'",null,1],
  ["IPA","tf","Semua jenis bakteri memiliki dinding sel yang tersusun dari peptidoglikan",null,1],
  ["IPA","tf","Dalam sistem ekskresi, filtrasi glomerulus menghasilkan urine sekunder",null,1],
  ["IPA","tf","Lichen (lumut kerak) merupakan bentuk simbiosis mutualisme antara alga dan jamur",null,0],
  ["IPA","tf","Hormon insulin disekresikan oleh sel alfa pankreas",null,1],
  ["IPA","tf","Tumbuhan xerofit beradaptasi dengan lingkungan kering melalui daun yang termodifikasi menjadi duri dan kutikula yang tebal",null,0],
  ["IPA","tf","Kromosom seks pria pada lalat buah (Drosophila melanogaster) adalah XY, sama seperti manusia",null,0],
  ["IPA","tf","Siklus Krebs terjadi di dalam stroma kloroplas",null,1],
  ["IPA","tf","Plasmodium yang menyebabkan malaria mengalami fase reproduksi seksual di dalam tubuh manusia",null,1],
  ["IPA","tf","Enzim katalase dalam sel hati berfungsi memecah hidrogen peroksida (H2O2) yang beracun menjadi air dan oksigen",null,0],
  ["IPA","mc","Organ tubuh manusia yang memompa darah adalah...",["jantung","paru-paru","lambung","ginjal"],0],
  ["IPA","mc","Alat pernapasan utama manusia adalah...",["jantung","paru-paru","hati","usus"],1],
  ["IPA","mc","Tumbuhan membuat makanan sendiri melalui proses...",["respirasi","pencernaan","fotosintesis","penguapan"],2],
  ["IPA","mc","Zat hijau daun disebut...",["hemoglobin","melanin","keratin","klorofil"],3],
  ["IPA","mc","Akar pada tumbuhan berfungsi menyerap...",["air dan mineral","cahaya","suara","asap"],0],
  ["IPA","mc","Bagian tumbuhan tempat terjadinya fotosintesis paling banyak adalah...",["akar","daun","batang tua","buah"],1],
  ["IPA","mc","Hewan pemakan tumbuhan disebut...",["karnivora","omnivora","herbivora","insektivora"],2],
  ["IPA","mc","Hewan pemakan daging disebut...",["herbivora","produsen","dekomposer","karnivora"],3],
  ["IPA","mc","Manusia termasuk makhluk hidup yang bernapas dengan...",["paru-paru","insang","trakea luar","kulit saja"],0],
  ["IPA","mc","Bagian darah yang membawa oksigen adalah...",["trombosit","sel darah merah","plasma saja","sel darah putih"],1],
  ["IPA","mc","Planet tempat manusia tinggal adalah...",["Mars","Venus","Bumi","Jupiter"],2],
  ["IPA","mc","Matahari termasuk benda langit berupa...",["planet","satelit","komet","bintang"],3],
  ["IPA","mc","Bulan adalah satelit alami dari...",["Bumi","Matahari","Mars","Venus"],0],
  ["IPA","mc","Penyakit flu sering disebabkan oleh...",["batu","virus","magnet","plastik"],1],
  ["IPA","mc","Vitamin yang banyak terdapat pada buah jeruk adalah...",["vitamin K","vitamin D","vitamin C","vitamin B12"],2],
  ["IPA","tf","Makhluk hidup memerlukan makanan untuk mendapatkan energi",null,0],
  ["IPA","tf","Tumbuhan tidak membutuhkan cahaya matahari untuk fotosintesis",null,1],
  ["IPA","tf","Insang adalah alat pernapasan ikan",null,0],
  ["IPA","tf","Bumi mengelilingi Matahari",null,0],
  ["IPA","tf","Tulang membantu tubuh berdiri tegak dan bergerak",null,0],

  /* ===== IPS (IPS) 50 soal ===== */
  ["IPS","mc","Kebijakan moneter kontraktif yang dilakukan bank sentral dengan menjual surat-surat berharga ke pasar disebut...",["Operasi pasar terbuka","Kebijakan diskonto","Kebijakan rasio cadangan wajib","Kebijakan kredit selektif"],0],
  ["IPS","mc","Manakah dari pasar berikut yang dicirikan dengan banyak penjual tetapi barang yang dijual terdiferensiasi (berbeda corak)?",["Monopoli","Oligopoli","Persaingan sempurna","Persaingan monopolistik"],3],
  ["IPS","mc","Koefisien Gini merupakan indikator yang digunakan untuk mengukur tingkat...",["Kemiskinan absolut","Ketimpangan distribusi pendapatan","Pertumbuhan ekonomi riil","Inflasi sektor riil"],1],
  ["IPS","mc","Inflasi yang disebabkan oleh kenaikan biaya produksi barang secara umum disebut...",["Demand-pull inflation","Cost-push inflation","Hyperinflation","Imported inflation"],1],
  ["IPS","mc","Sistem ekonomi di mana alokasi sumber daya ditentukan sepenuhnya melalui mekanisme pasar bebas tanpa campur tangan pemerintah disebut...",["Sistem ekonomi komando","Sistem ekonomi tradisional","Sistem ekonomi liberal","Sistem ekonomi campuran"],2],
  ["IPS","mc","Dalam neraca pembayaran, jika nilai ekspor barang dan jasa lebih kecil dari nilai impornya, maka negara tersebut mengalami...",["Defisit neraca perdagangan","Surplus neraca modal","Defisit neraca transaksi berjalan saja","Surplus transaksi berjalan"],0],
  ["IPS","mc","Kurva yang menunjukkan kombinasi dua barang yang memberikan tingkat kepuasan yang sama bagi konsumen adalah...",["Kurva indiferen","Kurva batas kemungkinan produksi (PPC)","Kurva Engel","Kurva permintaan"],0],
  ["IPS","mc","Teori keunggulan komparatif dalam perdagangan internasional dikemukakan oleh...",["Adam Smith","David Ricardo","John Maynard Keynes","Karl Marx"],1],
  ["IPS","mc","Lembaga keuangan internasional bentukan PBB yang bertugas membantu stabilitas nilai tukar mata uang dunia dan memberi pinjaman jangka pendek untuk mengatasi defisit neraca pembayaran adalah...",["World Bank","IMF","ADB","WTO"],1],
  ["IPS","mc","Kebijakan menaikkan suku bunga acuan oleh Bank Sentral untuk mengatasi inflasi dikenal sebagai...",["Tight money policy","Easy money policy","Fiscal policy","Trade policy"],0],
  ["IPS","mc","Menurut sosiologi, proses penyebaran unsur-unsur kebudayaan dari satu individu ke individu lain atau dari satu masyarakat ke masyarakat lain disebut...",["Asimilasi","Akulturasi","Difusi","Amalgamasi"],2],
  ["IPS","mc","Bentuk interaksi sosial disosiatif di mana pihak-pihak saling bersaing secara tersembunyi tanpa konflik terbuka disebut...",["Kontravensi","Pertikaian","Persaingan","Akomodasi"],0],
  ["IPS","mc","Sistem stratifikasi sosial tertutup yang membagi masyarakat berdasarkan keturunan dan tidak memungkinkan perpindahan kelas sosial adalah...",["Sistem kelas ekonomi","Sistem kasta","Sistem feodal","Meritokrasi"],1],
  ["IPS","mc","Pemberontakan petani Banten tahun 1888 dipicu oleh penderitaan akibat diterapkannya kebijakan...",["Tanam Paksa (Cultuurstelsel)","Sistem Sewa Tanah (Landrent)","Pintu Terbuka (Liberalisme)","Kerja Rodi"],2],
  ["IPS","mc","Berdasarkan fungsinya, uang kartal yang sah digunakan sehari-hari di Indonesia terdiri dari...",["Uang kertas dan uang logam","Uang giral dan deposito","Cek dan bilyet giro","Emas dan perak"],0],
  ["IPS","mc","Nilai total barang dan jasa yang dihasilkan oleh warga negara suatu negara baik di dalam maupun luar negeri selama satu tahun disebut...",["Produk Domestik Bruto (PDB)","Produk Nasional Bruto (PNB)","Produk Nasional Netto (PNN)","Pendapatan Nasional Disposabel"],1],
  ["IPS","mc","Fungsi pajak sebagai alat untuk mengatur kegiatan ekonomi dan menstabilkan kondisi moneter disebut fungsi...",["Budgetair","Regulerend","Distribusi","Stabilisasi"],1],
  ["IPS","mc","Manakah dari berikut ini yang merupakan contoh pengangguran siklikal (konjungtural)?",["Pekerja bangunan yang menganggur setelah proyek selesai","Pekerja yang di-PHK karena krisis ekonomi global","Pekerja yang keluar untuk mencari pekerjaan dengan gaji lebih tinggi","Pekerja pertanian yang menganggur menunggu musim panen berikutnya"],1],
  ["IPS","mc","Organisasi kerja sama ekonomi negara-negara pengekspor minyak bumi didirikan pada tahun 1960 dan disebut...",["APEC","NAFTA","OPEC","OECD"],2],
  ["IPS","mc","Jika elastisitas harga permintaan suatu barang bernilai Ed > 1, maka permintaan barang tersebut dikategorikan sebagai...",["Inelastis","Elastis","Elastis uniter","Inelastis sempurna"],1],
  ["IPS","tf","Kebijakan fiskal ekspansif dilakukan dengan cara menurunkan belanja negara dan menaikkan tarif pajak",null,1],
  ["IPS","tf","Akulturasi terjadi ketika dua kebudayaan bercampur menghasilkan kebudayaan baru dengan menghilangkan ciri asli masing-masing",null,1],
  ["IPS","tf","Mobilitas sosial vertikal naik terjadi ketika seseorang berpindah ke pekerjaan yang setara posisinya",null,1],
  ["IPS","tf","Lembaga sosial terkecil dalam masyarakat yang berfungsi sebagai agen sosialisasi pertama adalah keluarga",null,0],
  ["IPS","tf","Sensus penduduk de jure mencatat penduduk berdasarkan tempat di mana mereka berada saat sensus dilaksanakan",null,1],
  ["IPS","tf","Barang inferior adalah barang yang permintaannya akan turun ketika pendapatan konsumen naik",null,0],
  ["IPS","tf","Hukum Penawaran menyatakan bahwa jumlah barang yang ditawarkan berbanding lurus dengan tingkat harganya",null,0],
  ["IPS","tf","Negara dengan laju pertumbuhan ekonomi yang tinggi selalu memiliki nilai indeks ketimpangan pendapatan yang rendah",null,1],
  ["IPS","tf","Inflasi ringan (creeping inflation) dikategorikan sebagai inflasi dengan tingkat kenaikan harga di bawah 10% per tahun",null,0],
  ["IPS","tf","Dalam teori sosiologi Karl Marx, pertentangan kelas sosial terjadi antara kelas Borjuis (pemilik modal) dan Proletar (buruh)",null,0],
  ["IPS","mc","Kegiatan membeli barang untuk digunakan disebut...",["produksi","distribusi","ekspor","konsumsi"],3],
  ["IPS","mc","Kegiatan membuat barang disebut...",["produksi","konsumsi","impor","tabungan"],0],
  ["IPS","mc","Kegiatan menyalurkan barang dari produsen ke konsumen disebut...",["produksi","distribusi","konsumsi","investasi"],1],
  ["IPS","mc","Orang yang membeli dan menggunakan barang disebut...",["produsen","distributor","konsumen","eksportir"],2],
  ["IPS","mc","Orang atau pihak yang membuat barang disebut...",["konsumen","pembeli","wisatawan","produsen"],3],
  ["IPS","mc","Uang digunakan sebagai alat...",["tukar","ukur suhu","ukur panjang","penerangan"],0],
  ["IPS","mc","Kegiatan menabung biasanya dilakukan di...",["terminal","bank","pasar ikan","museum"],1],
  ["IPS","mc","Peta digunakan untuk menunjukkan...",["rasa makanan","umur benda","letak tempat","harga barang"],2],
  ["IPS","mc","Arah mata angin utama ada...",["2","6","8","4"],3],
  ["IPS","mc","Contoh kebutuhan pokok adalah...",["makanan","mainan mahal","perhiasan","koleksi langka"],0],
  ["IPS","mc","Kegiatan menjual barang ke luar negeri disebut...",["impor","ekspor","barter lokal","tabungan"],1],
  ["IPS","mc","Kegiatan membeli barang dari luar negeri disebut...",["ekspor","produksi","impor","distribusi lokal"],2],
  ["IPS","mc","Rumah adat, tarian, dan bahasa daerah termasuk bagian dari...",["cuaca","iklim","mineral","budaya"],3],
  ["IPS","mc","Musyawarah dilakukan untuk mencapai...",["mufakat","permusuhan","keributan","kekacauan"],0],
  ["IPS","mc","Lingkungan sosial adalah lingkungan yang berkaitan dengan...",["batuan saja","hubungan antarmanusia","planet","awan"],1],
  ["IPS","tf","Pasar adalah tempat bertemunya penjual dan pembeli",null,0],
  ["IPS","tf","Produsen adalah orang yang memakai barang sampai habis",null,1],
  ["IPS","tf","Gotong royong mencerminkan kerja sama dalam masyarakat",null,0],
  ["IPS","tf","Ekspor berarti membeli barang dari luar negeri",null,1],
  ["IPS","tf","Kebutuhan primer adalah kebutuhan yang penting untuk hidup",null,0],

  /* ===== FISIKA (FIS) 50 soal ===== */
  ["FIS","mc","Alat untuk mengukur suhu adalah...",["Barometer","Higrometer","Termometer","Speedometer"],2],
  ["FIS","mc","Satuan internasional untuk panjang adalah...",["kilogram","detik","ampere","meter"],3],
  ["FIS","mc","Satuan internasional untuk massa adalah...",["kilogram","meter","newton","joule"],0],
  ["FIS","mc","Gaya yang menarik benda ke arah pusat Bumi disebut...",["gaya gesek","gaya gravitasi","gaya magnet","gaya listrik"],1],
  ["FIS","mc","Benda yang dapat ditarik magnet biasanya terbuat dari...",["kayu","plastik","besi","kaca"],2],
  ["FIS","mc","Energi dari makanan di dalam tubuh terutama berubah menjadi energi...",["cahaya saja","bunyi saja","magnet","gerak dan panas"],3],
  ["FIS","mc","Alat untuk mengukur massa benda adalah...",["neraca","mistar","termometer","voltmeter"],0],
  ["FIS","mc","Bunyi dapat terdengar karena adanya...",["warna","getaran","bayangan","rasa"],1],
  ["FIS","mc","Cahaya merambat lurus. Contoh peristiwanya adalah terbentuknya...",["embun","karat","bayangan","arus listrik"],2],
  ["FIS","mc","Perubahan es menjadi air disebut...",["membeku","menguap","mengembun","mencair"],3],
  ["FIS","mc","Perubahan air menjadi uap disebut...",["menguap","mencair","membeku","menyublim"],0],
  ["FIS","mc","Perubahan uap air menjadi titik-titik air disebut...",["menguap","mengembun","mencair","membeku"],1],
  ["FIS","mc","Sumber energi utama bagi Bumi adalah...",["Bulan","angin malam","Matahari","awan"],2],
  ["FIS","mc","Lampu menyala karena energi listrik berubah menjadi energi...",["bunyi saja","kimia saja","gerak saja","cahaya dan panas"],3],
  ["FIS","mc","Satuan gaya dalam SI adalah...",["newton","joule","watt","pascal"],0],
  ["FIS","mc","Satuan energi dalam SI adalah...",["newton","joule","meter","ampere"],1],
  ["FIS","mc","Alat untuk mengukur kuat arus listrik adalah...",["voltmeter","barometer","amperemeter","termometer"],2],
  ["FIS","mc","Alat untuk mengukur tegangan listrik adalah...",["amperemeter","neraca","mistar","voltmeter"],3],
  ["FIS","mc","Benda yang menghantarkan panas dengan baik disebut...",["konduktor","isolator","reflektor","generator"],0],
  ["FIS","mc","Benda yang sulit menghantarkan panas disebut...",["konduktor","isolator","magnet","sumber bunyi"],1],
  ["FIS","mc","Contoh konduktor panas yang baik adalah...",["karet","kayu kering","aluminium","plastik"],2],
  ["FIS","mc","Energi pada benda yang bergerak disebut energi...",["potensial","kimia","nuklir","kinetik"],3],
  ["FIS","mc","Energi pada benda karena posisinya disebut energi...",["potensial","kinetik","bunyi","cahaya"],0],
  ["FIS","mc","Satuan daya dalam SI adalah...",["joule","watt","newton","meter"],1],
  ["FIS","mc","Jika gaya dorong diperbesar, benda lebih mudah...",["menghilang","berubah warna","bergerak","membeku"],2],
  ["FIS","mc","Gaya yang menghambat gerak benda di permukaan disebut...",["gaya gravitasi","gaya magnet","gaya apung","gaya gesek"],3],
  ["FIS","mc","Kompas bekerja dengan memanfaatkan gaya...",["magnet","gesek","pegas","otot"],0],
  ["FIS","mc","Cermin datar menghasilkan bayangan yang bersifat...",["terbalik selalu","tegak","lebih panas","tidak terlihat"],1],
  ["FIS","mc","Benda berwarna gelap lebih banyak menyerap energi...",["bunyi","magnet","panas","listrik statis"],2],
  ["FIS","mc","Semakin panjang tali ayunan sederhana, gerak ayunan biasanya semakin...",["cepat","hilang","terang","lambat"],3],
  ["FIS","mc","Tekanan udara diukur dengan alat...",["barometer","termometer","amperemeter","neraca"],0],
  ["FIS","mc","Semakin besar massa benda, umumnya semakin besar pula...",["warnanya","beratnya","suaranya","baunya"],1],
  ["FIS","mc","Roda pada sepeda membantu memperkecil gaya...",["gravitasi","listrik","gesek","magnet"],2],
  ["FIS","mc","Energi tidak dapat diciptakan atau dimusnahkan, hanya dapat...",["dihilangkan","dilipat","dibekukan","diubah bentuknya"],3],
  ["FIS","mc","Gelombang bunyi membutuhkan medium untuk...",["merambat","berwarna","mencair","memantul saja"],0],
  ["FIS","tf","Cahaya dapat merambat di ruang hampa",null,0],
  ["FIS","tf","Bunyi dapat merambat di ruang hampa tanpa medium",null,1],
  ["FIS","tf","Magnet memiliki kutub utara dan kutub selatan",null,0],
  ["FIS","tf","Air selalu membeku pada suhu kamar di Indonesia",null,1],
  ["FIS","tf","Gaya dapat mengubah arah gerak benda",null,0],
  ["FIS","tf","Karet termasuk penghantar listrik yang sangat baik",null,1],
  ["FIS","tf","Panas dapat berpindah dari benda bersuhu tinggi ke benda bersuhu rendah",null,0],
  ["FIS","tf","Mistar biasa digunakan untuk mengukur panjang",null,0],
  ["FIS","tf","Benda diam tidak mungkin bergerak walaupun diberi gaya",null,1],
  ["FIS","tf","Panel surya mengubah energi cahaya menjadi energi listrik",null,0],
  ["FIS","tf","Semakin licin permukaan, gaya gesek biasanya semakin besar",null,1],
  ["FIS","tf","Bayangan terbentuk karena cahaya terhalang oleh benda",null,0],
  ["FIS","tf","Satuan waktu dalam SI adalah detik",null,0],
  ["FIS","tf","Baterai menyimpan energi kimia yang dapat menjadi energi listrik",null,0],
  ["FIS","tf","Semua benda yang jatuh ke Bumi dipengaruhi gravitasi",null,0],

  /* ===== KIMIA (KIM) 50 soal ===== */
  ["KIM","mc","Rumus kimia air adalah...",["CO2","H2O","O2","NaCl"],1],
  ["KIM","mc","Rumus kimia garam dapur adalah...",["H2O","CO2","NaCl","NH3"],2],
  ["KIM","mc","Simbol kimia oksigen adalah...",["Ox","Og","Om","O"],3],
  ["KIM","mc","Simbol kimia hidrogen adalah...",["H","Hy","Hd","Hg"],0],
  ["KIM","mc","Simbol kimia karbon adalah...",["K","C","Ca","Co"],1],
  ["KIM","mc","Simbol kimia natrium adalah...",["N","Nt","Na","S"],2],
  ["KIM","mc","Simbol kimia besi adalah...",["B","Be","F","Fe"],3],
  ["KIM","mc","Simbol kimia emas adalah...",["Au","Ag","Em","Es"],0],
  ["KIM","mc","Zat dengan pH kurang dari 7 bersifat...",["basa","asam","netral","logam"],1],
  ["KIM","mc","Zat dengan pH lebih dari 7 bersifat...",["asam","netral","basa","gas mulia"],2],
  ["KIM","mc","pH air murni mendekati...",["1","5","14","7"],3],
  ["KIM","mc","Contoh perubahan kimia adalah...",["kayu terbakar","es mencair","air membeku","gula larut"],0],
  ["KIM","mc","Contoh perubahan fisika adalah...",["besi berkarat","es mencair","kertas terbakar","nasi basi"],1],
  ["KIM","mc","Gas yang banyak diperlukan manusia untuk bernapas adalah...",["karbon dioksida","nitrogen saja","oksigen","helium"],2],
  ["KIM","mc","Gas yang dihasilkan manusia saat bernapas keluar adalah...",["oksigen murni","hidrogen","klorin","karbon dioksida"],3],
  ["KIM","mc","Logam yang berwujud cair pada suhu ruang adalah...",["raksa","besi","aluminium","emas"],0],
  ["KIM","mc","Alat keselamatan yang melindungi mata di laboratorium adalah...",["sendok","kacamata pelindung","penggaris","topi biasa"],1],
  ["KIM","mc","Campuran garam dan air disebut...",["unsur","logam","larutan garam","gas mulia"],2],
  ["KIM","mc","Zat tunggal yang tidak dapat diuraikan lagi secara kimia disebut...",["campuran","larutan","koloid","unsur"],3],
  ["KIM","mc","Gabungan dua atau lebih unsur secara kimia disebut...",["senyawa","unsur","campuran kasar","suspensi"],0],
  ["KIM","mc","Partikel terkecil penyusun unsur disebut...",["sel","atom","jaringan","organ"],1],
  ["KIM","mc","Bagian atom yang bermuatan negatif disebut...",["proton","neutron","elektron","inti atom"],2],
  ["KIM","mc","Bagian atom yang bermuatan positif disebut...",["elektron","neutron","molekul","proton"],3],
  ["KIM","mc","Bagian atom yang tidak bermuatan listrik disebut...",["neutron","proton","elektron","ion positif"],0],
  ["KIM","mc","Larutan yang mengubah lakmus biru menjadi merah bersifat...",["basa","asam","netral","garam saja"],1],
  ["KIM","mc","Larutan yang mengubah lakmus merah menjadi biru bersifat...",["asam","netral","basa","logam"],2],
  ["KIM","mc","Besi yang terkena air dan udara dapat mengalami...",["mencair","menyublim","mengembun","karat"],3],
  ["KIM","mc","Nama umum senyawa CO2 adalah...",["karbon dioksida","karbon monoksida","oksigen","nitrogen"],0],
  ["KIM","mc","Nama umum senyawa O2 adalah...",["ozon","oksigen","karbon dioksida","hidrogen"],1],
  ["KIM","mc","Nama umum senyawa NH3 adalah...",["air","garam","amonia","kapur"],2],
  ["KIM","mc","Pemisahan pasir dari air paling mudah dilakukan dengan...",["pembakaran","magnet","pendinginan","penyaringan"],3],
  ["KIM","mc","Pemisahan garam dari air laut dapat dilakukan dengan...",["penguapan","penyaringan biasa","ditumbuk","dimagnetkan"],0],
  ["KIM","mc","Kertas indikator universal digunakan untuk memperkirakan...",["massa benda","pH larutan","panjang meja","suhu ruangan"],1],
  ["KIM","mc","Zat yang mempercepat reaksi kimia tanpa habis bereaksi disebut...",["pelarut","indikator","katalis","endapan"],2],
  ["KIM","mc","Contoh basa yang sering dipakai untuk membersihkan adalah...",["cuka","air jeruk","minuman bersoda","sabun"],3],
  ["KIM","tf","Air tersusun dari hidrogen dan oksigen",null,0],
  ["KIM","tf","NaCl adalah rumus kimia garam dapur",null,0],
  ["KIM","tf","Asam selalu memiliki pH lebih dari 7",null,1],
  ["KIM","tf","Oksigen membantu proses pembakaran",null,0],
  ["KIM","tf","Es mencair termasuk perubahan kimia",null,1],
  ["KIM","tf","Atom tersusun dari proton, neutron, dan elektron",null,0],
  ["KIM","tf","Elektron bermuatan positif",null,1],
  ["KIM","tf","Campuran masih dapat dipisahkan secara fisika",null,0],
  ["KIM","tf","Besi berkarat termasuk perubahan kimia",null,0],
  ["KIM","tf","Air murni biasanya bersifat netral",null,0],
  ["KIM","tf","Larutan gula dalam air adalah contoh campuran",null,0],
  ["KIM","tf","Semua zat kimia di laboratorium boleh dicicipi untuk dikenali",null,1],
  ["KIM","tf","Kacamata pelindung membantu menjaga keselamatan mata di laboratorium",null,0],
  ["KIM","tf","Karbon dioksida biasa ditulis CO2",null,0],
  ["KIM","tf","Unsur dan senyawa adalah hal yang sama persis",null,1],

  /* ===== GEOGRAFI (GEO) 45 soal ===== */
  ["GEO","mc","Garis khayal yang menghubungkan titik-titik dengan tekanan udara yang sama pada peta cuaca disebut...",["Isoterm","Isobar","Isohiet","Isobat"],1],
  ["GEO","mc","Jenis batuan sedimen klastik yang terbentuk dari kerikil bulat yang terakumulasi dan tersemenkan adalah...",["Breksi","Konglomerat","Batu pasir","Batu serpih"],1],
  ["GEO","mc","Fenomena sirkulasi angin laut global yang bertiup dari daerah subtropis menuju ekuator disebut angin...",["Barat","Pasat","Fohn","Muson"],1],
  ["GEO","mc","Manakah dari lempeng tektonik berikut yang merupakan lempeng samudra terbesar di dunia?",["Lempeng Nazca","Lempeng Pasifik","Lempeng Eurasia","Lempeng India-Australia"],1],
  ["GEO","mc","Peta berskala 1:100.000 diperkecil menjadi skala 1:500.000. Berapakah luas area peta baru dibandingkan dengan luas area peta awal?",["5 kali lipat","25 kali lipat","1/5 dari awal","1/25 dari awal"],3],
  ["GEO","mc","Tipe letusan gunung api yang dicirikan oleh lava cair encer, tekanan gas rendah, dan pembentukan gunung api perisai adalah...",["Tipe Merapi","Tipe Hawaii","Tipe Stromboli","Tipe Vulkano"],1],
  ["GEO","mc","Lapisan tanah yang kaya akan bahan organik, humus, dan mengalami pencucian (eluviasi) mineral tertinggi disebut horizon...",["Horizon A","Horizon O","Horizon B","Horizon C"],0],
  ["GEO","mc","Proses penguapan air yang terjadi langsung dari tubuh air dan ditambah penguapan dari stomata tumbuhan disebut...",["Kondensasi","Evapotranspirasi","Infiltrasi","Presipitasi"],1],
  ["GEO","mc","Wilayah di dasar laut berupa lereng curam yang membatasi landas kontinen dengan laut dalam disebut...",["Abyssal plain","Continental slope (lereng benua)","Trench (palung)","Continental rise"],1],
  ["GEO","mc","Negara manakah di kawasan Amerika Selatan yang memiliki wilayah paling panjang dan sempit di antara Pegunungan Andes dan Samudra Pasifik?",["Argentina","Peru","Chili","Kolombia"],2],
  ["GEO","mc","Fenomena pemanasan suhu permukaan laut di bagian timur Samudra Pasifik ekuatorial yang berdampak pada kekeringan di Indonesia disebut...",["La Nina","El Nino","Dipole Mode","Tornado"],1],
  ["GEO","mc","Proyeksi peta yang paling cocok digunakan untuk menggambarkan wilayah lintang tinggi atau kutub adalah proyeksi...",["Silinder (Mercator)","Kerucut (Conic)","Azimut (Zenithal)","Transversal"],2],
  ["GEO","mc","Manakah dari sungai berikut yang mengalir ke arah utara dan bermuara di Laut Mediterania?",["Sungai Amazon","Sungai Nil","Sungai Kongo","Sungai Yangtze"],1],
  ["GEO","mc","Tipe iklim menurut Koppen yang dicirikan oleh iklim tropis basah dengan musim kemarau yang jelas (sabana) disimbolkan dengan...",["Af","Am","Aw","BS"],2],
  ["GEO","mc","Patahan di mana satu blok batuan bergeser secara horizontal terhadap blok lainnya akibat gaya geser disebut patahan...",["Normal","Reverse","Strike-slip (mendatar)","Thrust"],2],
  ["GEO","tf","Garis ekuator (khatulistiwa) melewati wilayah kota Pontianak di Indonesia",null,0],
  ["GEO","tf","Palung Mariana, titik terdalam di bumi, terbentuk akibat pertemuan konvergen dua lempeng benua",null,1],
  ["GEO","tf","Batuan sabak (slate) merupakan contoh dari batuan metamorf yang berasal dari batuan sedimen serpih (shale)",null,0],
  ["GEO","tf","Bioma tundra didominasi oleh pohon-pohon berdaun jarum (konifer) seperti pinus",null,1],
  ["GEO","tf","Garis Wallace memisahkan tipe fauna Asiatis dengan fauna Peralihan di Indonesia",null,0],
  ["GEO","tf","Arus laut hangat Teluk (Gulf Stream) mengalir dari Meksiko menuju pantai barat Eropa",null,0],
  ["GEO","tf","Gurun pasir terbesar di dunia berdasarkan luas wilayahnya adalah Gurun Gobi",null,1],
  ["GEO","tf","Garis tanggal internasional (International Date Line) secara kasar mengikuti meridian bujur 180 derajat",null,0],
  ["GEO","tf","Delta sungai biasanya terbentuk di bagian hulu sungai yang memiliki arus air sangat deras",null,1],
  ["GEO","tf","Pemanasan global menyebabkan peningkatan ketebalan lapisan es di kutub utara",null,1],
  ["GEO","mc","Ibu kota Provinsi Jawa Barat adalah...",["Semarang","Surabaya","Bandung","Serang"],2],
  ["GEO","mc","Ibu kota Provinsi Jawa Tengah adalah...",["Bandung","Yogyakarta","Denpasar","Semarang"],3],
  ["GEO","mc","Ibu kota Provinsi Jawa Timur adalah...",["Surabaya","Malang","Madiun","Kediri"],0],
  ["GEO","mc","Pulau terbesar di Indonesia adalah...",["Bali","Kalimantan","Madura","Lombok"],1],
  ["GEO","mc","Gunung tertinggi di Pulau Jawa adalah...",["Merapi","Bromo","Semeru","Tangkuban Perahu"],2],
  ["GEO","mc","Sungai terpanjang di Indonesia adalah...",["Musi","Citarum","Brantas","Kapuas"],3],
  ["GEO","mc","Samudra di sebelah barat Indonesia adalah...",["Samudra Hindia","Samudra Pasifik","Samudra Arktik","Samudra Atlantik"],0],
  ["GEO","mc","Benua terluas di dunia adalah...",["Afrika","Asia","Eropa","Australia"],1],
  ["GEO","mc","Garis khayal yang membagi Bumi menjadi utara dan selatan disebut...",["meridian","bujur","khatulistiwa","orbit"],2],
  ["GEO","mc","Daerah yang lebih tinggi dari sekitarnya dan sangat luas disebut...",["pantai","rawa","selat","dataran tinggi"],3],
  ["GEO","mc","Wilayah perairan sempit yang memisahkan dua pulau disebut...",["selat","teluk","danau","rawa"],0],
  ["GEO","mc","Kumpulan pulau-pulau disebut...",["gurun","kepulauan","savana","delta"],1],
  ["GEO","mc","Awan terbentuk dari proses...",["pembakaran","pengkristalan besi","pengembunan","pelapukan kimia saja"],2],
  ["GEO","mc","Peta yang menggambarkan tinggi rendah permukaan bumi disebut peta...",["politik","cuaca harian","jalan tol saja","topografi"],3],
  ["GEO","mc","Arah matahari terbit adalah...",["timur","barat","utara","selatan"],0],
  ["GEO","tf","Indonesia berada di antara Benua Asia dan Australia",null,0],
  ["GEO","tf","Khatulistiwa melewati wilayah Indonesia",null,0],
  ["GEO","tf","Kutub Utara berada di bagian paling selatan Bumi",null,1],
  ["GEO","tf","Pantai adalah batas antara daratan dan laut",null,0],
  ["GEO","tf","Danau adalah wilayah perairan yang seluruhnya berada di daratan",null,0],

  /* ===== SEJARAH (SEJ) 45 soal ===== */
  ["SEJ","mc","Salah satu keputusan penting dalam sidang pertama PPKI pada 18 Agustus 1945 adalah...",["Membentuk Tentara Keamanan Rakyat","Menetapkan Pancasila sebagai ideologi negara","Mengesahkan UUD 1945","Menetapkan batas wilayah negara Indonesia"],2],
  ["SEJ","mc","Perang Dunia II di Eropa secara resmi berakhir setelah Jerman menandatangani kapitulasi tanpa syarat pada tanggal...",["7-8 Mei 1945","6 Agustus 1945","15 Agustus 1945","2 September 1945"],0],
  ["SEJ","mc","Kerajaan bercorak Hindu tertua di Indonesia yang dibuktikan dengan penemuan prasasti Yupa adalah...",["Tarumanegara","Kutai","Singasari","Majapahit"],1],
  ["SEJ","mc","Siapakah gubernur jenderal VOC pertama yang memindahkan pusat pemerintahan VOC dari Ambon ke Batavia?",["Jan Pieterszoon Coen","Gerard Reynst","Laurens Reael","Pieter Both"],0],
  ["SEJ","mc","Peristiwa penculikan Soekarno dan Hatta oleh para pemuda ke luar kota menjelang proklamasi dikenal sebagai peristiwa...",["Peristiwa Rengasdengklok","Peristiwa Ambarawa","Peristiwa Cikini","Peristiwa 3 Juli 1946"],0],
  ["SEJ","mc","Perjanjian perdamaian yang secara resmi mengakhiri Perang Tiga Puluh Tahun di Eropa pada tahun 1648 adalah...",["Perjanjian Utrecht","Perjanjian Westphalia","Perjanjian Tordesillas","Perjanjian Versailles"],1],
  ["SEJ","mc","Siapakah tokoh yang memimpin revolusi Bolshevik pada tahun 1917 di Rusia?",["Joseph Stalin","Vladimir Lenin","Leon Trotsky","Nikita Khrushchev"],1],
  ["SEJ","mc","Peradaban kuno yang membangun kuil Ziggurat dan menulis menggunakan huruf paku (cuneiform) di wilayah Mesopotamia adalah...",["Mesir Kuno","Persia","Sumeria","Yunani Kuno"],2],
  ["SEJ","mc","Konferensi Meja Bundar (KMB) yang menghasilkan pengakuan kedaulatan Indonesia oleh Belanda diselenggarakan di kota...",["Batavia","Den Haag","Amsterdam","Linggajati"],1],
  ["SEJ","mc","Isi dari Dekret Presiden 5 Juli 1959 yang dikeluarkan oleh Presiden Soekarno adalah...",["Bubarkan PKI","Kembali ke UUD 1945 dan pembubaran Konstituante","Pembentukan Kabinet Ampera","Pelaksanaan Pemilu pertama"],1],
  ["SEJ","mc","Tembok besar Berlin yang memisahkan Berlin Barat dan Berlin Timur didirikan pada tahun...",["1945","1949","1961","1989"],2],
  ["SEJ","mc","Perjanjian Tordesillas tahun 1494 membagi wilayah penjelajahan dunia baru di luar Eropa antara dua negara, yaitu...",["Spanyol dan Portugal","Inggris dan Perancis","Belanda dan Spanyol","Portugal dan Inggris"],0],
  ["SEJ","mc","Siapakah kaisar Perancis yang mengalami kekalahan telak dalam Pertempuran Waterloo pada tahun 1815?",["Louis XIV","Napoleon Bonaparte","Charles de Gaulle","Louis XVI"],1],
  ["SEJ","mc","Perang Diponegoro (1825–1830) yang sangat menguras kas keuangan kolonial Belanda dipicu oleh...",["Belanda menarik pajak tanah yang tinggi","Belanda memasang patok jalan melintasi makam leluhur Pangeran Diponegoro","Belanda menangkap Sentot Alibasyah","Belanda membakar Keraton Yogyakarta"],1],
  ["SEJ","mc","Dinasti kekaisaran terakhir yang memerintah di China sebelum runtuh dan berubah menjadi republik pada tahun 1912 adalah...",["Dinasti Ming","Dinasti Tang","Dinasti Qing","Dinasti Han"],2],
  ["SEJ","tf","Konferensi Asia-Afrika (KAA) pertama kali diselenggarakan di Bandung pada tahun 1955",null,0],
  ["SEJ","tf","Perang Dunia I dipicu oleh pembunuhan terhadap pewaris tahta Austria-Hongaria, Franz Ferdinand, di Sarajevo",null,0],
  ["SEJ","tf","Kerajaan Sriwijaya merupakan kerajaan maritim besar bercorak Islam yang terletak di Sumatera Selatan",null,1],
  ["SEJ","tf","Sumpah Pemuda dibacakan pada Kongres Pemuda I tanggal 28 Oktober 1928",null,1],
  ["SEJ","tf","Piagam Jakarta (Jakarta Charter) dirumuskan oleh Panitia Sembilan pada tanggal 22 Juni 1945",null,0],
  ["SEJ","tf","Revolusi Industri pertama kali dimulai di negara Perancis pada abad ke-18",null,1],
  ["SEJ","tf","Christopher Columbus mendarat pertama kali di benua Amerika pada tahun 1492",null,0],
  ["SEJ","tf","Candi Borobudur yang megah dibangun pada masa pemerintahan Dinasti Sanjaya",null,1],
  ["SEJ","tf","Jepang menyerang pangkalan angkatan laut Amerika Serikat di Pearl Harbor pada 7 Desember 1941",null,0],
  ["SEJ","tf","Perjanjian Bongaya (1667) ditandatangani oleh Sultan Hasanuddin dari Gowa-Tallo setelah kalah perang melawan VOC",null,0],
  ["SEJ","mc","Proklamasi Kemerdekaan Indonesia dibacakan pada tanggal...",["10 November 1945","17 Agustus 1945","1 Juni 1945","28 Oktober 1928"],1],
  ["SEJ","mc","Tokoh yang membacakan Proklamasi Kemerdekaan Indonesia adalah...",["Mohammad Hatta","Sudirman","Soekarno","Ki Hajar Dewantara"],2],
  ["SEJ","mc","Wakil presiden pertama Indonesia adalah...",["Soekarno","Sutan Sjahrir","Tan Malaka","Mohammad Hatta"],3],
  ["SEJ","mc","Hari Pahlawan diperingati setiap tanggal...",["10 November","17 Agustus","1 Juni","21 April"],0],
  ["SEJ","mc","Sumpah Pemuda terjadi pada tahun...",["1908","1928","1945","1950"],1],
  ["SEJ","mc","Organisasi Budi Utomo berdiri pada tahun...",["1928","1945","1908","1955"],2],
  ["SEJ","mc","R.A. Kartini dikenal sebagai tokoh perjuangan...",["kemaritiman","pertanian modern","olahraga","emansipasi wanita"],3],
  ["SEJ","mc","Pancasila diperingati hari lahirnya pada tanggal...",["1 Juni","17 Agustus","10 November","28 Oktober"],0],
  ["SEJ","mc","Kerajaan Majapahit mencapai masa kejayaan pada masa Patih...",["Hayam Wuruk saja","Gajah Mada","Ken Arok","Purnawarman"],1],
  ["SEJ","mc","Candi Borobudur merupakan peninggalan bercorak...",["Islam","Kristen","Buddha","Modern"],2],
  ["SEJ","mc","Candi Prambanan merupakan peninggalan bercorak...",["Buddha","Islam","Kolonial","Hindu"],3],
  ["SEJ","mc","VOC adalah kongsi dagang dari negara...",["Belanda","Portugis","Spanyol","Inggris"],0],
  ["SEJ","mc","Penjajahan Jepang di Indonesia berakhir setelah Jepang kalah dalam...",["Perang Dingin","Perang Dunia II","Perang Teluk","Perang Korea"],1],
  ["SEJ","mc","Naskah Proklamasi diketik oleh...",["Soekarni","Ahmad Soebardjo","Sayuti Melik","Wikana"],2],
  ["SEJ","mc","Tokoh pendidikan Indonesia yang dikenal dengan Taman Siswa adalah...",["R.A. Kartini","Dewi Sartika","Mohammad Yamin","Ki Hajar Dewantara"],3],
  ["SEJ","tf","Indonesia merdeka pada tahun 1945",null,0],
  ["SEJ","tf","Sumpah Pemuda berisi tekad satu tanah air, satu bangsa, dan satu bahasa Indonesia",null,0],
  ["SEJ","tf","VOC berasal dari Jepang",null,1],
  ["SEJ","tf","Borobudur berada di wilayah Jawa Tengah",null,0],
  ["SEJ","tf","Hari Kartini diperingati setiap 21 April",null,0],

  /* ===== NEGARA (NEG) 40 soal ===== */
  ["NEG","mc","Manakah dari negara berikut di kawasan Asia Tenggara yang wilayahnya tidak memiliki akses langsung ke laut (landlocked)?",["Laos","Kamboja","Myanmar","Vietnam"],0],
  ["NEG","mc","Apakah nama ibu kota dari negara Swiss?",["Jenewa","Zurich","Bern","Basel"],2],
  ["NEG","mc","Mata uang resmi yang digunakan oleh negara Afrika Selatan adalah...",["Rand","Shilling","Dinar","Kwacha"],0],
  ["NEG","mc","Manakah dari negara berikut yang memiliki jumlah pulau terbanyak di dunia (melebihi 200.000 pulau)?",["Indonesia","Kanada","Swedia","Filipina"],2],
  ["NEG","mc","Apakah nama ibu kota dari negara Kanada?",["Toronto","Vancouver","Ottawa","Montreal"],2],
  ["NEG","mc","Mata uang resmi dari negara India adalah...",["Taka","Rupee","Rupiah","Kyat"],1],
  ["NEG","mc","Negara manakah yang secara geografis berada sepenuhnya di dalam wilayah negara Italia (enklave)?",["Monako","San Marino","Liechtenstein","Andorra"],1],
  ["NEG","mc","Apakah nama ibu kota dari negara Turki?",["Istanbul","Ankara","Izmir","Bursa"],1],
  ["NEG","mc","Negara manakah yang memiliki wilayah daratan terluas di benua Afrika?",["Sudan","Aljazair","Kongo","Libya"],1],
  ["NEG","mc","Apakah mata uang resmi dari negara Brasil?",["Peso","Real","Cruzeiro","Bolivar"],1],
  ["NEG","mc","Manakah dari negara berikut yang merupakan negara terluas di dunia yang tidak memiliki lautan (landlocked terbesar)?",["Kazakhstan","Mongolia","Bolivia","Chad"],0],
  ["NEG","mc","Apakah nama ibu kota dari negara Australia?",["Sydney","Melbourne","Canberra","Brisbane"],2],
  ["NEG","mc","Negara manakah yang bendera nasionalnya berbentuk persegi dengan palang putih berlatar belakang merah?",["Swiss","Denmark","Inggris","Norwegia"],0],
  ["NEG","mc","Apakah nama ibu kota dari negara Vietnam?",["Ho Chi Minh","Hanoi","Da Nang","Hue"],1],
  ["NEG","mc","Negara manakah yang memiliki garis pantai terpanjang di dunia?",["Kanada","Indonesia","Rusia","Australia"],0],
  ["NEG","tf","Kota Sydney adalah ibu kota dari negara Australia",null,1],
  ["NEG","tf","Negara Brasil menggunakan bahasa Portugis sebagai bahasa resminya",null,0],
  ["NEG","tf","Mata uang resmi negara Turki adalah Lira",null,0],
  ["NEG","tf","Kota New York merupakan ibu kota dari negara Amerika Serikat",null,1],
  ["NEG","tf","Ekuador dinamai berdasarkan letak geografisnya yang dilintasi oleh garis khatulistiwa (ekuator)",null,0],
  ["NEG","tf","Negara Jepang dipimpin oleh seorang presiden sebagai kepala negaranya",null,1],
  ["NEG","tf","Swiss memiliki empat bahasa resmi, yaitu Jerman, Perancis, Italia, dan Romansh",null,0],
  ["NEG","tf","Negara Mesir terletak sepenuhnya di benua Asia",null,1],
  ["NEG","tf","Ibu kota dari negara Selandia Baru (New Zealand) adalah Auckland",null,1],
  ["NEG","tf","Negara Belanda (Netherlands) dikenal karena sebagian besar wilayah daratannya berada di bawah permukaan laut",null,0],
  ["NEG","mc","Ibu kota Indonesia adalah...",["Jakarta","Bandung","Surabaya","Medan"],0],
  ["NEG","mc","Ibu kota Jepang adalah...",["Seoul","Tokyo","Beijing","Bangkok"],1],
  ["NEG","mc","Ibu kota Thailand adalah...",["Hanoi","Manila","Bangkok","Kuala Lumpur"],2],
  ["NEG","mc","Ibu kota Malaysia adalah...",["Singapura","Jakarta","Phnom Penh","Kuala Lumpur"],3],
  ["NEG","mc","Ibu kota Australia adalah...",["Canberra","Sydney","Melbourne","Perth"],0],
  ["NEG","mc","Ibu kota Korea Selatan adalah...",["Tokyo","Seoul","Busan","Pyongyang"],1],
  ["NEG","mc","Ibu kota Vietnam adalah...",["Ho Chi Minh City","Bangkok","Hanoi","Vientiane"],2],
  ["NEG","mc","Negara dengan bendera merah putih seperti Indonesia tetapi susunan warnanya sama persis adalah...",["Jepang","India","Kanada","Monako"],3],
  ["NEG","mc","Negara yang dikenal dengan Menara Eiffel adalah...",["Prancis","Italia","Spanyol","Jerman"],0],
  ["NEG","mc","Negara yang dikenal dengan Piramida Giza adalah...",["Meksiko","Mesir","India","Yunani"],1],
  ["NEG","mc","Negara yang memiliki kota suci Makkah adalah...",["Turki","Mesir","Arab Saudi","Qatar"],2],
  ["NEG","mc","Negara kepulauan di selatan India yang ibu kotanya Sri Jayawardenepura Kotte adalah...",["Maladewa","Nepal","Bangladesh","Sri Lanka"],3],
  ["NEG","tf","Indonesia berada di kawasan Asia Tenggara",null,0],
  ["NEG","tf","Jepang berada di benua Afrika",null,1],
  ["NEG","tf","Canberra adalah ibu kota Australia",null,0],

  /* ===== TRIVIA (TRV) 50 soal ===== */
  ["TRV","mc","Manakah dari organ tubuh manusia berikut yang merupakan organ internal terbesar?",["Otak","Hati","Paru-paru","Usus besar"],1],
  ["TRV","mc","Apakah nama zat kimia alami dalam cabai yang memberikan sensasi rasa pedas?",["Piperin","Kapsaisin","Alisin","Kurkumin"],1],
  ["TRV","mc","Siapakah pencipta kubus Rubik yang merupakan seorang arsitek dari Hungaria?",["Erno Rubik","Laszlo Biro","Janos Neumann","Albert Szent-Gyorgyi"],0],
  ["TRV","mc","Manakah dari jenis hewan berikut yang memiliki golongan darah paling banyak (melebihi 800 golongan darah)?",["Kucing","Anjing","Sapi","Kuda"],2],
  ["TRV","mc","Bahan dasar pembuatan cokelat adalah biji kakao. Di negara manakah biji kakao pertama kali dibudidayakan oleh peradaban kuno?",["Meksiko","Brasil","Pantai Gading","Indonesia"],0],
  ["TRV","mc","Siapakah pelukis terkenal di balik karya mahakarya beraliran surealisme 'The Persistence of Memory' yang menggambarkan jam-jam meleleh?",["Pablo Picasso","Salvador Dali","Vincent van Gogh","Claude Monet"],1],
  ["TRV","mc","Hewan laut manakah yang memiliki tiga jantung, sembilan otak, dan darah berwarna biru?",["Lumba-lumba","Gurita","Hiu putih","Ubur-ubur"],1],
  ["TRV","mc","Apakah nama zat pewarna alami pada wortel yang diubah oleh tubuh menjadi Vitamin A?",["Klorofil","Beta-karoten","Likopen","Antosianin"],1],
  ["TRV","mc","Dalam olahraga catur, berapakah jumlah total petak kotak-kotak hitam dan putih di papan catur?",["36","48","64","81"],2],
  ["TRV","mc","Siapakah penemu penisilin, antibiotik pertama di dunia, secara tidak sengaja pada tahun 1928?",["Louis Pasteur","Alexander Fleming","Jonas Salk","Robert Koch"],1],
  ["TRV","mc","Hewan mamalia manakah yang memiliki masa kehamilan terlama, yaitu sekitar 22 bulan?",["Badak","Gajah","Paus Biru","Jerapah"],1],
  ["TRV","mc","Negara manakah yang memenangkan Piala Dunia FIFA edisi pertama pada tahun 1930?",["Brasil","Uruguay","Argentina","Italia"],1],
  ["TRV","mc","Apakah nama bagian mata manusia yang berfungsi mengatur jumlah cahaya yang masuk dengan cara menyesuaikan ukuran pupil?",["Kornea","Iris","Retina","Lensa"],1],
  ["TRV","mc","Siapakah novelis asal Inggris yang menulis seri misteri detektif terkenal Hercule Poirot dan Miss Marple?",["Arthur Conan Doyle","Agatha Christie","Edgar Allan Poe","Stephen King"],1],
  ["TRV","mc","Manakah dari planet berikut dalam tata surya kita yang memiliki suhu permukaan paling panas?",["Merkurius","Venus","Mars","Jupiter"],1],
  ["TRV","mc","Bahan peledak dinamit diciptakan oleh Alfred Nobel pada abad ke-19. Apakah nama senyawa kimia utama penyusun dinamit?",["Trinitrotoluena (TNT)","Nitrogliserin","Mesiu","Klorat"],1],
  ["TRV","mc","Kota manakah yang dianggap sebagai tempat kelahiran peradaban Renaissance di Italia?",["Roma","Florence","Venesia","Milan"],1],
  ["TRV","mc","Manakah dari bahasa berikut yang memiliki penutur asli (native speakers) terbanyak di dunia?",["Inggris","Mandarin","Spanyol","Hindi"],1],
  ["TRV","mc","Apakah nama samudra terkecil dan terdangkal di dunia?",["Samudra Hindia","Samudra Arktik","Samudra Antartika","Samudra Atlantik"],1],
  ["TRV","mc","Hewan manakah yang dikenal sebagai satu-satunya mamalia bersayap yang dapat terbang secara aktif?",["Kelelawar","Tupai terbang","Burung hantu","Platipus"],0],
  ["TRV","mc","Siapakah fisikawan penemu elektron pada tahun 1897 melalui eksperimen tabung sinar katode?",["Ernest Rutherford","J.J. Thomson","Niels Bohr","James Chadwick"],1],
  ["TRV","mc","Apakah nama selat yang memisahkan benua Asia (Rusia) dan benua Amerika Utara (Alaska)?",["Selat Gibraltar","Selat Bering","Selat Bosporus","Selat Malaka"],1],
  ["TRV","mc","Dalam mitologi Yunani, siapakah dewa penguasa laut dan gempa bumi yang membawa senjata trisula?",["Zeus","Poseidon","Hades","Ares"],1],
  ["TRV","mc","Apakah nama pulau terbesar di dunia yang secara administratif merupakan wilayah otonom dari negara Denmark?",["Madagaskar","Greenland","Kalimantan","Papua"],1],
  ["TRV","mc","Manakah dari hewan berikut yang memiliki sidik jari yang sangat mirip dengan sidik jari manusia sehingga sulit dibedakan di laboratorium?",["Koala","Simpanse","Lumba-lumba","Anjing"],0],
  ["TRV","tf","Kupu-kupu mendeteksi rasa makanan menggunakan reseptor yang terletak di kaki mereka",null,0],
  ["TRV","tf","Pisang secara botani diklasifikasikan sebagai buah beri",null,0],
  ["TRV","tf","Suara merambat lebih cepat di dalam air murni dibandingkan di udara bebas pada suhu kamar",null,0],
  ["TRV","tf","Tembok Besar China dapat dilihat dengan mata telanjang dari bulan",null,1],
  ["TRV","tf","Madu asli tidak dapat membusuk dan dapat bertahan selama ribuan tahun jika disimpan dalam wadah tertutup",null,0],
  ["TRV","tf","Otot terbesar dalam tubuh manusia adalah otot jantung",null,1],
  ["TRV","tf","Unta menyimpan cadangan air mereka di dalam punuknya",null,1],
  ["TRV","tf","Warna merah pada bendera Indonesia melambangkan kesucian, sedangkan putih melambangkan keberanian",null,1],
  ["TRV","tf","Hiu tidak memiliki tulang keras di dalam tubuhnya; seluruh rangkanya tersusun dari tulang rawan",null,0],
  ["TRV","tf","Benua Australia dihuni secara alami oleh hewan penguin",null,0],
  ["TRV","tf","Kucing peliharaan tidak dapat merasakan rasa manis karena kekurangan gen penerima rasa manis",null,0],
  ["TRV","tf","Logam emas murni 24 karat sangat lunak sehingga dapat dibentuk dengan tangan kosong",null,0],
  ["TRV","tf","Petir tidak pernah menyambar tempat yang sama lebih dari sekali",null,1],
  ["TRV","tf","Semua jenis ular bernapas menggunakan paru-paru",null,0],
  ["TRV","tf","Air laut membeku pada suhu yang sama dengan air tawar, yaitu tepat 0 derajat Celsius",null,1],
  ["TRV","tf","Peradaban Romawi Kuno menggunakan sistem kalender Julian sebelum beralih ke kalender Gregorian yang kita gunakan saat ini",null,0],
  ["TRV","tf","Tomat dikategorikan secara ilmiah sebagai sayuran, bukan buah-buahan",null,1],
  ["TRV","tf","Hewan bunglon mengubah warna kulitnya terutama untuk berkamuflase menyatu dengan lingkungan sekitarnya",null,1],
  ["TRV","tf","Bumi adalah satu-satunya objek di tata surya kita yang memiliki bukti adanya air dalam bentuk cair",null,1],
  ["TRV","tf","Jantung manusia berdetak rata-rata lebih dari 100.000 kali dalam satu hari",null,0],
  ["TRV","mc","Warna campuran merah dan kuning adalah...",["hijau","oranye","ungu","biru"],1],
  ["TRV","mc","Alat musik yang dimainkan dengan cara dipetik adalah...",["drum","seruling","gitar","terompet"],2],
  ["TRV","mc","Olahraga yang menggunakan raket dan kok adalah...",["sepak bola","renang","basket","bulu tangkis"],3],
  ["TRV","tf","Hari memiliki 24 jam",null,0],
  ["TRV","tf","Pelangi biasanya memiliki banyak warna",null,0],

  /* ===== ADVANCED (ADV) 40 soal ===== */
  ["ADV","mc","Dalam fisika kuantum, prinsip eksklusi Pauli menyatakan bahwa...",["Tidak ada dua fermion yang dapat menempati keadaan kuantum yang sama secara bersamaan","Energi foton sebanding dengan frekuensinya","Posisi dan momentum partikel tidak dapat diukur secara presisi sekaligus","Fungsi gelombang partikel selalu kontinu"],0],
  ["ADV","mc","Apakah nama teorema dalam teori grup matematika yang menyatakan bahwa untuk setiap grup berhingga G, orde dari setiap subgrup H dari G membagi habis orde dari G?",["Teorema Lagrange","Teorema Euler","Teorema Cayley","Teorema Fermat"],0],
  ["ADV","mc","Manakah dari kelas kompleksitas komputasi berikut yang mendefinisikan masalah yang solusinya dapat diverifikasi dalam waktu polinomial oleh mesin Turing nondeterministik?",["P","NP","PSPACE","EXPTIME"],1],
  ["ADV","mc","Dalam biologi molekuler, kompleks enzim yang bertanggung jawab untuk menyalin DNA menjadi untai RNA selama transkripsi adalah...",["DNA Polimerase","RNA Polimerase","Helikase","Ligase"],1],
  ["ADV","mc","Apakah nama efek dalam fisika di mana terjadi perubahan frekuensi gelombang (seperti bunyi atau cahaya) akibat gerak relatif antara sumber gelombang dan pengamat?",["Efek Compton","Efek Doppler","Efek Faraday","Efek Zeeman"],1],
  ["ADV","mc","Dalam filsafat, argumen ontologis untuk membuktikan keberadaan Tuhan pertama kali dikemukakan oleh...",["Thomas Aquinas","Anselmus dari Canterbury","Rene Descartes","Immanuel Kant"],1],
  ["ADV","mc","Apakah nama hukum termodinamika yang menyatakan bahwa entropi dari suatu kristal sempurna pada suhu nol mutlak adalah nol?",["Hukum Pertama","Hukum Kedua","Hukum Ketiga","Hukum Zeroth"],2],
  ["ADV","mc","Dalam ilmu komputer, algoritma kriptografi RSA didasarkan pada kesulitan matematis dari...",["Logaritma diskrit","Faktorisasi prima bilangan bulat besar","Kriptografi kurva eliptik","Pecahan berlanjut"],1],
  ["ADV","mc","Apakah nama struktur data hierarki di mana setiap simpul memiliki maksimal dua anak dan anak kiri selalu lebih kecil dari induknya, sedangkan anak kanan lebih besar?",["Heap","AVL Tree","Binary Search Tree (Pohon Pencarian Biner)","Red-Black Tree"],2],
  ["ADV","mc","Konsep relativitas umum Einstein memprediksi adanya gelombang gravitasi. Eksperimen pertama yang berhasil mendeteksi gelombang gravitasi secara langsung pada tahun 2015 adalah...",["CERN","LIGO","Hubble","James Webb"],1],
  ["ADV","mc","Dalam kimia organik, reaksi eliminasi Hofmann menghasilkan alkena yang...",["Kurang tersubstitusi (kurang stabil)","Paling banyak tersubstitusi (paling stabil)","Memiliki isomer trans saja","Memiliki cincin benzena"],0],
  ["ADV","mc","Apakah nama paradoks kosmologi yang mempertanyakan mengapa alam semesta tampak sepi dari peradaban luar angkasa maju padahal secara statistik peluangnya tinggi?",["Paradoks Fermi","Paradoks Drake","Paradoks Olbers","Paradoks Hawking"],0],
  ["ADV","mc","Dalam kalkulus multivariabel, teorema yang menghubungkan integral garis pada lintasan tertutup dengan integral lipat dua pada daerah yang dilingkupinya adalah...",["Teorema Green","Teorema Stokes","Teorema Divergensi Gauss","Teorema Nilai Rata-rata"],0],
  ["ADV","mc","Apakah nama partikel elementer pembawa gaya nuklir kuat yang mengikat kuark bersama-sama di dalam proton dan neutron?",["Foton","Gluon","Boson W/Z","Graviton"],1],
  ["ADV","mc","Konsep 'Heisenberg Uncertainty Principle' menyatakan ketidakpastian posisi (delta x) dan momentum (delta p) memiliki batas minimum yang sebanding dengan...",["Konstanta gravitasi G","Konstanta Planck tereduksi (hbar)","Kecepatan cahaya c","Konstanta Boltzmann k"],1],
  ["ADV","tf","Persamaan Schrödinger merupakan persamaan diferensial linier parsial yang mendeskripsikan bagaimana keadaan kuantum sistem fisik berubah terhadap waktu",null,0],
  ["ADV","tf","Pernyataan P vs NP menanyakan apakah setiap masalah yang solusinya dapat diverifikasi dengan cepat juga dapat diselesaikan dengan cepat",null,0],
  ["ADV","tf","Dalam mekanika kuantum, fenomena Quantum Entanglement memungkinkan transmisi informasi melampaui kecepatan cahaya",null,1],
  ["ADV","tf","Teorema Ketidaklengkapan Gödel membuktikan bahwa dalam sistem formal matematika yang konsisten, terdapat pernyataan yang benar tetapi tidak dapat dibuktikan",null,0],
  ["ADV","tf","Radiasi Hawking menyebabkan lubang hitam kehilangan massa secara perlahan dan akhirnya menguap",null,0],
  ["ADV","tf","DNA mitokondria (mtDNA) diwariskan secara eksklusif dari pihak ayah pada mamalia",null,1],
  ["ADV","tf","Dualitas gelombang-partikel menyatakan bahwa cahaya hanya bertindak sebagai gelombang, sedangkan elektron hanya bertindak sebagai partikel",null,1],
  ["ADV","tf","Entropi dari suatu sistem terisolasi yang tidak berada dalam kesetimbangan akan selalu cenderung berkurang seiring waktu",null,1],
  ["ADV","tf","CRISPR-Cas9 merupakan teknologi pengeditan genom yang diadaptasi dari sistem pertahanan imun alami bakteri terhadap virus",null,0],
  ["ADV","tf","Dalam relativitas khusus, panjang sebuah benda yang diukur oleh pengamat yang bergerak relatif terhadap benda tersebut akan tampak lebih panjang daripada panjang aslinya (proper length)",null,1],
  ["ADV","tf","Teorema Terakhir Fermat berhasil dibuktikan oleh matematikawan Andrew Wiles pada akhir abad ke-20",null,0],
  ["ADV","tf","Enzim mempercepat laju reaksi kimia dengan cara meningkatkan energi aktivasi reaksi tersebut",null,1],
  ["ADV","tf","Dalam kosmologi, materi gelap (dark matter) menyusun bagian terbesar dari total densitas energi alam semesta dibandingkan energi gelap (dark energy)",null,1],
  ["ADV","tf","Teorema Bayes menyatakan peluang kejadian A setelah kejadian B terjadi dapat dihitung jika kita mengetahui peluang B setelah A terjadi",null,0],
  ["ADV","tf","Superkonduktor adalah bahan yang memiliki hambatan listrik tepat nol ketika suhunya diturunkan di bawah suhu kritis tertentu",null,0],
  ["ADV","mc","Dalam komputer, CPU sering disebut sebagai...",["otak komputer","layar komputer","kabel listrik","printer"],0],
  ["ADV","mc","Data yang hanya bernilai 0 atau 1 disebut data...",["desimal","biner","pecahan","huruf vokal"],1],
  ["ADV","mc","Dalam internet, URL digunakan sebagai...",["nama baterai","jenis layar","alamat halaman web","ukuran suara"],2],
  ["ADV","mc","Sandi yang mengubah pesan agar sulit dibaca disebut...",["kompresi suara","pencetakan","penghapusan","enkripsi"],3],
  ["ADV","mc","Dalam biologi, DNA membawa informasi...",["genetik","cuaca","harga","arah angin"],0],
  ["ADV","tf","Algoritma adalah langkah-langkah untuk menyelesaikan masalah",null,0],
  ["ADV","tf","Internet hanya dapat dipakai untuk mengirim suara, bukan data lain",null,1],
  ["ADV","tf","Robot dapat diprogram untuk melakukan tugas tertentu",null,0],
  ["ADV","tf","Password yang kuat sebaiknya mudah ditebak semua orang",null,1],
  ["ADV","tf","Satelit dapat membantu komunikasi jarak jauh",null,0],

  /* ===== AKUNTANSI (AKT) 40 soal ===== */
  ["AKT","mc","Metode penyusutan aset tetap di mana beban penyusutan dihitung berdasarkan persentase tetap dari nilai buku aset disebut...",["Metode garis lurus","Metode saldo menurun ganda","Metode satuan hasil","Metode jumlah angka tahun"],1],
  ["AKT","mc","Manakah dari akun berikut yang dikelompokkan sebagai akun riil (kontinu) yang saldonya dibawa ke periode akuntansi berikutnya?",["Beban Gaji","Pendapatan Jasa","Piutang Usaha","Prive Pemilik"],2],
  ["AKT","mc","Dalam akuntansi persediaan barang dagang, metode yang mengasumsikan barang yang dibeli pertama adalah barang yang dijual pertama disebut...",["LIFO","FIFO","Rata-rata tertimbang","Identifikasi spesifik"],1],
  ["AKT","mc","Laporan keuangan yang menyajikan rincian arus masuk dan arus keluar kas perusahaan selama periode tertentu dikelompokkan dalam tiga aktivitas, yaitu...",["Operasi, Investasi, Pendanaan","Produksi, Pemasaran, Keuangan","Debit, Kredit, Penyesuaian","Aset, Kewajiban, Ekuitas"],0],
  ["AKT","mc","Pembelian peralatan kantor secara kredit dicatat dalam jurnal umum dengan cara...",["Mendebit Peralatan Kantor dan mengkredit Kas","Mendebit Kas dan mengkredit Peralatan Kantor","Mendebit Peralatan Kantor dan mengkredit Utang Usaha","Mendebit Utang Usaha dan mengkredit Peralatan Kantor"],2],
  ["AKT","mc","Manakah dari berikut ini yang merupakan rumus yang tepat untuk menghitung Harga Pokok Penjualan (HPP)?",["Persediaan Awal + Pembelian Bersih - Persediaan Akhir","Persediaan Awal - Pembelian Bersih + Persediaan Akhir","Penjualan Bersih - Laba Kotor","Persediaan Akhir + Pembelian Bersih - Persediaan Awal"],0],
  ["AKT","mc","Akun 'Akumulasi Penyusutan Peralatan' disajikan di dalam Laporan Posisi Keuangan (Neraca) sebagai...",["Akun kewajiban lancar","Akun kontra-aset (pengurang nilai peralatan)","Akun beban di ekuitas","Akun aset lancar"],1],
  ["AKT","mc","Prinsip akuntansi yang mengharuskan pengakuan beban dilakukan pada periode yang sama dengan pendapatan yang terkait dengannya disebut...",["Prinsip Biaya Historis","Prinsip Penandingan (Matching Principle)","Prinsip Pengungkapan Penuh","Prinsip Kelangsungan Usaha"],1],
  ["AKT","mc","Jika pada akhir periode akuntansi terdapat beban gaji yang telah terjadi tetapi belum dibayar sebesar Rp5.000.000, jurnal penyesuaiannya adalah...",["Debit Beban Gaji Rp5.000.000, Kredit Kas Rp5.000.000","Debit Utang Gaji Rp5.000.000, Kredit Beban Gaji Rp5.000.000","Debit Beban Gaji Rp5.000.000, Kredit Utang Gaji Rp5.000.000","Debit Kas Rp5.000.000, Kredit Utang Gaji Rp5.000.000"],2],
  ["AKT","mc","Buku jurnal yang digunakan khusus untuk mencatat transaksi penjualan barang dagang secara kredit adalah...",["Jurnal Penerimaan Kas","Jurnal Penjualan","Jurnal Umum","Jurnal Pengeluaran Kas"],1],
  ["AKT","tf","Dalam persamaan dasar akuntansi, transaksi pengambilan uang untuk keperluan pribadi (prive) akan mengurangi saldo ekuitas pemilik",null,0],
  ["AKT","tf","Akun beban dan pendapatan merupakan akun nominal (sementara) yang harus ditutup pada akhir periode akuntansi",null,0],
  ["AKT","tf","Debit selalu berarti kenaikan saldo akun, sedangkan kredit selalu berarti penurunan saldo akun",null,1],
  ["AKT","tf","Kas kecil (petty cash) dibentuk untuk mendanai pengeluaran operasional perusahaan yang jumlahnya relatif besar",null,1],
  ["AKT","tf","Neraca saldo (trial balance) yang seimbang antara kolom debit dan kredit menjamin bahwa tidak ada kesalahan pencatatan transaksi",null,1],
  ["AKT","tf","Goodwill dikategorikan sebagai aset tidak berwujud di dalam neraca perusahaan",null,0],
  ["AKT","tf","Dalam akuntansi basis akrual, pendapatan diakui hanya saat kas diterima secara tunai dari pelanggan",null,1],
  ["AKT","tf","Laporan Perubahan Ekuitas menyajikan informasi mengenai laba atau rugi bersih dan penambahan/pengurangan modal selama periode tertentu",null,0],
  ["AKT","tf","Utang Obligasi (bonds payable) diklasifikasikan sebagai kewajiban jangka pendek (lancar) dalam neraca",null,1],
  ["AKT","tf","Metode penghapusan piutang langsung mencatat beban kerugian piutang saat suatu piutang dipastikan tidak dapat ditagih tanpa menggunakan akun cadangan",null,0],
  ["AKT","mc","Dalam akuntansi, harta perusahaan disebut...",["aset","beban","utang","modal saja"],0],
  ["AKT","mc","Kewajiban perusahaan kepada pihak lain disebut...",["aset","utang","pendapatan","kas kecil"],1],
  ["AKT","mc","Uang tunai perusahaan dicatat dalam akun...",["utang","beban gaji","kas","persediaan rusak"],2],
  ["AKT","mc","Pendapatan adalah uang atau hak yang diperoleh dari...",["hukuman","kerugian saja","utang bank","kegiatan usaha"],3],
  ["AKT","mc","Beban listrik termasuk akun...",["beban","aset","modal","piutang"],0],
  ["AKT","mc","Pembelian barang dagang secara tunai mengurangi akun...",["utang","kas","modal awal","piutang"],1],
  ["AKT","mc","Pihak yang berutang kepada perusahaan disebut...",["kreditur","auditor","debitur","kasir"],2],
  ["AKT","mc","Pihak yang memberi pinjaman kepada perusahaan disebut...",["debitur","pelanggan tunai","pemilik barang","kreditur"],3],
  ["AKT","mc","Dokumen bukti pembelian atau penjualan disebut...",["faktur","peta","jadwal","kartu anggota"],0],
  ["AKT","mc","Laporan yang menunjukkan laba atau rugi adalah laporan...",["neraca saldo saja","laba rugi","daftar hadir","peta akun"],1],
  ["AKT","mc","Persamaan dasar akuntansi adalah...",["Aset = Beban - Modal","Modal = Beban + Kas","Aset = Utang + Modal","Utang = Pendapatan + Aset"],2],
  ["AKT","mc","Jika menerima uang dari pelanggan, akun kas akan...",["berkurang","hilang","ditutup otomatis","bertambah"],3],
  ["AKT","mc","Jika membayar sewa kantor, perusahaan mencatat...",["beban sewa","pendapatan sewa","utang pajak saja","modal bertambah"],0],
  ["AKT","mc","Barang yang dibeli untuk dijual kembali disebut...",["peralatan pribadi","persediaan","beban listrik","modal akhir"],1],
  ["AKT","mc","Catatan pertama transaksi keuangan disebut...",["peta","nota kosong","jurnal","brosur"],2],
  ["AKT","tf","Aset adalah sumber daya yang dimiliki perusahaan",null,0],
  ["AKT","tf","Utang adalah kewajiban yang harus dibayar",null,0],
  ["AKT","tf","Kas selalu berarti uang tunai atau setara kas",null,0],
  ["AKT","tf","Beban membuat laba bertambah tanpa batas",null,1],
  ["AKT","tf","Pendapatan dapat menambah modal pemilik",null,0],

  /* ===== FILM (FIL) 45 soal ===== */
  ["FIL","mc","Orang yang mengarahkan jalannya pembuatan film disebut...",["sutradara","produser saja","penonton","kritikus"],0],
  ["FIL","mc","Naskah cerita film disebut...",["poster","skenario","trailer","subtitle"],1],
  ["FIL","mc","Cuplikan pendek untuk promosi film disebut...",["kredit","adegan penuh","trailer","dialog utama"],2],
  ["FIL","mc","Teks terjemahan di bagian bawah layar disebut...",["soundtrack","poster","rating","subtitle"],3],
  ["FIL","mc","Musik pengiring dalam film disebut...",["soundtrack","subtitle","properti","kamera"],0],
  ["FIL","mc","Film yang dibuat dengan gambar bergerak hasil animasi disebut film...",["dokumenter","animasi","aksi langsung","bisu saja"],1],
  ["FIL","mc","Film yang berisi rekaman fakta atau peristiwa nyata disebut...",["fantasi","komedi","dokumenter","musikal"],2],
  ["FIL","mc","Genre film yang bertujuan membuat penonton tertawa adalah...",["horor","drama perang","thriller","komedi"],3],
  ["FIL","mc","Genre film yang bertujuan menakut-nakuti penonton adalah...",["horor","romantis","komedi","biografi"],0],
  ["FIL","mc","Film yang banyak menampilkan nyanyian dan tarian disebut...",["dokumenter","musikal","laga","misteri"],1],
  ["FIL","mc","Orang yang berperan di depan kamera disebut...",["editor saja","kameramen saja","aktor atau aktris","penulis kredit"],2],
  ["FIL","mc","Proses memilih pemain untuk sebuah film disebut...",["rendering","mixing","screening","casting"],3],
  ["FIL","mc","Proses menyusun potongan gambar menjadi film utuh disebut...",["editing","akting","casting","promosi"],0],
  ["FIL","mc","Alat utama untuk merekam gambar dalam film adalah...",["mikrofon saja","kamera","lampu meja","speaker"],1],
  ["FIL","mc","Adegan pembuka film biasanya berada di bagian...",["akhir","tengah selalu","awal","kredit akhir saja"],2],
  ["FIL","mc","Daftar nama kru dan pemain yang muncul setelah film selesai disebut...",["trailer","subtitle","poster","credit title"],3],
  ["FIL","mc","Film tanpa suara dialog yang populer pada awal sejarah film disebut film...",["bisu","3D","berwarna","interaktif"],0],
  ["FIL","mc","Film dengan banyak ledakan, kejar-kejaran, atau pertarungan biasanya bergenre...",["dokumenter alam","aksi","komedi romantis","biografi tenang"],1],
  ["FIL","mc","Festival film biasanya digunakan untuk...",["menjual sayur","mengukur suhu","memutar dan menilai film","mencetak uang"],2],
  ["FIL","mc","Tempat umum untuk menonton film di layar besar adalah...",["stasiun","bank","perpustakaan saja","bioskop"],3],
  ["FIL","mc","Cerita lanjutan dari film sebelumnya disebut...",["sekuel","prekuel","trailer","poster"],0],
  ["FIL","mc","Cerita yang terjadi sebelum film utama disebut...",["sekuel","prekuel","remake","teaser"],1],
  ["FIL","mc","Pembuatan ulang film lama dengan versi baru disebut...",["subtitle","kredit","remake","rating"],2],
  ["FIL","mc","Film yang menggabungkan gambar nyata dan efek komputer memakai...",["GPS","ATM","HTML saja","CGI"],3],
  ["FIL","mc","Suara percakapan antar tokoh dalam film disebut...",["dialog","poster","kostum","latar"],0],
  ["FIL","mc","Barang yang digunakan pemain dalam adegan disebut...",["subtitle","properti","rating","trailer"],1],
  ["FIL","mc","Pakaian yang dipakai tokoh dalam film disebut...",["kamera","poster","kostum","soundtrack"],2],
  ["FIL","mc","Tempat atau waktu terjadinya cerita dalam film disebut...",["rating","kredit","filter","latar"],3],
  ["FIL","mc","Tokoh utama dalam cerita disebut...",["protagonis","figuran","penata cahaya","operator suara"],0],
  ["FIL","mc","Tokoh yang biasanya menjadi lawan tokoh utama disebut...",["narator","antagonis","kameo","editor"],1],
  ["FIL","tf","Sutradara bertugas mengarahkan pembuatan film",null,0],
  ["FIL","tf","Trailer biasanya berdurasi lebih panjang daripada film utamanya",null,1],
  ["FIL","tf","Subtitle membantu penonton memahami dialog dalam bahasa lain",null,0],
  ["FIL","tf","Film dokumenter selalu harus berupa cerita fiksi",null,1],
  ["FIL","tf","Aktor dan aktris memerankan tokoh dalam film",null,0],
  ["FIL","tf","Editing dilakukan untuk menyusun dan merapikan hasil rekaman",null,0],
  ["FIL","tf","Bioskop adalah tempat umum untuk menonton film",null,0],
  ["FIL","tf","Soundtrack adalah daftar harga tiket film",null,1],
  ["FIL","tf","Film animasi dapat dibuat dari gambar atau objek yang digerakkan",null,0],
  ["FIL","tf","Credit title biasanya memuat nama orang yang terlibat dalam film",null,0],
  ["FIL","tf","Remake berarti film lama dibuat ulang dalam versi baru",null,0],
  ["FIL","tf","Horor adalah genre yang umumnya dibuat untuk menimbulkan rasa takut",null,0],
  ["FIL","tf","Kostum dalam film tidak pernah memengaruhi tampilan tokoh",null,1],
  ["FIL","tf","CGI dapat digunakan untuk membuat efek visual",null,0],
  ["FIL","tf","Protagonis biasanya adalah tokoh utama dalam cerita",null,0],

  /* ===== HEWAN (HEW) 45 soal ===== */
  ["HEW","mc","Hewan yang menyusui anaknya disebut...",["reptil","amfibi","mamalia","serangga"],2],
  ["HEW","mc","Hewan yang hidup di air dan bernapas dengan insang adalah...",["kucing","ayam","ular","ikan"],3],
  ["HEW","mc","Burung bernapas menggunakan...",["paru-paru","insang","kulit saja","akar"],0],
  ["HEW","mc","Kucing termasuk hewan pemakan...",["batu","daging","plastik","tanah"],1],
  ["HEW","mc","Sapi termasuk hewan pemakan...",["daging saja","besi","tumbuhan","kertas"],2],
  ["HEW","mc","Hewan yang dapat hidup di air dan darat disebut...",["mamalia","burung","ikan tulang","amfibi"],3],
  ["HEW","mc","Contoh hewan amfibi adalah...",["katak","kucing","elang","hiu"],0],
  ["HEW","mc","Hewan melata seperti ular termasuk kelompok...",["mamalia","reptil","burung","serangga"],1],
  ["HEW","mc","Serangga umumnya memiliki kaki sebanyak...",["4","8","6","10"],2],
  ["HEW","mc","Laba-laba memiliki kaki sebanyak...",["4","6","10","8"],3],
  ["HEW","mc","Hewan tercepat di darat yang terkenal adalah...",["cheetah","gajah","kura-kura","badak"],0],
  ["HEW","mc","Hewan darat terbesar saat ini adalah...",["kuda","gajah","harimau","rusa"],1],
  ["HEW","mc","Mamalia laut yang sangat besar adalah...",["ayam","katak","paus","kupu-kupu"],2],
  ["HEW","mc","Kelelawar adalah mamalia yang dapat...",["berfotosintesis","berakar","bertelur batu","terbang aktif"],3],
  ["HEW","mc","Pinguin adalah burung yang pandai...",["berenang","terbang tinggi","memanjat pohon kelapa","menggali logam"],0],
  ["HEW","mc","Hewan yang membuat madu adalah...",["semut","lebah","nyamuk","lalat"],1],
  ["HEW","mc","Ulat akan berubah menjadi...",["ikan","kucing","kupu-kupu","ayam"],2],
  ["HEW","mc","Anak katak disebut...",["anak ayam","larva lalat","pupa","berudu"],3],
  ["HEW","mc","Ayam berkembang biak dengan cara...",["bertelur","melahirkan","membelah diri","bertunas"],0],
  ["HEW","mc","Kucing berkembang biak dengan cara...",["bertelur","melahirkan","bertunas","membelah diri"],1],
  ["HEW","mc","Hewan pemakan segala disebut...",["herbivora","karnivora","omnivora","insektivora"],2],
  ["HEW","mc","Hewan pemakan serangga disebut...",["herbivora","omnivora","granivora","insektivora"],3],
  ["HEW","mc","Paruh burung digunakan terutama untuk...",["mengambil makanan","melihat warna","mendengar","bernapas saja"],0],
  ["HEW","mc","Ikan bergerak di air dengan bantuan...",["sayap kering","sirip","akar","tanduk"],1],
  ["HEW","mc","Burung memiliki tubuh tertutup...",["sisik ikan","rambut akar","bulu","cangkang besi"],2],
  ["HEW","mc","Ular bergerak dengan cara...",["terbang","berenang saja","melompat seperti bola","melata"],3],
  ["HEW","mc","Kura-kura melindungi tubuhnya dengan...",["tempurung","sayap","tanduk panjang","sirip punggung"],0],
  ["HEW","mc","Jerapah dikenal memiliki leher yang...",["sangat pendek","panjang","bercabang","berduri tajam"],1],
  ["HEW","mc","Harimau termasuk hewan...",["herbivora","produsen","karnivora","jamur"],2],
  ["HEW","mc","Kambing termasuk hewan...",["karnivora","pemakan plastik","amfibi","herbivora"],3],
  ["HEW","tf","Mamalia menyusui anaknya",null,0],
  ["HEW","tf","Ikan bernapas dengan insang",null,0],
  ["HEW","tf","Semua burung pasti bisa terbang jauh",null,1],
  ["HEW","tf","Katak mengalami metamorfosis",null,0],
  ["HEW","tf","Serangga memiliki tiga pasang kaki",null,0],
  ["HEW","tf","Kucing termasuk hewan herbivora",null,1],
  ["HEW","tf","Ular termasuk reptil",null,0],
  ["HEW","tf","Kelelawar termasuk mamalia",null,0],
  ["HEW","tf","Paus adalah ikan karena hidup di laut",null,1],
  ["HEW","tf","Ayam berkembang biak dengan bertelur",null,0],
  ["HEW","tf","Lebah dapat menghasilkan madu",null,0],
  ["HEW","tf","Kupu-kupu berasal dari metamorfosis ulat",null,0],
  ["HEW","tf","Gajah termasuk hewan darat berukuran besar",null,0],
  ["HEW","tf","Laba-laba memiliki enam kaki seperti serangga",null,1],
  ["HEW","tf","Kura-kura memiliki tempurung untuk perlindungan",null,0],

];
