export const RAW = [
  /* ===== MATEMATIKA (MTK) 40 soal ===== */
  ["MTK", "mc", "Berapakah hasil dari 15 x 6?", ["70", "80", "90", "100"], 2],
  ["MTK", "mc", "Berapakah nilai x dari persamaan 3x - 7 = 11?", ["4", "5", "6", "7"], 2],
  ["MTK", "mc", "Rumus untuk mencari luas persegi panjang adalah...", ["s x s", "p x l", "2 x (p+l)", "a x t"], 1],
  ["MTK", "mc", "Berapakah nilai dari akar kuadrat 144?", ["11", "12", "13", "14"], 1],
  ["MTK", "mc", "Jika sebuah segitiga memiliki alas 8 cm dan tinggi 5 cm, berapakah luasnya?", ["40 cm²", "20 cm²", "15 cm²", "30 cm²"], 1],
  ["MTK", "mc", "Berapakah hasil dari 25% dari 200?", ["25", "50", "75", "100"], 1],
  ["MTK", "mc", "Berapakah FPB (Faktor Persekutuan Terbesar) dari bilangan 12 dan 18?", ["2", "3", "6", "12"], 2],
  ["MTK", "mc", "Berapakah KPK (Kelipatan Persekutuan Terkecil) dari bilangan 6 dan 8?", ["12", "18", "24", "48"], 2],
  ["MTK", "mc", "Berapakah hasil pembagian dari 120 : 5?", ["20", "22", "24", "26"], 2],
  ["MTK", "mc", "Sebuah kubus memiliki panjang rusuk 4 cm. Berapakah volume kubus tersebut?", ["16 cm³", "32 cm³", "64 cm³", "96 cm³"], 2],
  ["MTK", "mc", "Berapakah hasil dari 2³ + 3²?", ["12", "15", "17", "19"], 2],
  ["MTK", "mc", "Berapakah jumlah sudut dalam sebuah segitiga?", ["90°", "180°", "270°", "360°"], 1],
  ["MTK", "mc", "Berapakah nilai dari 10 - 3 x 2?", ["14", "4", "7", "5"], 1],
  ["MTK", "mc", "Jika harga 5 buku adalah Rp 15.000, berapakah harga 8 buku?", ["Rp 20.000", "Rp 24.000", "Rp 25.000", "Rp 30.000"], 1],
  ["MTK", "mc", "Berapakah hasil dari 3/4 + 1/2?", ["4/6", "5/4", "1/2", "3/8"], 1],
  ["MTK", "mc", "Bentuk desimal dari pecahan 3/5 adalah...", ["0.3", "0.5", "0.6", "0.8"], 2],
  ["MTK", "mc", "Berapakah rata-rata (mean) dari data berikut: 4, 6, 8, 10?", ["6", "7", "8", "9"], 1],
  ["MTK", "mc", "Berapakah hasil dari -15 + 8?", ["-7", "7", "-23", "23"], 0],
  ["MTK", "mc", "Berapakah banyak rusuk pada prisma segitiga?", ["6", "9", "12", "15"], 1],
  ["MTK", "mc", "Berapakah nilai dari 10³?", ["100", "500", "1000", "10000"], 2],
  ["MTK", "tf", "Bilangan prima genap satu-satunya adalah 2", null, 0],
  ["MTK", "tf", "Sudut siku-siku memiliki besar 90 derajat", null, 0],
  ["MTK", "tf", "Bilangan pecahan 1/3 lebih besar daripada 1/2", null, 1],
  ["MTK", "tf", "Hasil dari bilangan apa pun jika dipangkatkan nol adalah satu", null, 0],
  ["MTK", "tf", "Keliling lingkaran dihitung dengan rumus pi dikali jari-jari kuadrat", null, 1],
  ["MTK", "tf", "Segitiga sama sisi memiliki tiga sudut yang masing-masing besarnya 60 derajat", null, 0],
  ["MTK", "tf", "Bilangan 1 merupakan bilangan prima", null, 1],
  ["MTK", "tf", "Hasil pembagian bilangan negatif dengan bilangan negatif adalah negatif", null, 1],
  ["MTK", "tf", "Trapesium adalah bangun datar segiempat", null, 0],
  ["MTK", "tf", "Satu jam sama dengan 3600 detik", null, 0],
  ["MTK", "tf", "Bilangan 9 adalah bilangan prima", null, 1],
  ["MTK", "tf", "Dalam matematika, nilai pi kira-kira adalah 3.14 atau 22/7", null, 0],
  ["MTK", "tf", "Sebuah dadu bersisi enam memiliki peluang 1/6 untuk memunculkan angka 3", null, 0],
  ["MTK", "tf", "Bila x + 5 = 12, maka x adalah 8", null, 1],
  ["MTK", "tf", "Luas segitiga dihitung dengan setengah dikali alas dikali tinggi", null, 0],
  ["MTK", "tf", "Bilangan 15 adalah kelipatan dari 3 dan 5", null, 0],
  ["MTK", "tf", "Sebuah tabung memiliki 3 sisi", null, 0],
  ["MTK", "tf", "Hasil dari 5 + 0 x 10 adalah 50", null, 1],
  ["MTK", "tf", "Nilai mutlak dari -10 adalah 10", null, 0],
  ["MTK", "tf", "Dua garis sejajar tidak akan pernah bertemu jika diperpanjang", null, 0],

  /* ===== KIMIA (KIM) 40 soal ===== */
  ["KIM", "mc", "Lambang unsur kimia untuk zat Oksigen adalah...", ["Ok", "O", "Ox", "Os"], 1],
  ["KIM", "mc", "Rumus kimia dari air murni adalah...", ["CO2", "H2O", "NaCl", "H2SO4"], 1],
  ["KIM", "mc", "Zat yang bersifat asam memiliki derajat keasaman (pH) sebesar...", ["Di atas 7", "Di bawah 7", "Tepat 7", "Tepat 14"], 1],
  ["KIM", "mc", "Garam dapur memiliki nama kimia natrium klorida, dengan rumus...", ["NaK", "HCl", "NaCl", "NaOH"], 2],
  ["KIM", "mc", "Zat kimia yang digunakan untuk membunuh kuman pada air kolam renang adalah...", ["Tawas", "Kaporit (Klorin)", "Garam", "Belerang"], 1],
  ["KIM", "mc", "Manakah di bawah ini yang merupakan contoh perubahan kimia?", ["Es mencair", "Kertas terbakar", "Garam larut dalam air", "Kaca pembuat cermin pecah"], 1],
  ["KIM", "mc", "Gas yang paling banyak terdapat di atmosfer bumi adalah...", ["Oksigen", "Nitrogen", "Karbon Dioksida", "Hidrogen"], 1],
  ["KIM", "mc", "Logam yang berwujud cair pada suhu kamar adalah...", ["Emas", "Tembaga", "Besi", "Raksa (Merkuri)"], 3],
  ["KIM", "mc", "Partikel penyusun atom yang bermuatan negatif disebut...", ["Proton", "Neutron", "Elektron", "Positron"], 2],
  ["KIM", "mc", "Zat yang rasanya pahit dan dapat mengubah warna lakmus merah menjadi biru adalah...", ["Asam", "Basa", "Garam", "Netral"], 1],
  ["KIM", "mc", "Senyawa kimia CO2 dikenal dengan nama...", ["Karbon Monoksida", "Karbon Dioksida", "Karbonat", "Metana"], 1],
  ["KIM", "mc", "Proses pengaratan pada besi dipicu oleh reaksi besi dengan...", ["Oksigen dan air", "Nitrogen", "Karbon dioksida", "Helium"], 0],
  ["KIM", "mc", "Asam lambung yang membantu pencernaan makanan adalah...", ["Asam Asetat", "Asam Sulfat", "Asam Klorida", "Asam Sitrat"], 2],
  ["KIM", "mc", "Unsur kimia dengan lambang Au adalah...", ["Perak", "Emas", "Tembaga", "Aluminium"], 1],
  ["KIM", "mc", "Susu dan santan merupakan contoh campuran dalam bentuk...", ["Larutan", "Koloid", "Suspensi", "Unsur"], 1],
  ["KIM", "mc", "Bagian terkecil dari suatu unsur yang masih memiliki sifat unsur tersebut dinamakan...", ["Molekul", "Atom", "Ion", "Senyawa"], 1],
  ["KIM", "mc", "Alat yang digunakan untuk mengukur derajat keasaman (pH) larutan secara akurat adalah...", ["Termometer", "Barometer", "pH meter", "Altimeter"], 2],
  ["KIM", "mc", "Zat tunggal yang tidak dapat diuraikan lagi menjadi zat yang lebih sederhana melalui reaksi kimia biasa disebut...", ["Unsur", "Senyawa", "Campuran", "Larutan"], 0],
  ["KIM", "mc", "Larutan cuka dapur mengandung zat aktif berupa...", ["Asam klorida", "Asam asetat", "Asam sitrat", "Asam sulfat"], 1],
  ["KIM", "mc", "Zat yang ditambahkan ke dalam makanan untuk memberikan rasa manis buatan adalah...", ["MSG", "Sakarin", "Formalin", "Boraks"], 1],
  ["KIM", "tf", "pH air murni yang netral adalah 7", null, 0],
  ["KIM", "tf", "Minyak dan air dapat bercampur secara merata tanpa bantuan sabun", null, 1],
  ["KIM", "tf", "Proton terletak di dalam inti atom dan bermuatan positif", null, 0],
  ["KIM", "tf", "Karbon monoksida adalah gas yang aman untuk dihirup dalam jumlah banyak", null, 1],
  ["KIM", "tf", "Besi berkarat merupakan contoh dari perubahan fisika", null, 1],
  ["KIM", "tf", "Zat pemutih pakaian biasanya mengandung senyawa klorin", null, 0],
  ["KIM", "tf", "Udara di sekitar kita termasuk zat tunggal", null, 1],
  ["KIM", "tf", "Garam dapur (NaCl) terbentuk dari unsur logam Natrium dan gas Klorin", null, 0],
  ["KIM", "tf", "Asam sulfat (H2SO4) sering digunakan sebagai cairan pengisi aki mobil", null, 0],
  ["KIM", "tf", "Kertas lakmus biru akan berubah menjadi merah jika dicelupkan ke dalam larutan asam", null, 0],
  ["KIM", "tf", "Helium merupakan gas yang mudah terbakar", null, 1],
  ["KIM", "tf", "Perubahan wujud zat dari padat menjadi gas disebut mengkristal", null, 1],
  ["KIM", "tf", "Atom hidrogen adalah atom teringan di alam semesta", null, 0],
  ["KIM", "tf", "Oksigen adalah zat yang mudah terbakar dengan sendirinya", null, 1],
  ["KIM", "tf", "Senyawa NaOH merupakan contoh senyawa basa kuat", null, 0],
  ["KIM", "tf", "Logam tembaga adalah penghantar listrik yang baik", null, 0],
  ["KIM", "tf", "Formalin aman digunakan sebagai bahan pengawet makanan bakso dan mie", null, 1],
  ["KIM", "tf", "Unsur Nitrogen dilambangkan dengan huruf Ni", null, 1],
  ["KIM", "tf", "Molekul air terbentuk dari penggabungan dua atom hidrogen dan satu atom oksigen", null, 0],
  ["KIM", "tf", "Larutan sabun mandi bersifat asam", null, 1],

  /* ===== FISIKA (FIS) 40 soal ===== */
  ["FIS", "mc", "Alat yang digunakan untuk mengukur suhu adalah...", ["Barometer", "Termometer", "Altimeter", "Mikrometer"], 1],
  ["FIS", "mc", "Gaya yang menarik buah apel jatuh ke bawah menuju tanah disebut...", ["Gaya gesek", "Gaya magnet", "Gaya gravitasi", "Gaya pegas"], 2],
  ["FIS", "mc", "Satuan kecepatan dalam Sistem Internasional (SI) adalah...", ["m/s", "km/jam", "cm/detik", "mil/jam"], 0],
  ["FIS", "mc", "Energi yang dimiliki oleh benda karena geraknya disebut...", ["Energi potensial", "Energi kinetik", "Energi kimia", "Energi nuklir"], 1],
  ["FIS", "mc", "Benda yang dapat menghantarkan panas atau listrik dengan baik disebut...", ["Isolator", "Konduktor", "Semikonduktor", "Transistor"], 1],
  ["FIS", "mc", "Perubahan wujud benda dari padat menjadi cair dinamakan...", ["Membeku", "Mencair", "Menguap", "Menyublim"], 1],
  ["FIS", "mc", "Aliran muatan listrik dalam suatu rangkaian tertutup disebut...", ["Tegangan", "Arus listrik", "Daya listrik", "Hambatan"], 1],
  ["FIS", "mc", "Kaca pembesar yang digunakan untuk melihat benda-benda kecil menggunakan lensa...", ["Cembung", "Cekung", "Datar", "Ganda"], 0],
  ["FIS", "mc", "Bunyi pantul yang terdengar kembali setelah bunyi asli selesai diucapkan disebut...", ["Gaung", "Gema", "Nada", "Desah"], 1],
  ["FIS", "mc", "Alat yang digunakan untuk mengukur kuat arus listrik adalah...", ["Voltmeter", "Ohmmeter", "Amperemeter", "Barometer"], 2],
  ["FIS", "mc", "Manakah di bawah ini yang termasuk sumber energi alternatif yang dapat diperbarui?", ["Batubara", "Minyak bumi", "Energi matahari", "Gas alam"], 2],
  ["FIS", "mc", "Bagian mata yang berfungsi memfokuskan cahaya agar jatuh tepat di retina adalah...", ["Pupil", "Iris", "Lensa mata", "Kornea"], 2],
  ["FIS", "mc", "Gaya gesek terjadi jika dua permukaan benda...", ["Saling menjauh", "Saling bersentuhan", "Saling tarik-menarik", "Saling berputar"], 1],
  ["FIS", "mc", "Sinar matahari dapat sampai ke bumi melewati ruang hampa udara dengan cara...", ["Konduksi", "Konveksi", "Radiasi", "Evaporasi"], 2],
  ["FIS", "mc", "Sebuah lampu 10 Watt menyala selama 2 jam. Berapakah energi listrik yang digunakan dalam satuan watt-jam (Wh)?", ["5 Wh", "10 Wh", "20 Wh", "30 Wh"], 2],
  ["FIS", "mc", "Alat pemutus dan penyambung aliran listrik pada rangkaian listrik disebut...", ["Sekering", "Saklar", "Stopkontak", "Fiting"], 1],
  ["FIS", "mc", "Zat padat mempertahankan bentuk dan volumenya karena...", ["Gaya tarik antarpartikel sangat kuat", "Partikel bergerak bebas", "Suhu zat sangat dingin", "Massa zat sangat ringan"], 0],
  ["FIS", "mc", "Warna pelangi terbentuk karena adanya proses... cahaya matahari oleh tetesan air hujan.", ["Pembiasan dan penguraian", "Pemantulan baur", "Penyerapan total", "Pengutuban"], 0],
  ["FIS", "mc", "Alat yang digunakan untuk mendeteksi keberadaan muatan listrik pada suatu benda disebut...", ["Elektroskop", "Mikroskop", "Teleskop", "Periskop"], 0],
  ["FIS", "mc", "Magnet memiliki dua kutub, yaitu kutub...", ["Positif dan negatif", "Utara dan selatan", "Barat dan timur", "Atas dan bawah"], 1],
  ["FIS", "tf", "Bunyi dapat merambat di dalam ruang hampa udara", null, 1],
  ["FIS", "tf", "Gaya gravitasi di bulan lebih kecil daripada di bumi", null, 0],
  ["FIS", "tf", "Isolator adalah bahan yang sulit menghantarkan panas", null, 0],
  ["FIS", "tf", "Kecepatan cahaya lebih cepat daripada kecepatan suara di udara", null, 0],
  ["FIS", "tf", "Suhu nol derajat Celsius sama dengan nol Kelvin", null, 1],
  ["FIS", "tf", "Massa sebuah benda akan berubah jika benda tersebut dibawa ke bulan", null, 1],
  ["FIS", "tf", "Semakin besar luas permukaan bidang tekan, semakin kecil tekanan yang dihasilkan", null, 0],
  ["FIS", "tf", "Pemantulan cahaya pada cermin datar bersifat maya, tegak, dan sama besar", null, 0],
  ["FIS", "tf", "Logam besi tidak dapat ditarik oleh magnet", null, 1],
  ["FIS", "tf", "Arus listrik mengalir dari kutub negatif ke kutub positif dalam baterai secara konvensional", null, 1],
  ["FIS", "tf", "Konveksi adalah perpindahan panas yang disertai perpindahan partikel zat perantaranya", null, 0],
  ["FIS", "tf", "Hukum Archimedes melandasi mengapa kapal selam dapat terapung, melayang, dan tenggelam di air", null, 0],
  ["FIS", "tf", "Kutub magnet yang senama jika didekatkan akan tarik-menarik", null, 1],
  ["FIS", "tf", "Pasang surut air laut dipengaruhi oleh gaya gravitasi bulan dan matahari", null, 0],
  ["FIS", "tf", "Energi tidak dapat diciptakan dan tidak dapat dimusnahkan, melainkan hanya dapat diubah bentuknya", null, 0],
  ["FIS", "tf", "Gaya pegas bekerja pada busur panah yang diregangkan", null, 0],
  ["FIS", "tf", "Lensa cekung bersifat mengumpulkan sinar (konvergen)", null, 1],
  ["FIS", "tf", "Hukum Ohm menyatakan hambatan berbanding lurus dengan arus jika tegangan tetap", null, 1],
  ["FIS", "tf", "Periskop pada kapal selam menggunakan cermin atau prisma untuk melihat permukaan laut", null, 0],
  ["FIS", "tf", "Satuan gaya dalam Sistem Internasional (SI) adalah Joule", null, 1],

  /* ===== IPA 50 soal ===== */
  ["IPA", "mc", "Manakah dari organel berikut yang memiliki DNA-nya sendiri di luar nukleus sel hewan?", ["Ribosom", "Aparatus Golgi", "Mitokondria", "Lisosom"], 2],
  ["IPA", "mc", "Proses pembelahan sel yang menghasilkan sel anak dengan variasi genetik akibat crossing over adalah...", ["Mitosis", "Amitosis", "Meiosis I", "Meiosis II"], 2],
  ["IPA", "mc", "Hormon yang memicu pelepasan sel telur (ovulasi) dari ovarium pada wanita adalah...", ["Progesteron", "Estrogen", "LH (Luteinizing Hormone)", "FSH"], 2],
  ["IPA", "mc", "Manakah dari hewan berikut yang bernapas menggunakan paru-paru buku?", ["Laba-laba", "Cacing tanah", "Ikan mas", "Belalang"], 0],
  ["IPA", "mc", "Zat warna empedu yang memberi warna kuning pada urine dan feses merupakan hasil perombakan dari...", ["Sel darah putih", "Hemoglobin sel darah merah", "Trombosit", "Albumin plasma"], 1],
  ["IPA", "mc", "Lumut lumut (Bryophyta) dibedakan dari paku-pakuan (Pteridophyta) karena lumut tidak memiliki...", ["Klorofil", "Spora", "Berkas pengangkut (xilem dan floem)", "Rhizoid"], 2],
  ["IPA", "mc", "Bagian bunga yang berkembang menjadi daging buah pada buah sejati adalah...", ["Bakal biji (ovulum)", "Bakal buah (ovarium)", "Kepala putik", "Kelopak bunga"], 1],
  ["IPA", "mc", "Manakah dari penyakit berikut yang disebabkan oleh infeksi bakteri, bukan virus?", ["TBC (Tuberkulosis)", "Campak", "Influenza", "Demam berdarah"], 0],
  ["IPA", "mc", "Pada tumbuhan C4, fiksasi karbon pertama kali terjadi di sel mesofil dengan menghasilkan senyawa berkarbon 4, yaitu...", ["Asam sitrat", "Asam oksaloasetat", "Asam fosfogliserat (PGA)", "RUDP"], 1],
  ["IPA", "mc", "Dalam ekologi, hubungan antara tanaman anggrek yang menempel pada pohon mangga diklasifikasikan sebagai...", ["Mutualisme", "Komensalisme", "Parasitisme", "Predasi"], 1],
  ["IPA", "mc", "Bagian lambung sapi yang dianggap homolog dengan lambung manusia karena menyekresikan asam lambung adalah...", ["Rumen", "Retikulum", "Omasum", "Abomasum"], 3],
  ["IPA", "mc", "Pembuluh darah yang membawa darah kaya oksigen dari paru-paru kembali ke serambi kiri jantung adalah...", ["Vena kava superior", "Arteri pulmonalis", "Vena pulmonalis", "Aorta"], 2],
  ["IPA", "mc", "Manakah dari asam amino berikut yang dikategorikan sebagai asam amino esensial bagi tubuh manusia?", ["Alanin", "Asam glutamat", "Lisin", "Glisin"], 2],
  ["IPA", "mc", "Teknik rekayasa genetika yang digunakan untuk menyalin miliaran salinan segmen DNA secara cepat adalah...", ["PCR (Polymerase Chain Reaction)", "Elektroforesis gel", "DNA Sekuensing", "Kloning terapeutik"], 0],
  ["IPA", "mc", "Zat neurotransmitter yang dilepaskan di celah sinapsis untuk merangsang kontraksi otot lurik adalah...", ["Dopamin", "Asetilkolin", "Serotonin", "Adrenalin"], 1],
  ["IPA", "mc", "Hukum Mendel II (Asortasi Bebas) dapat diamati pada persilangan dengan menggunakan...", ["Satu sifat beda (monohibrid)", "Dua sifat beda (dihibrid) atau lebih", "Persilangan balik (backcross)", "Persilangan resiprokal"], 1],
  ["IPA", "mc", "Sel darah putih yang berfungsi memproduksi antibodi untuk melawan patogen spesifik adalah...", ["Neutrofil", "Monosit", "Limfosit B", "Eosinofil"], 2],
  ["IPA", "mc", "Pada pernapasan dada manusia, inspirasi terjadi ketika otot antartulang rusuk berkontraksi, yang mengakibatkan...", ["Tekanan udara paru-paru meningkat", "Volume rongga dada membesar dan tekanan mengecil", "Diafragma mendatar", "Volume rongga dada mengecil"], 1],
  ["IPA", "mc", "Penyakit autoimun di mana sistem imun merusak selubung mielin di otak dan sumsum tulang belakang adalah...", ["Multiple Sclerosis", "Lupus", "Rheumatoid Arthritis", "Diabetes Tipe 1"], 0],
  ["IPA", "mc", "Manakah dari tumbuhan berikut yang merupakan contoh tumbuhan insektivora (pemakan serangga)?", ["Kantong semar", "Paku tanduk rusa", "Bunga bangkai", "Tali putri"], 0],
  ["IPA", "mc", "Zat makanan yang berfungsi sebagai pembangun jaringan tubuh dan pengganti sel-sel yang rusak adalah...", ["Karbohidrat", "Protein", "Lemak", "Vitamin"], 1],
  ["IPA", "mc", "Pencernaan secara kimiawi yang dibantu oleh enzim amilase (ptialin) pertama kali terjadi di...", ["Mulut", "Lambung", "Usus halus", "Kerongkongan"], 0],
  ["IPA", "mc", "Kelompok makhluk hidup berikut yang memiliki dinding sel terbuat dari zat kitin dan tidak berklorofil adalah...", ["Plantae", "Fungi (Jamur)", "Animalia", "Protista"], 1],
  ["IPA", "mc", "Lapisan atmosfer bumi tempat terjadinya fenomena cuaca seperti hujan, angin, dan awan adalah...", ["Troposfer", "Stratosfer", "Mesosfer", "Termosfer"], 0],
  ["IPA", "mc", "Penyakit anemia terjadi karena tubuh kekurangan zat utama penyusun sel darah merah, yaitu...", ["Kalsium", "Zat besi", "Yodium", "Kalium"], 1],
  ["IPA", "tf", "Pada transkripsi DNA, rantai mRNA disintesis dari arah 3' ke 5'", null, 1],
  ["IPA", "tf", "Semua jenis bakteri memiliki dinding sel yang tersusun dari peptidoglikan", null, 1],
  ["IPA", "tf", "Dalam sistem ekskresi, filtrasi glomerulus menghasilkan urine sekunder", null, 1],
  ["IPA", "tf", "Lichen (lumut kerak) merupakan bentuk simbiosis mutualisme antara alga dan jamur", null, 0],
  ["IPA", "tf", "Hormon insulin disekresikan oleh sel alfa pankreas", null, 1],
  ["IPA", "tf", "Tumbuhan xerofit beradaptasi dengan lingkungan kering melalui daun berduri dan kutikula tebal", null, 0],
  ["IPA", "tf", "Kromosom seks pria pada lalat buah (Drosophila melanogaster) adalah XY, sama seperti manusia", null, 0],
  ["IPA", "tf", "Siklus Krebs terjadi di dalam stroma kloroplas", null, 1],
  ["IPA", "tf", "Plasmodium yang menyebabkan malaria mengalami fase reproduksi seksual di dalam tubuh manusia", null, 1],
  ["IPA", "tf", "Enzim katalase dalam sel hati berfungsi memecah hidrogen peroksida (H2O2) menjadi air dan oksigen", null, 0],
  ["IPA", "tf", "Fotosintesis menghasilkan gas karbon dioksida yang dilepaskan ke udara bebas", null, 1],
  ["IPA", "tf", "Eritrosit atau sel darah merah tidak memiliki inti sel pada saat dewasa", null, 0],
  ["IPA", "tf", "Metamorfosis pada belalang diklasifikasikan sebagai metamorfosis tidak sempurna", null, 0],
  ["IPA", "tf", "Pembuluh arteri selalu membawa darah yang miskin oksigen menuju ke jantung", null, 1],
  ["IPA", "tf", "Saraf sensorik berfungsi membawa impuls/rangsang dari reseptor menuju sistem saraf pusat", null, 0],
  ["IPA", "tf", "Kelompok hewan mamalia bertelur (platipus) menyusui anaknya meskipun tidak memiliki puting susu", null, 0],
  ["IPA", "tf", "Ekosistem hutan hujan tropis memiliki tingkat keanekaragaman hayati yang sangat rendah", null, 1],
  ["IPA", "tf", "Bakteri Rhizobium bersimbiosis dengan akar tanaman kacang-kacangan untuk memfiksasi nitrogen bebas", null, 0],
  ["IPA", "tf", "Cairan empedu dihasilkan oleh kantung empedu dan disekresikan oleh lambung", null, 1],
  ["IPA", "tf", "Hewan berdarah dingin (Poikiloterm) memiliki suhu tubuh yang berubah mengikuti suhu lingkungan", null, 0],
  ["IPA", "tf", "Penyerapan sari-sari makanan pada saluran pencernaan manusia terutama terjadi di usus besar", null, 1],
  ["IPA", "tf", "Tanaman putri malu menutup daunnya saat disentuh sebagai bentuk adaptasi seismonasti", null, 0],
  ["IPA", "tf", "Pembelahan mitosis menghasilkan empat sel anak yang identik dengan sel induk", null, 1],
  ["IPA", "tf", "Ginjal manusia menyaring darah untuk mengekskresikan zat sisa metabolisme berupa urea", null, 0],
  ["IPA", "tf", "Semua virus memiliki asam nukleat berupa DNA dan RNA sekaligus di dalam tubuhnya", null, 1],

  /* ===== IPS 50 soal ===== */
  ["IPS", "mc", "Kebijakan moneter kontraktif yang dilakukan bank sentral dengan menjual surat berharga disebut...", ["Operasi pasar terbuka", "Kebijakan diskonto", "Kebijakan rasio cadangan wajib", "Kebijakan kredit selektif"], 0],
  ["IPS", "mc", "Manakah dari pasar berikut yang dicirikan dengan banyak penjual tetapi barang yang dijual terdiferensiasi?", ["Monopoli", "Oligopoli", "Persaingan sempurna", "Persaingan monopolistik"], 3],
  ["IPS", "mc", "Koefisien Gini merupakan indikator yang digunakan untuk mengukur tingkat...", ["Kemiskinan absolut", "Ketimpangan distribusi pendapatan", "Pertumbuhan ekonomi riil", "Inflasi sektor riil"], 1],
  ["IPS", "mc", "Inflasi yang disebabkan oleh kenaikan biaya produksi barang secara umum disebut...", ["Demand-pull inflation", "Cost-push inflation", "Hyperinflation", "Imported inflation"], 1],
  ["IPS", "mc", "Sistem ekonomi di mana alokasi sumber daya ditentukan sepenuhnya melalui mekanisme pasar bebas disebut...", ["Sistem ekonomi komando", "Sistem ekonomi tradisional", "Sistem ekonomi liberal", "Sistem ekonomi campuran"], 2],
  ["IPS", "mc", "Dalam neraca pembayaran, jika nilai ekspor barang dan jasa lebih kecil dari nilai impornya, maka negara tersebut mengalami...", ["Defisit neraca perdagangan", "Surplus neraca modal", "Defisit neraca transaksi berjalan", "Surplus transaksi berjalan"], 0],
  ["IPS", "mc", "Kurva yang menunjukkan kombinasi dua barang yang memberikan tingkat kepuasan yang sama bagi konsumen adalah...", ["Kurva indiferen", "Kurva batas kemungkinan produksi (PPC)", "Kurva Engel", "Kurva permintaan"], 0],
  ["IPS", "mc", "Teori keunggulan komparatif dalam perdagangan internasional dikemukakan oleh...", ["Adam Smith", "David Ricardo", "John Maynard Keynes", "Karl Marx"], 1],
  ["IPS", "mc", "Lembaga keuangan internasional PBB yang bertugas membantu stabilitas nilai tukar dunia adalah...", ["World Bank", "IMF", "ADB", "WTO"], 1],
  ["IPS", "mc", "Kebijakan menaikkan suku bunga acuan oleh Bank Sentral untuk mengatasi inflasi dikenal sebagai...", ["Tight money policy", "Easy money policy", "Fiscal policy", "Trade policy"], 0],
  ["IPS", "mc", "Menurut sosiologi, proses penyebaran unsur-unsur kebudayaan dari satu individu ke individu lain disebut...", ["Asimilasi", "Akulturasi", "Difusi", "Amalgamasi"], 2],
  ["IPS", "mc", "Bentuk interaksi sosial disosiatif di mana pihak-pihak saling bersaing secara tersembunyi disebut...", ["Kontravensi", "Pertikaian", "Persaingan", "Akomodasi"], 0],
  ["IPS", "mc", "Sistem stratifikasi sosial tertutup yang membagi masyarakat berdasarkan keturunan adalah...", ["Sistem kelas ekonomi", "Sistem kasta", "Sistem feodal", "Meritokrasi"], 1],
  ["IPS", "mc", "Pemberontakan petani Banten tahun 1888 dipicu oleh penderitaan akibat diterapkannya kebijakan...", ["Tanam Paksa (Cultuurstelsel)", "Sistem Sewa Tanah (Landrent)", "Pintu Terbuka (Liberalisme)", "Kerja Rodi"], 2],
  ["IPS", "mc", "Berdasarkan fungsinya, uang kartal yang sah digunakan sehari-hari di Indonesia terdiri dari...", ["Uang kertas dan uang logam", "Uang giral dan deposito", "Cek dan bilyet giro", "Emas dan perak"], 0],
  ["IPS", "mc", "Nilai total barang dan jasa yang dihasilkan oleh warga negara suatu negara baik di dalam maupun luar negeri selama satu tahun disebut...", ["Produk Domestik Bruto (PDB)", "Produk Nasional Bruto (PNB)", "Produk Nasional Netto (PNN)", "Pendapatan Nasional Disposabel"], 1],
  ["IPS", "mc", "Fungsi pajak sebagai alat untuk mengatur kegiatan ekonomi dan menstabilkan kondisi moneter disebut fungsi...", ["Budgetair", "Regulerend", "Distribusi", "Stabilisasi"], 1],
  ["IPS", "mc", "Manakah dari berikut ini yang merupakan contoh pengangguran siklikal (konjungtural)?", ["Pekerja bangunan yang menganggur setelah proyek selesai", "Pekerja yang di-PHK karena krisis ekonomi global", "Pekerja yang keluar untuk mencari pekerjaan dengan gaji lebih tinggi", "Pekerja pertanian yang menganggur menunggu musim panen berikutnya"], 1],
  ["IPS", "mc", "Organisasi kerja sama ekonomi negara-negara pengekspor minyak bumi didirikan pada tahun 1960 dan disebut...", ["APEC", "NAFTA", "OPEC", "OECD"], 2],
  ["IPS", "mc", "Jika elastisitas harga permintaan suatu barang bernilai Ed > 1, maka permintaan barang tersebut dikategorikan sebagai...", ["Inelastis", "Elastis", "Elastis uniter", "Inelastis sempurna"], 1],
  ["IPS", "mc", "Proses penyesuaian diri dari unsur-unsur kebudayaan yang saling berbeda sehingga menghasilkan keserasian fungsi disebut...", ["Integrasi sosial", "Konflik sosial", "Revolusi sosial", "Asosiasi sosial"], 0],
  ["IPS", "mc", "Manakah di bawah ini yang merupakan contoh kebutuhan tersier bagi masyarakat umum?", ["Makanan bergizi", "Pakaian dinas kerja", "Perhiasan emas dan mobil mewah", "Rumah tinggal sederhana"], 2],
  ["IPS", "mc", "Kegiatan menyalurkan barang dari produsen ke tangan konsumen dinamakan...", ["Produksi", "Konsumsi", "Distribusi", "Investasi"], 2],
  ["IPS", "mc", "Jumlah barang dan jasa yang ingin dibeli oleh konsumen pada berbagai tingkat harga tertentu dinamakan...", ["Penawaran", "Permintaan", "Pasar", "Harga keseimbangan"], 1],
  ["IPS", "mc", "Lembaga sosial yang mengatur tata cara hubungan antarmanusia dalam pemenuhan kebutuhan hidup sehari-hari disebut...", ["Lembaga politik", "Lembaga ekonomi", "Lembaga keluarga", "Lembaga pendidikan"], 1],
  ["IPS", "tf", "Kebijakan fiskal ekspansif dilakukan dengan cara menurunkan belanja negara dan menaikkan tarif pajak", null, 1],
  ["IPS", "tf", "Akulturasi terjadi ketika dua kebudayaan bercampur menghasilkan kebudayaan baru dengan menghilangkan ciri asli masing-masing", null, 1],
  ["IPS", "tf", "Mobilitas sosial vertikal naik terjadi ketika seseorang berpindah ke pekerjaan yang setara posisinya", null, 1],
  ["IPS", "tf", "Lembaga sosial terkecil dalam masyarakat yang berfungsi sebagai agen sosialisasi pertama adalah keluarga", null, 0],
  ["IPS", "tf", "Sensus penduduk de jure mencatat penduduk berdasarkan tempat di mana mereka berada saat sensus dilaksanakan", null, 1],
  ["IPS", "tf", "Barang inferior adalah barang yang permintaannya akan turun ketika pendapatan konsumen naik", null, 0],
  ["IPS", "tf", "Hukum Penawaran menyatakan bahwa jumlah barang yang ditawarkan berbanding lurus dengan tingkat harganya", null, 0],
  ["IPS", "tf", "Negara dengan laju pertumbuhan ekonomi yang tinggi selalu memiliki nilai indeks ketimpangan pendapatan yang rendah", null, 1],
  ["IPS", "tf", "Inflasi ringan (creeping inflation) dikategorikan sebagai inflasi dengan tingkat kenaikan harga di bawah 10% per tahun", null, 0],
  ["IPS", "tf", "Dalam teori sosiologi Karl Marx, pertentangan kelas sosial terjadi antara kelas Borjuis dan Proletar", null, 0],
  ["IPS", "tf", "Pembagian kerja secara khusus di dalam organisasi birokrasi modern merupakan salah satu konsep sosiologi Max Weber", null, 0],
  ["IPS", "tf", "Tindakan ekonomi rasional didasarkan pada keinginan untuk memperoleh kepuasan maksimal dengan pengorbanan sekecil-kecilnya", null, 0],
  ["IPS", "tf", "Interaksi sosial tetap dapat terjadi meskipun tidak ada kontak sosial dan komunikasi antarpelaku", null, 1],
  ["IPS", "tf", "Uang giral merupakan alat pembayaran sah yang diterbitkan oleh Bank Sentral dalam bentuk uang kertas dan koin", null, 1],
  ["IPS", "tf", "Batas landas kontinen suatu negara diukur sejauh 200 mil laut dari garis pangkal pantai saat pasang surut", null, 1],
  ["IPS", "tf", "Sikap etnosentrisme menganggap kebudayaan kelompok sendiri jauh lebih unggul dibandingkan kebudayaan kelompok lain", null, 0],
  ["IPS", "tf", "Penerimaan devisa negara bersumber utama dari kegiatan impor barang dari negara lain", null, 1],
  ["IPS", "tf", "Koperasi Indonesia berlandaskan atas asas kekeluargaan dan gotong royong sesuai amanat UUD 1945", null, 0],
  ["IPS", "tf", "Dalam sosiologi, norma hukum menduduki tingkatan sanksi yang paling lemah jika dilanggar dibandingkan norma cara (usage)", null, 1],
  ["IPS", "tf", "Sistem ekonomi komando (terpusat) banyak diterapkan pada negara-negara yang menganut paham sosialis/komunis", null, 0],
  ["IPS", "tf", "Pasar oligopoli hanya dikuasai oleh satu penjual tunggal yang menguasai seluruh penawaran pasar", null, 1],
  ["IPS", "tf", "Pendapatan per kapita diperoleh dengan membagi Pendapatan Nasional Bruto dengan jumlah penduduk suatu negara", null, 0],
  ["IPS", "tf", "Asimilasi menghasilkan kebudayaan baru dan menghilangkan unsur-unsur kebudayaan asli", null, 0],
  ["IPS", "tf", "Pajak Bumi dan Bangunan (PBB) dikategorikan sebagai contoh dari jenis pajak tidak langsung", null, 1],
  ["IPS", "tf", "Masalah pokok ekonomi klasik meliputi masalah produksi, distribusi, dan konsumsi barang/jasa", null, 0],

  /* ===== GEOGRAFI (GEO) 45 soal ===== */
  ["GEO", "mc", "Garis khayal yang menghubungkan titik-titik dengan tekanan udara yang sama pada peta cuaca disebut...", ["Isoterm", "Isobar", "Isohiet", "Isobat"], 1],
  ["GEO", "mc", "Jenis batuan sedimen klastik yang terbentuk dari kerikil bulat yang terakumulasi dan tersemenkan adalah...", ["Breksi", "Konglomerat", "Batu pasir", "Batu serpih"], 1],
  ["GEO", "mc", "Fenomena sirkulasi angin laut global yang bertiup dari daerah subtropis menuju ekuator disebut angin...", ["Barat", "Pasat", "Fohn", "Muson"], 1],
  ["GEO", "mc", "Manakah dari lempeng tektonik berikut yang merupakan lempeng samudra terbesar di dunia?", ["Lempeng Nazca", "Lempeng Pasifik", "Lempeng Eurasia", "Lempeng India-Australia"], 1],
  ["GEO", "mc", "Peta berskala 1:100.000 diperkecil menjadi skala 1:500.000. Berapakah luas area peta baru dibandingkan dengan luas area peta awal?", ["5 kali lipat", "25 kali lipat", "1/5 dari awal", "1/25 dari awal"], 3],
  ["GEO", "mc", "Tipe letusan gunung api yang dicirikan oleh lava cair encer dan pembentukan gunung api perisai adalah...", ["Tipe Merapi", "Tipe Hawaii", "Tipe Stromboli", "Tipe Vulkano"], 1],
  ["GEO", "mc", "Lapisan tanah yang kaya akan bahan organik, humus, dan mengalami pencucian mineral tertinggi disebut horizon...", ["Horizon A", "Horizon O", "Horizon B", "Horizon C"], 0],
  ["GEO", "mc", "Proses penguapan air dari tubuh air ditambah penguapan dari stomata tumbuhan disebut...", ["Kondensasi", "Evapotranspirasi", "Infiltrasi", "Presipitasi"], 1],
  ["GEO", "mc", "Wilayah di dasar laut berupa lereng curam yang membatasi landas kontinen dengan laut dalam disebut...", ["Abyssal plain", "Continental slope (lereng benua)", "Trench (palung)", "Continental rise"], 1],
  ["GEO", "mc", "Negara manakah di kawasan Amerika Selatan yang memiliki wilayah paling panjang dan sempit di antara Pegunungan Andes dan Samudra Pasifik?", ["Argentina", "Peru", "Chili", "Kolombia"], 2],
  ["GEO", "mc", "Fenomena pemanasan suhu permukaan laut di Pasifik ekuatorial yang berdampak pada kekeringan di Indonesia disebut...", ["La Nina", "El Nino", "Dipole Mode", "Tornado"], 1],
  ["GEO", "mc", "Proyeksi peta yang paling cocok digunakan untuk menggambarkan wilayah kutub adalah proyeksi...", ["Silinder (Mercator)", "Kerucut (Conic)", "Azimut (Zenithal)", "Transversal"], 2],
  ["GEO", "mc", "Manakah dari sungai berikut yang mengalir ke arah utara dan bermuara di Laut Mediterania?", ["Sungai Amazon", "Sungai Nil", "Sungai Kongo", "Sungai Yangtze"], 1],
  ["GEO", "mc", "Tipe iklim menurut Koppen yang dicirikan oleh iklim tropis sabana disimbolkan dengan...", ["Af", "Am", "Aw", "BS"], 2],
  ["GEO", "mc", "Patahan di mana satu blok batuan bergeser secara horizontal terhadap blok lainnya disebut patahan...", ["Normal", "Reverse", "Strike-slip (mendatar)", "Thrust"], 2],
  ["GEO", "mc", "Danau terdalam di dunia yang terletak di Siberia, Rusia adalah...", ["Danau Baikal", "Danau Kaspia", "Danau Victoria", "Danau Superior"], 0],
  ["GEO", "mc", "Samudra terluas di dunia yang mencakup sepertiga permukaan bumi adalah...", ["Samudra Atlantik", "Samudra Hindia", "Samudra Arktik", "Samudra Pasifik"], 3],
  ["GEO", "mc", "Sungai terpanjang di benua Amerika Selatan yang memiliki debit air terbesar di dunia adalah...", ["Sungai Nil", "Sungai Mississippi", "Sungai Amazon", "Sungai Congo"], 2],
  ["GEO", "mc", "Pegunungan terpanjang di dunia yang membentang di sepanjang pantai barat Amerika Selatan adalah...", ["Pegunungan Himalaya", "Pegunungan Alpen", "Pegunungan Andes", "Pegunungan Rocky"], 2],
  ["GEO", "mc", "Negara kepulauan terbesar di dunia berdasarkan luas wilayah dan jumlah pulaunya adalah...", ["Filipina", "Jepang", "Indonesia", "Maladewa"], 2],
  ["GEO", "tf", "Garis ekuator melewati wilayah kota Pontianak di Indonesia", null, 0],
  ["GEO", "tf", "Palung Mariana, titik terdalam di bumi, terbentuk akibat pertemuan konvergen dua lempeng benua", null, 1],
  ["GEO", "tf", "Batuan sabak merupakan contoh dari batuan metamorf yang berasal dari batuan sedimen serpih", null, 0],
  ["GEO", "tf", "Bioma tundra didominasi oleh pohon-pohon berdaun jarum seperti pinus", null, 1],
  ["GEO", "tf", "Garis Wallace memisahkan tipe fauna Asiatis dengan fauna Peralihan di Indonesia", null, 0],
  ["GEO", "tf", "Arus laut hangat Teluk (Gulf Stream) mengalir dari Meksiko menuju pantai barat Eropa", null, 0],
  ["GEO", "tf", "Gurun pasir terbesar di dunia berdasarkan luas wilayahnya adalah Gurun Gobi", null, 1],
  ["GEO", "tf", "Garis tanggal internasional secara kasar mengikuti meridian bujur 180 derajat", null, 0],
  ["GEO", "tf", "Delta sungai biasanya terbentuk di bagian hulu sungai yang memiliki arus air sangat deras", null, 1],
  ["GEO", "tf", "Pemanasan global menyebabkan peningkatan ketebalan lapisan es di kutub utara", null, 1],
  ["GEO", "tf", "Indonesia beriklim tropis karena secara astronomis terletak di antara 6 derajat LU sampai 11 derajat LS", null, 0],
  ["GEO", "tf", "Erosi angin yang mengikis batuan hingga membentuk batu jamur disebut deflasi", null, 0],
  ["GEO", "tf", "Garis lintang digunakan untuk menentukan perbedaan waktu di berbagai belahan bumi", null, 1],
  ["GEO", "tf", "Stalaktit merupakan endapan kapur yang tumbuh menjulang dari dasar gua ke atas", null, 1],
  ["GEO", "tf", "Siklon tropis adalah badai dengan pusaran angin kencang yang terbentuk di atas samudra hangat dekat ekuator", null, 0],
  ["GEO", "tf", "Benua Australia merupakan benua yang memiliki luas wilayah terkecil di dunia", null, 0],
  ["GEO", "tf", "Lapisan stratosfer merupakan lapisan atmosfer tempat dipantulkannya gelombang radio", null, 1],
  ["GEO", "tf", "Sebagian besar wilayah gurun pasir di bumi terletak di sepanjang garis lintang 20-30 derajat LU/LS", null, 0],
  ["GEO", "tf", "Bencana likuefaksi tanah biasanya dipicu oleh guncangan gempa bumi yang kuat pada tanah berpasir jenuh air", null, 0],
  ["GEO", "tf", "Garis Webber memisahkan wilayah fauna tipe peralihan dengan tipe Australis di Indonesia", null, 0],
  ["GEO", "tf", "Hutan hujan tropis dicirikan oleh kanopi pohon yang rapat dan lantai hutan yang sangat terang", null, 1],
  ["GEO", "tf", "Pegunungan Ural merupakan batas alam yang memisahkan benua Asia dengan benua Eropa", null, 0],
  ["GEO", "tf", "Proses pengikisan pantai oleh hantaman gelombang laut dinamakan abrasi", null, 0],
  ["GEO", "tf", "Wilayah perairan laut dangkal dengan kedalaman kurang dari 200 meter disebut zona batial", null, 1],
  ["GEO", "tf", "Gunung Everest secara geografis terletak di perbatasan antara negara India dan Pakistan", null, 1],

  /* ===== SEJARAH (SEJ) 45 soal ===== */
  ["SEJ", "mc", "Salah satu keputusan penting dalam sidang pertama PPKI pada 18 Agustus 1945 adalah...", ["Membentuk Tentara Keamanan Rakyat", "Menetapkan Pancasila sebagai ideologi negara", "Mengesahkan UUD 1945", "Menetapkan batas wilayah negara Indonesia"], 2],
  ["SEJ", "mc", "Perang Dunia II di Eropa secara resmi berakhir setelah Jerman menandatangani kapitulasi tanpa syarat pada tanggal...", ["7-8 Mei 1945", "6 Agustus 1945", "15 Agustus 1945", "2 September 1945"], 0],
  ["SEJ", "mc", "Kerajaan bercorak Hindu tua di Indonesia yang dibuktikan dengan penemuan prasasti Yupa adalah...", ["Tarumanegara", "Kutai", "Singasari", "Majapahit"], 1],
  ["SEJ", "mc", "Siapakah gubernur jenderal VOC pertama yang memindahkan pusat pemerintahan VOC dari Ambon ke Batavia?", ["Jan Pieterszoon Coen", "Gerard Reynst", "Laurens Reael", "Pieter Both"], 0],
  ["SEJ", "mc", "Peristiwa penculikan Soekarno dan Hatta oleh para pemuda ke luar kota menjelang proklamasi dikenal sebagai...", ["Peristiwa Rengasdengklok", "Peristiwa Ambarawa", "Peristiwa Cikini", "Peristiwa 3 Juli 1946"], 0],
  ["SEJ", "mc", "Perjanjian perdamaian yang secara resmi mengakhiri Perang Tiga Puluh Tahun di Eropa pada tahun 1648 adalah...", ["Perjanjian Utrecht", "Perjanjian Westphalia", "Perjanjian Tordesillas", "Perjanjian Versailles"], 1],
  ["SEJ", "mc", "Siapakah tokoh yang memimpin revolusi Bolshevik pada tahun 1917 di Rusia?", ["Joseph Stalin", "Vladimir Lenin", "Leon Trotsky", "Nikita Khrushchev"], 1],
  ["SEJ", "mc", "Peradaban kuno yang membangun kuil Ziggurat dan menulis menggunakan huruf paku di Mesopotamia adalah...", ["Mesir Kuno", "Persia", "Sumeria", "Yunani Kuno"], 2],
  ["SEJ", "mc", "Konferensi Meja Bundar (KMB) yang menghasilkan pengakuan kedaulatan Indonesia oleh Belanda diselenggarakan di...", ["Batavia", "Den Haag", "Amsterdam", "Linggajati"], 1],
  ["SEJ", "mc", "Isi dari Dekret Presiden 5 Juli 1959 yang dikeluarkan oleh Presiden Soekarno adalah...", ["Bubarkan PKI", "Kembali ke UUD 1945 dan pembubaran Konstituante", "Pembentukan Kabinet Ampera", "Pelaksanaan Pemilu pertama"], 1],
  ["SEJ", "mc", "Tembok besar Berlin yang memisahkan Berlin Barat dan Berlin Timur didirikan pada tahun...", ["1945", "1949", "1961", "1989"], 2],
  ["SEJ", "mc", "Perjanjian Tordesillas tahun 1494 membagi wilayah penjelajahan dunia baru di luar Eropa antara dua negara...", ["Spanyol dan Portugal", "Inggris dan Perancis", "Belanda dan Spanyol", "Portugal dan Inggris"], 0],
  ["SEJ", "mc", "Siapakah kaisar Perancis yang mengalami kekalahan telak dalam Pertempuran Waterloo pada tahun 1815?", ["Louis XIV", "Napoleon Bonaparte", "Charles de Gaulle", "Louis XVI"], 1],
  ["SEJ", "mc", "Perang Diponegoro (1825–1830) yang sangat menguras kas keuangan kolonial Belanda dipicu oleh...", ["Belanda menarik pajak tanah yang tinggi", "Belanda memasang patok jalan melintasi makam leluhur Pangeran Diponegoro", "Belanda menangkap Sentot Alibasyah", "Belanda membakar Keraton Yogyakarta"], 1],
  ["SEJ", "mc", "Dinasti kekaisaran terakhir yang memerintah di China sebelum runtuh menjadi republik pada tahun 1912 adalah...", ["Dinasti Ming", "Dinasti Tang", "Dinasti Qing", "Dinasti Han"], 2],
  ["SEJ", "mc", "Organisasi pergerakan nasional pertama Indonesia yang didirikan oleh dr. Soetomo pada 20 Mei 1908 adalah...", ["Sarekat Islam", "Indische Partij", "Budi Utomo", "Perhimpunan Indonesia"], 2],
  ["SEJ", "mc", "Peristiwa pengeboman kota Hiroshima oleh Amerika Serikat terjadi pada tanggal...", ["6 Agustus 1945", "9 Agustus 1945", "14 Agustus 1945", "17 Agustus 1945"], 0],
  ["SEJ", "mc", "Raja terbesar dari Kerajaan Majapahit yang didampingi oleh Patih Gajah Mada adalah...", ["Raden Wijaya", "Hayam Wuruk", "Kertanegara", "Tribhuwana Tunggadewi"], 1],
  ["SEJ", "mc", "Pahlawan nasional yang dikenal sebagai pemimpin gerilya wanita tangguh dari Aceh melawan Belanda adalah...", ["Cut Nyak Dhien", "Kartini", "Dewi Sartika", "Christina Martha Tiahahu"], 0],
  ["SEJ", "mc", "Candi Borobudur dibangun pada masa pemerintahan Dinasti...", ["Sanjaya", "Syailendra", "Isyana", "Girindra"], 1],
  ["SEJ", "tf", "Konferensi Asia-Afrika pertama kali diselenggarakan di Bandung pada tahun 1955", null, 0],
  ["SEJ", "tf", "Perang Dunia I dipicu oleh pembunuhan terhadap pewaris tahta Austria-Hongaria, Franz Ferdinand, di Sarajevo", null, 0],
  ["SEJ", "tf", "Kerajaan Sriwijaya merupakan kerajaan maritim besar bercorak Islam yang terletak di Sumatera Selatan", null, 1],
  ["SEJ", "tf", "Sumpah Pemuda dibacakan pada Kongres Pemuda I tanggal 28 Oktober 1928", null, 1],
  ["SEJ", "tf", "Piagam Jakarta dirumuskan oleh Panitia Sembilan pada tanggal 22 Juni 1945", null, 0],
  ["SEJ", "tf", "Revolusi Industri pertama kali dimulai di negara Perancis pada abad ke-18", null, 1],
  ["SEJ", "tf", "Christopher Columbus mendarat pertama kali di benua Amerika pada tahun 1492", null, 0],
  ["SEJ", "tf", "Candi Prambanan dibangun oleh dinasti Syailendra yang menganut agama Hindu", null, 1],
  ["SEJ", "tf", "Jepang menyerang pangkalan angkatan laut Amerika Serikat di Pearl Harbor pada 7 Desember 1941", null, 0],
  ["SEJ", "tf", "Perjanjian Bongaya ditandatangani oleh Sultan Hasanuddin setelah kalah perang melawan VOC", null, 0],
  ["SEJ", "tf", "Kebijakan politik Etis (politik Balas Budi) meliputi irigasi, emigrasi, dan edukasi", null, 0],
  ["SEJ", "tf", "Kekuasaan Daendels di Indonesia terkenal dengan pembangunan jalan raya pos Anyer-Panarukan", null, 0],
  ["SEJ", "tf", "Pemberontakan G30S/PKI terjadi pada masa pemerintahan presiden Soeharto", null, 1],
  ["SEJ", "tf", "Perang Dingin merupakan persaingan ideologi antara blok barat pimpinan AS dan blok timur pimpinan Uni Soviet", null, 0],
  ["SEJ", "tf", "Kerajaan Samudera Pasai diakui sebagai kerajaan Islam pertama di Indonesia", null, 0],
  ["SEJ", "tf", "VOC dibubarkan pada 31 Desember 1799 karena masalah korupsi dan terlilit utang besar", null, 0],
  ["SEJ", "tf", "Teks proklamasi kemerdekaan Indonesia dirumuskan di rumah Laksamana Maeda", null, 0],
  ["SEJ", "tf", "Konferensi Potsdam merupakan pertemuan sekutu untuk menentukan nasib Jepang setelah kalah perang", null, 1],
  ["SEJ", "tf", "Peristiwa rengasdengklok dipicu oleh perbedaan pendapat antara golongan muda dan tua mengenai waktu proklamasi", null, 0],
  ["SEJ", "tf", "Sultan Agung merupakan raja terbesar dari kerajaan Banten yang gigih melawan VOC", null, 1],
  ["SEJ", "tf", "Penemu mesin cetak pertama yang merevolusi penyebaran informasi di Eropa adalah Johannes Gutenberg", null, 0],
  ["SEJ", "tf", "Sistem tanam paksa (cultuurstelsel) dihapuskan karena adanya kritik keras dari kaum liberal Belanda sendiri", null, 0],
  ["SEJ", "tf", "Perang Dunia II dimulai di Asia ditandai dengan serangan Jerman ke Polandia tahun 1939", null, 1],
  ["SEJ", "tf", "Belanda mengakui kedaulatan Indonesia secara resmi dalam Konferensi Meja Bundar tahun 1949", null, 0],
  ["SEJ", "tf", "Mahatma Gandhi memperjuangkan kemerdekaan India dengan menggunakan metode kekerasan bersenjata", null, 1],

  /* ===== NEGARA (NEG) 45 soal ===== */
  ["NEG", "mc", "Manakah dari negara berikut di kawasan Asia Tenggara yang wilayahnya tidak memiliki akses langsung ke laut?", ["Laos", "Kamboja", "Myanmar", "Vietnam"], 0],
  ["NEG", "mc", "Apakah nama ibu kota dari negara Swiss?", ["Jenewa", "Zurich", "Bern", "Basel"], 2],
  ["NEG", "mc", "Mata uang resmi yang digunakan oleh negara Afrika Selatan adalah...", ["Rand", "Shilling", "Dinar", "Kwacha"], 0],
  ["NEG", "mc", "Manakah dari negara berikut yang memiliki jumlah pulau terbanyak di dunia?", ["Indonesia", "Kanada", "Swedia", "Filipina"], 2],
  ["NEG", "mc", "Apakah nama ibu kota dari negara Kanada?", ["Toronto", "Vancouver", "Ottawa", "Montreal"], 2],
  ["NEG", "mc", "Mata uang resmi dari negara India adalah...", ["Taka", "Rupee", "Rupiah", "Kyat"], 1],
  ["NEG", "mc", "Negara manakah yang secara geografis berada sepenuhnya di dalam wilayah negara Italia?", ["Monako", "San Marino", "Liechtenstein", "Andorra"], 1],
  ["NEG", "mc", "Apakah nama ibu kota dari negara Turki?", ["Istanbul", "Ankara", "Izmir", "Bursa"], 1],
  ["NEG", "mc", "Negara manakah yang memiliki wilayah daratan terluas di benua Afrika?", ["Sudan", "Aljazair", "Kongo", "Libya"], 1],
  ["NEG", "mc", "Apakah mata uang resmi dari negara Brasil?", ["Peso", "Real", "Cruzeiro", "Bolivar"], 1],
  ["NEG", "mc", "Manakah dari negara berikut yang merupakan negara terluas di dunia yang tidak memiliki lautan?", ["Kazakhstan", "Mongolia", "Bolivia", "Chad"], 0],
  ["NEG", "mc", "Apakah nama ibu kota dari negara Australia?", ["Sydney", "Melbourne", "Canberra", "Brisbane"], 2],
  ["NEG", "mc", "Negara manakah yang bendera nasionalnya berbentuk persegi dengan palang putih berlatar belakang merah?", ["Swiss", "Denmark", "Inggris", "Norwegia"], 0],
  ["NEG", "mc", "Apakah nama ibu kota dari negara Vietnam?", ["Ho Chi Minh", "Hanoi", "Da Nang", "Hue"], 1],
  ["NEG", "mc", "Negara manakah yang memiliki garis pantai terpanjang di dunia?", ["Kanada", "Indonesia", "Rusia", "Australia"], 0],
  ["NEG", "mc", "Ibu kota dari negara Rusia adalah...", ["Saint Petersburg", "Moskow", "Kazan", "Novosibirsk"], 1],
  ["NEG", "mc", "Mata uang resmi dari negara Korea Selatan adalah...", ["Won", "Yen", "Yuan", "Ringgit"], 0],
  ["NEG", "mc", "Negara manakah di kawasan Eropa Utara yang terkenal dengan julukan 'Land of the Midnight Sun'?", ["Norwegia", "Denmark", "Swedia", "Finlandia"], 0],
  ["NEG", "mc", "Ibu kota dari negara Mesir yang dilalui oleh Sungai Nil adalah...", ["Kairo", "Iskandariyah", "Giza", "Luxor"], 0],
  ["NEG", "mc", "Mata uang resmi dari negara Inggris (United Kingdom) adalah...", ["Euro", "Pound Sterling", "Dolar", "Franc"], 1],
  ["NEG", "tf", "Kota Sydney adalah ibu kota dari negara Australia", null, 1],
  ["NEG", "tf", "Negara Brasil menggunakan bahasa Portugis sebagai bahasa resminya", null, 0],
  ["NEG", "tf", "Mata uang resmi negara Turki adalah Lira", null, 0],
  ["NEG", "tf", "Kota New York merupakan ibu kota dari negara Amerika Serikat", null, 1],
  ["NEG", "tf", "Ekuador dinamai berdasarkan letak geografisnya yang dilintasi oleh garis khatulistiwa", null, 0],
  ["NEG", "tf", "Negara Jepang dipimpin oleh seorang presiden sebagai kepala negaranya", null, 1],
  ["NEG", "tf", "Swiss memiliki empat bahasa resmi, yaitu Jerman, Perancis, Italia, dan Romansh", null, 0],
  ["NEG", "tf", "Negara Mesir terletak sepenuhnya di benua Asia", null, 1],
  ["NEG", "tf", "Ibu kota dari negara Selandia Baru adalah Auckland", null, 1],
  ["NEG", "tf", "Negara Belanda dikenal karena sebagian besar wilayah daratannya berada di bawah permukaan laut", null, 0],
  ["NEG", "tf", "Ibu kota negara Arab Saudi adalah kota Riyadh", null, 0],
  ["NEG", "tf", "Mata uang resmi dari negara Singapura adalah Ringgit", null, 1],
  ["NEG", "tf", "Negara Thailand merupakan satu-satunya negara di Asia Tenggara yang tidak pernah dijajah oleh bangsa barat", null, 0],
  ["NEG", "tf", "Ibu kota negara Spanyol adalah Barcelona", null, 1],
  ["NEG", "tf", "Negara India merupakan negara dengan jumlah penduduk terbanyak di dunia saat ini", null, 0],
  ["NEG", "tf", "Bahasa resmi yang digunakan di negara Argentina adalah bahasa Spanyol", null, 0],
  ["NEG", "tf", "Ibu kota dari negara Filipina adalah kota Manila", null, 0],
  ["NEG", "tf", "Terusan Panama menghubungkan Samudra Pasifik dengan Samudra Hindia", null, 1],
  ["NEG", "tf", "Negara Islandia terkenal dengan julukan 'Land of Fire and Ice' karena memiliki banyak gunung api dan gletser", null, 0],
  ["NEG", "tf", "Kota terbesar di negara Amerika Serikat adalah Washington D.C.", null, 1],
  ["NEG", "tf", "Mata uang Euro digunakan secara resmi oleh seluruh negara anggota Uni Eropa tanpa terkecuali", null, 1],
  ["NEG", "tf", "Gunung Fuji yang merupakan ikon negara Jepang terletak di pulau Honshu", null, 0],
  ["NEG", "tf", "Negara Vatikan diakui sebagai negara merdeka terkecil di dunia berdasarkan luas wilayahnya", null, 0],
  ["NEG", "tf", "Ibu kota dari negara Malaysia adalah Kuala Lumpur", null, 0],
  ["NEG", "tf", "Negara Peru terletak di kawasan benua Amerika Utara", null, 1],

  /* ===== AKUNTANSI (AKT) 35 soal ===== */
  ["AKT", "mc", "Metode penyusutan aset tetap berdasarkan persentase tetap dari nilai buku aset disebut...", ["Metode garis lurus", "Metode saldo menurun ganda", "Metode satuan hasil", "Metode jumlah angka tahun"], 1],
  ["AKT", "mc", "Manakah dari akun berikut yang dikelompokkan sebagai akun riil yang saldonya dibawa ke periode berikutnya?", ["Beban Gaji", "Pendapatan Jasa", "Piutang Usaha", "Prive Pemilik"], 2],
  ["AKT", "mc", "Dalam akuntansi persediaan, metode yang mengasumsikan barang yang dibeli pertama adalah yang dijual pertama disebut...", ["LIFO", "FIFO", "Rata-rata tertimbang", "Identifikasi spesifik"], 1],
  ["AKT", "mc", "Laporan keuangan yang menyajikan rincian arus masuk dan keluar kas dikelompokkan dalam tiga aktivitas...", ["Operasi, Investasi, Pendanaan", "Produksi, Pemasaran, Keuangan", "Debit, Kredit, Penyesuaian", "Aset, Kewajiban, Ekuitas"], 0],
  ["AKT", "mc", "Pembelian peralatan kantor secara kredit dicatat dalam jurnal dengan cara...", ["Mendebit Peralatan Kantor dan mengkredit Kas", "Mendebit Kas dan mengkredit Peralatan Kantor", "Mendebit Peralatan Kantor dan mengkredit Utang Usaha", "Mendebit Utang Usaha dan mengkredit Peralatan Kantor"], 2],
  ["AKT", "mc", "Manakah dari berikut ini yang merupakan rumus untuk mencari Harga Pokok Penjualan (HPP)?", ["Persediaan Awal + Pembelian Bersih - Persediaan Akhir", "Persediaan Awal - Pembelian Bersih + Persediaan Akhir", "Penjualan Bersih - Laba Kotor", "Persediaan Akhir + Pembelian Bersih - Persediaan Awal"], 0],
  ["AKT", "mc", "Akun 'Akumulasi Penyusutan Peralatan' disajikan di dalam Neraca sebagai...", ["Akun kewajiban lancar", "Akun kontra-aset", "Akun beban di ekuitas", "Akun aset lancar"], 1],
  ["AKT", "mc", "Prinsip akuntansi yang mengharuskan pengakuan beban dilakukan pada periode yang sama dengan pendapatan terkait disebut...", ["Prinsip Biaya Historis", "Prinsip Penandingan (Matching Principle)", "Prinsip Pengungkapan Penuh", "Prinsip Kelangsungan Usaha"], 1],
  ["AKT", "mc", "Jika pada akhir periode terdapat beban gaji yang belum dibayar sebesar Rp5.000.000, jurnal penyesuaiannya adalah...", ["Debit Beban Gaji Rp5.000.000, Kredit Kas Rp5.000.000", "Debit Utang Gaji Rp5.000.000, Kredit Beban Gaji Rp5.000.000", "Debit Beban Gaji Rp5.000.000, Kredit Utang Gaji Rp5.000.000", "Debit Kas Rp5.000.000, Kredit Utang Gaji Rp5.000.000"], 2],
  ["AKT", "mc", "Buku jurnal yang digunakan khusus untuk mencatat transaksi penjualan barang secara kredit adalah...", ["Jurnal Penerimaan Kas", "Jurnal Penjualan", "Jurnal Umum", "Jurnal Pengeluaran Kas"], 1],
  ["AKT", "mc", "Buku yang berisi kumpulan akun-akun sejenis untuk menggolongkan transaksi keuangan disebut...", ["Jurnal Umum", "Buku Besar", "Neraca Saldo", "Kertas Kerja"], 1],
  ["AKT", "mc", "Laporan keuangan yang menyajikan posisi aset, kewajiban, dan modal pada tanggal tertentu disebut...", ["Laporan Laba Rugi", "Laporan Perubahan Modal", "Neraca (Laporan Posisi Keuangan)", "Laporan Arus Kas"], 2],
  ["AKT", "mc", "Pengeluaran kas kecil yang menggunakan sistem dana tetap (imperest fund system) dicatat pada saat...", ["Terjadi transaksi pengeluaran", "Pengisian kembali dana kas kecil", "Pembentukan kas kecil pertama kali", "Perubahan pengelola kas kecil"], 1],
  ["AKT", "mc", "Hak kekayaan pemilik atas aset perusahaan setelah dikurangi seluruh kewajiban disebut...", ["Ekuitas (Modal)", "Investasi", "Liabilitas (Utang)", "Piutang"], 0],
  ["AKT", "mc", "Penjualan barang dagang secara tunai akan dicatat dalam jurnal khusus...", ["Jurnal Penjualan", "Jurnal Umum", "Jurnal Penerimaan Kas", "Jurnal Pengeluaran Kas"], 2],
  ["AKT", "tf", "Dalam persamaan dasar akuntansi, transaksi pengambilan prive akan mengurangi saldo ekuitas pemilik", null, 0],
  ["AKT", "tf", "Akun beban dan pendapatan merupakan akun nominal yang harus ditutup pada akhir periode akuntansi", null, 0],
  ["AKT", "tf", "Debit selalu berarti kenaikan saldo akun, sedangkan kredit selalu berarti penurunan saldo akun", null, 1],
  ["AKT", "tf", "Kas kecil dibentuk untuk mendanai pengeluaran operasional perusahaan yang jumlahnya relatif besar", null, 1],
  ["AKT", "tf", "Neraca saldo yang seimbang menjamin bahwa tidak ada kesalahan dalam pencatatan transaksi", null, 1],
  ["AKT", "tf", "Goodwill dikategorikan sebagai aset tidak berwujud di dalam neraca perusahaan", null, 0],
  ["AKT", "tf", "Dalam akuntansi basis akrual, pendapatan diakui hanya saat kas diterima secara tunai dari pelanggan", null, 1],
  ["AKT", "tf", "Laporan Perubahan Ekuitas menyajikan informasi mengenai laba atau rugi bersih dan penambahan modal", null, 0],
  ["AKT", "tf", "Utang Obligasi diklasifikasikan sebagai kewajiban jangka pendek dalam neraca", null, 1],
  ["AKT", "tf", "Metode penghapusan piutang langsung mencatat beban kerugian piutang tanpa menggunakan akun cadangan", null, 0],
  ["AKT", "tf", "Aktiva lancar adalah aset yang diharapkan dapat dicairkan menjadi kas dalam jangka waktu kurang dari satu tahun", null, 0],
  ["AKT", "tf", "Posting adalah proses memindahkan catatan dari jurnal umum ke dalam buku besar", null, 0],
  ["AKT", "tf", "Saldo normal untuk akun Pendapatan Jasa berada di sebelah debit", null, 1],
  ["AKT", "tf", "Siklus akuntansi diawali dengan analisis bukti transaksi keuangan", null, 0],
  ["AKT", "tf", "Beban penyusutan aset tetap tidak mempengaruhi nilai kas perusahaan secara langsung", null, 0],
  ["AKT", "tf", "Akun Pendapatan Diterima di Muka diklasifikasikan sebagai akun pendapatan di laporan laba rugi", null, 1],
  ["AKT", "tf", "Jurnal penutup dibuat pada setiap awal bulan berjalan sebelum transaksi dicatat", null, 1],
  ["AKT", "tf", "Syarat pembayaran 2/10, n/30 berarti pembeli mendapat potongan 2% jika membayar dalam waktu 10 hari", null, 0],
  ["AKT", "tf", "Laba kotor diperoleh dari penjualan bersih dikurangi dengan total seluruh beban operasional", null, 1],
  ["AKT", "tf", "Peralatan kantor disusutkan karena memiliki masa manfaat ekonomis yang berangsur-angsur menurun", null, 0],

  /* ===== ADVANCED (ADV) 50 soal ===== */
  ["ADV", "mc", "Dalam fisika kuantum, prinsip eksklusi Pauli menyatakan bahwa...", ["Tidak ada dua fermion yang dapat menempati keadaan kuantum yang sama", "Energi foton sebanding dengan frekuensinya", "Posisi dan momentum partikel tidak dapat diukur secara presisi sekaligus", "Fungsi gelombang partikel selalu kontinu"], 0],
  ["ADV", "mc", "Apakah nama teorema teori grup yang menyatakan orde dari subgrup membagi habis orde dari grup berhingga?", ["Teorema Lagrange", "Teorema Euler", "Teorema Cayley", "Teorema Fermat"], 0],
  ["ADV", "mc", "Manakah dari kelas kompleksitas berikut yang mendefinisikan masalah yang solusinya dapat diverifikasi dalam waktu polinomial?", ["P", "NP", "PSPACE", "EXPTIME"], 1],
  ["ADV", "mc", "Dalam biologi molekuler, kompleks enzim yang menyalin DNA menjadi RNA selama transkripsi adalah...", ["DNA Polimerase", "RNA Polimerase", "Helikase", "Ligase"], 1],
  ["ADV", "mc", "Apakah nama efek perubahan frekuensi gelombang akibat gerak relatif sumber dan pengamat?", ["Efek Compton", "Efek Doppler", "Efek Faraday", "Efek Zeeman"], 1],
  ["ADV", "mc", "Dalam filsafat, argumen ontologis untuk membuktikan keberadaan Tuhan dikemukakan oleh...", ["Thomas Aquinas", "Anselmus dari Canterbury", "Rene Descartes", "Immanuel Kant"], 1],
  ["ADV", "mc", "Apakah nama hukum termodinamika yang menyatakan entropi kristal sempurna pada suhu nol mutlak adalah nol?", ["Hukum Pertama", "Hukum Kedua", "Hukum Ketiga", "Hukum Zeroth"], 2],
  ["ADV", "mc", "Dalam ilmu komputer, algoritma kriptografi RSA didasarkan pada kesulitan...", ["Logaritma diskrit", "Faktorisasi prima bilangan bulat besar", "Kriptografi kurva eliptik", "Pecahan berlanjut"], 1],
  ["ADV", "mc", "Apakah nama struktur data di mana anak kiri selalu lebih kecil dari induknya, sedangkan anak kanan lebih besar?", ["Heap", "AVL Tree", "Binary Search Tree", "Red-Black Tree"], 2],
  ["ADV", "mc", "Eksperimen pertama yang berhasil mendeteksi gelombang gravitasi secara langsung pada tahun 2015 adalah...", ["CERN", "LIGO", "Hubble", "James Webb"], 1],
  ["ADV", "mc", "Dalam kimia organik, reaksi eliminasi Hofmann menghasilkan alkena yang...", ["Kurang tersubstitusi", "Paling banyak tersubstitusi", "Memiliki isomer trans saja", "Memiliki cincin benzena"], 0],
  ["ADV", "mc", "Apakah nama paradoks kosmologi yang menanyakan mengapa luar angkasa tampak sepi dari peradaban maju?", ["Paradoks Fermi", "Paradoks Drake", "Paradoks Olbers", "Paradoks Hawking"], 0],
  ["ADV", "mc", "Teorema yang menghubungkan integral garis pada lintasan tertutup dengan integral lipat dua adalah...", ["Teorema Green", "Teorema Stokes", "Teorema Divergensi Gauss", "Teorema Nilai Rata-rata"], 0],
  ["ADV", "mc", "Apakah nama partikel pembawa gaya nuklir kuat yang mengikat kuark bersama-sama?", ["Foton", "Gluon", "Boson W/Z", "Graviton"], 1],
  ["ADV", "mc", "Prinsip ketidakpastian Heisenberg menyatakan batas minimum ketidakpastian sebanding dengan...", ["Konstanta gravitasi G", "Konstanta Planck tereduksi", "Kecepatan cahaya c", "Konstanta Boltzmann k"], 1],
  ["ADV", "mc", "Dalam sistem basis data, properti ACID memastikan keandalan transaksi. Huruf 'I' dalam ACID mewakili...", ["Integration", "Isolation", "Inheritance", "Index"], 1],
  ["ADV", "mc", "Metode kompresi data tanpa kehilangan informasi sama sekali (bit demi bit) diklasifikasikan sebagai...", ["Lossy compression", "Lossless compression", "Asymmetric compression", "Run-length coding saja"], 1],
  ["ADV", "mc", "Apakah nama reaksi kimia di mana dua molekul organik bergabung membentuk satu molekul baru dengan melepaskan molekul kecil seperti air?", ["Reaksi adisi", "Reaksi kondensasi", "Reaksi eliminasi", "Reaksi substitusi"], 1],
  ["ADV", "mc", "Dalam genetika, struktur protein kompleks tempat mengikatnya serat spindel pada kromosom saat pembelahan sel disebut...", ["Sentromer", "Kinetokor", "Kromatid", "Kromatin"], 1],
  ["ADV", "mc", "Dalam jaringan komputer, protokol kriptografi yang digunakan untuk mengamankan komunikasi data di atas TCP adalah...", ["IPsec", "TLS (Transport Layer Security)", "SSH", "HTTPS"], 1],
  ["ADV", "tf", "Persamaan Schrödinger mendeskripsikan bagaimana keadaan kuantum sistem fisik berubah terhadap waktu", null, 0],
  ["ADV", "tf", "Pernyataan P vs NP menanyakan apakah masalah yang diverifikasi dengan cepat dapat diselesaikan dengan cepat", null, 0],
  ["ADV", "tf", "Dalam mekanika kuantum, Quantum Entanglement memungkinkan transmisi informasi melampaui kecepatan cahaya secara instan", null, 1],
  ["ADV", "tf", "Teorema Ketidaklengkapan Gödel membuktikan bahwa dalam sistem formal konsisten terdapat pernyataan benar yang tak dapat dibuktikan", null, 0],
  ["ADV", "tf", "Radiasi Hawking menyebabkan lubang hitam kehilangan massa secara perlahan dan akhirnya menguap", null, 0],
  ["ADV", "tf", "DNA mitokondria diwariskan secara eksklusif dari pihak ayah pada mamalia", null, 1],
  ["ADV", "tf", "Dualitas gelombang-partikel menyatakan cahaya hanya bertindak sebagai gelombang dan elektron sebagai partikel", null, 1],
  ["ADV", "tf", "Entropi dari suatu sistem terisolasi yang tidak berada dalam kesetimbangan cenderung berkurang seiring waktu", null, 1],
  ["ADV", "tf", "CRISPR-Cas9 merupakan teknologi pengeditan genom yang diadaptasi dari sistem imun bakteri", null, 0],
  ["ADV", "tf", "Dalam relativitas khusus, panjang benda yang bergerak akan tampak lebih panjang dari proper length", null, 1],
  ["ADV", "tf", "Teorema Terakhir Fermat berhasil dibuktikan oleh matematikawan Andrew Wiles pada akhir abad ke-20", null, 0],
  ["ADV", "tf", "Enzim mempercepat laju reaksi kimia dengan cara meningkatkan energi aktivasi reaksi", null, 1],
  ["ADV", "tf", "Materi gelap (dark matter) menyusun bagian terbesar dari total densitas energi alam semesta dibanding energi gelap", null, 1],
  ["ADV", "tf", "Teorema Bayes menyatakan peluang kejadian A setelah B terjadi dapat dihitung jika kita tahu peluang B setelah A", null, 0],
  ["ADV", "tf", "Superkonduktor adalah bahan yang memiliki hambatan listrik tepat nol di bawah suhu kritis", null, 0],
  ["ADV", "tf", "Dalam teori string, partikel dasar dimodelkan sebagai senar bergetar satu dimensi", null, 0],
  ["ADV", "tf", "Sel punca pluripoten memiliki kemampuan untuk berkembang menjadi semua jenis sel dalam tubuh organisme", null, 0],
  ["ADV", "tf", "Fungsi rekursif dalam ilmu komputer adalah fungsi yang memanggil fungsi lain di luar dirinya secara paralel", null, 1],
  ["ADV", "tf", "Hukum termodinamika pertama menyatakan bahwa total energi dalam sistem terisolasi selalu konstan", null, 0],
  ["ADV", "tf", "Teori relativitas khusus Einstein berlaku untuk sistem acuan non-inersia yang mengalami percepatan", null, 1],
  ["ADV", "tf", "Dalam kecerdasan buatan, teknik pembelajaran mendalam (deep learning) menggunakan jaringan saraf tiruan berlapis banyak", null, 0],
  ["ADV", "tf", "Enzim restriksi endonuklease digunakan dalam rekayasa genetika untuk menyambung potongan DNA", null, 1],
  ["ADV", "tf", "Prinsip superposisi kuantum menyatakan suatu partikel dapat berada dalam banyak keadaan secara bersamaan sebelum diukur", null, 0],
  ["ADV", "tf", "Penyakit Alzheimer dikaitkan dengan akumulasi plak protein amiloid-beta di jaringan otak", null, 0],
  ["ADV", "tf", "Paradoks kembar memprediksi astronot yang bepergian dengan kecepatan mendekati cahaya akan menua lebih cepat dibanding kembarannya di bumi", null, 1],
  ["ADV", "tf", "Konstanta Boltzmann menghubungkan suhu termodinamika rata-rata dengan energi kinetik partikel gas", null, 0],
  ["ADV", "tf", "Dalam aljabar linear, matriks persegi A memiliki invers jika dan hanya jika determinannya sama dengan nol", null, 1],
  ["ADV", "tf", "Efek rumah kaca dipicu oleh penumpukan gas-gas yang menyerap dan memancarkan kembali radiasi inframerah", null, 0],
  ["ADV", "tf", "Algoritma pencarian biner memiliki kompleksitas waktu rata-rata sebesar O(N) dalam kasus terburuk", null, 1],
  ["ADV", "tf", "Epigenetika mempelajari perubahan ekspresi gen herediter yang tidak melibatkan perubahan urutan basa nitrogen DNA", null, 0],

  /* ===== TRIVIA (TRV) 60 soal ===== */
  ["TRV", "mc", "Manakah dari organ tubuh manusia berikut yang merupakan organ internal terbesar?", ["Otak", "Hati", "Paru-paru", "Usus besar"], 1],
  ["TRV", "mc", "Apakah nama zat kimia alami dalam cabai yang memberikan sensasi pedas?", ["Piperin", "Kapsaisin", "Alisin", "Kurkumin"], 1],
  ["TRV", "mc", "Siapakah pencipta kubus Rubik yang merupakan seorang arsitek dari Hungaria?", ["Erno Rubik", "Laszlo Biro", "Janos Neumann", "Albert Szent-Gyorgyi"], 0],
  ["TRV", "mc", "Manakah dari jenis hewan berikut yang memiliki golongan darah paling banyak?", ["Kucing", "Anjing", "Sapi", "Kuda"], 2],
  ["TRV", "mc", "Di negara manakah biji kakao pertama kali dibudidayakan oleh peradaban kuno?", ["Meksiko", "Brasil", "Pantai Gading", "Indonesia"], 0],
  ["TRV", "mc", "Siapakah pelukis terkenal di balik karya mahakarya surealisme jam meleleh?", ["Pablo Picasso", "Salvador Dali", "Vincent van Gogh", "Claude Monet"], 1],
  ["TRV", "mc", "Hewan laut manakah yang memiliki tiga jantung, sembilan otak, dan darah berwarna biru?", ["Lumba-lumba", "Gurita", "Hiu putih", "Ubur-ubur"], 1],
  ["TRV", "mc", "Apakah nama zat pewarna alami pada wortel yang diubah oleh tubuh menjadi Vitamin A?", ["Klorofil", "Beta-karoten", "Likopen", "Antosianin"], 1],
  ["TRV", "mc", "Dalam olahraga catur, berapakah jumlah total petak di papan catur?", ["36", "48", "64", "81"], 2],
  ["TRV", "mc", "Siapakah penemu penisilin, antibiotik pertama di dunia, pada tahun 1928?", ["Louis Pasteur", "Alexander Fleming", "Jonas Salk", "Robert Koch"], 1],
  ["TRV", "mc", "Hewan mamalia manakah yang memiliki masa kehamilan terlama, yaitu 22 bulan?", ["Badak", "Gajah", "Paus Biru", "Jerapah"], 1],
  ["TRV", "mc", "Negara manakah yang memenangkan Piala Dunia FIFA edisi pertama pada tahun 1930?", ["Brasil", "Uruguay", "Argentina", "Italia"], 1],
  ["TRV", "mc", "Apakah nama bagian mata manusia yang berfungsi mengatur jumlah cahaya yang masuk?", ["Kornea", "Iris", "Retina", "Lensa"], 1],
  ["TRV", "mc", "Siapakah novelis asal Inggris yang menulis seri misteri detektif terkenal Hercule Poirot?", ["Arthur Conan Doyle", "Agatha Christie", "Edgar Allan Poe", "Stephen King"], 1],
  ["TRV", "mc", "Manakah dari planet berikut dalam tata surya kita yang memiliki suhu paling panas?", ["Merkurius", "Venus", "Mars", "Jupiter"], 1],
  ["TRV", "mc", "Bahan peledak dinamit diciptakan oleh Alfred Nobel. Senyawa kimia utama penyusunnya adalah...", ["TNT", "Nitrogliserin", "Mesiu", "Klorat"], 1],
  ["TRV", "mc", "Kota manakah yang dianggap sebagai tempat kelahiran peradaban Renaissance di Italia?", ["Roma", "Florence", "Venesia", "Milan"], 1],
  ["TRV", "mc", "Manakah dari bahasa berikut yang memiliki penutur asli terbanyak di dunia?", ["Inggris", "Mandarin", "Spanyol", "Hindi"], 1],
  ["TRV", "mc", "Apakah nama samudra terkecil dan terdangkal di dunia?", ["Samudra Hindia", "Samudra Arktik", "Samudra Antartika", "Samudra Atlantik"], 1],
  ["TRV", "mc", "Hewan manakah yang dikenal sebagai satu-satunya mamalia yang dapat terbang?", ["Kelelawar", "Tupai terbang", "Burung hantu", "Platipus"], 0],
  ["TRV", "mc", "Siapakah fisikawan penemu elektron pada tahun 1897?", ["Ernest Rutherford", "J.J. Thomson", "Niels Bohr", "James Chadwick"], 1],
  ["TRV", "mc", "Apakah nama selat yang memisahkan benua Asia (Rusia) dan benua Amerika Utara (Alaska)?", ["Selat Gibraltar", "Selat Bering", "Selat Bosporus", "Selat Malaka"], 1],
  ["TRV", "mc", "Dalam mitologi Yunani, siapakah dewa penguasa laut dan gempa bumi?", ["Zeus", "Poseidon", "Hades", "Ares"], 1],
  ["TRV", "mc", "Apakah nama pulau terbesar di dunia yang merupakan wilayah otonom dari negara Denmark?", ["Madagaskar", "Greenland", "Kalimantan", "Papua"], 1],
  ["TRV", "mc", "Manakah dari hewan berikut yang memiliki sidik jari sangat mirip dengan sidik jari manusia?", ["Koala", "Simpanse", "Lumba-lumba", "Anjing"], 0],
  ["TRV", "mc", "Berapakah jumlah senar standar pada alat musik biola?", ["4", "5", "6", "8"], 0],
  ["TRV", "mc", "Minuman kopi espresso berasal dari negara...", ["Turki", "Italia", "Brasil", "Kolombia"], 1],
  ["TRV", "mc", "Siapakah sutradara legendaris asal Italia di balik trilogi film spaghetti western 'Dollars Trilogy'?", ["Federico Fellini", "Sergio Leone", "Bernardo Bertolucci", "Luchino Visconti"], 1],
  ["TRV", "mc", "Bunga bangkai raksasa yang merupakan salah satu bunga tertinggi di dunia berasal dari pulau...", ["Sumatera", "Kalimantan", "Jawa", "Sulawesi"], 0],
  ["TRV", "mc", "Olahraga bela diri Taekwondo berasal dari negara...", ["Jepang", "China", "Korea", "Thailand"], 2],
  ["TRV", "tf", "Kupu-kupu mendeteksi rasa makanan menggunakan reseptor di kaki mereka", null, 0],
  ["TRV", "tf", "Pisang secara botani diklasifikasikan sebagai buah beri", null, 0],
  ["TRV", "tf", "Suara merambat lebih cepat di dalam air dibanding di udara bebas", null, 0],
  ["TRV", "tf", "Tembok Besar China dapat dilihat dengan mata telanjang dari bulan", null, 1],
  ["TRV", "tf", "Madu asli tidak dapat membusuk dan dapat bertahan selama ribuan tahun", null, 0],
  ["TRV", "tf", "Otot terbesar dalam tubuh manusia adalah otot jantung", null, 1],
  ["TRV", "tf", "Unta menyimpan cadangan air mereka di dalam punuknya", null, 1],
  ["TRV", "tf", "Warna merah pada bendera Indonesia melambangkan kesucian", null, 1],
  ["TRV", "tf", "Hiu tidak memiliki tulang keras; seluruh rangkanya tersusun dari tulang rawan", null, 0],
  ["TRV", "tf", "Benua Australia dihuni secara alami oleh hewan penguin", null, 0],
  ["TRV", "tf", "Kucing peliharaan tidak dapat merasakan rasa manis", null, 0],
  ["TRV", "tf", "Logam emas murni 24 karat sangat lunak sehingga dapat dibentuk tangan", null, 0],
  ["TRV", "tf", "Petir tidak pernah menyambar tempat yang sama lebih dari sekali", null, 1],
  ["TRV", "tf", "Semua jenis ular bernapas menggunakan paru-paru", null, 0],
  ["TRV", "tf", "Air laut membeku pada suhu yang sama dengan air tawar", null, 1],
  ["TRV", "tf", "Peradaban Romawi menggunakan sistem kalender Julian sebelum beralih ke kalender Gregorian", null, 0],
  ["TRV", "tf", "Tomat dikategorikan secara ilmiah sebagai sayuran", null, 1],
  ["TRV", "tf", "Hewan bunglon mengubah warna kulitnya terutama untuk berkamuflase", null, 1],
  ["TRV", "tf", "Bumi adalah satu-satunya objek di tata surya dengan bukti adanya air cair", null, 1],
  ["TRV", "tf", "Jantung manusia berdetak rata-rata lebih dari 100.000 kali dalam sehari", null, 0],
  ["TRV", "tf", "Gitar akustik standar memiliki 6 senar", null, 0],
  ["TRV", "tf", "Microsoft didirikan bersama oleh Bill Gates dan Steve Jobs", null, 1],
  ["TRV", "tf", "Burung kolibri adalah satu-satunya burung yang dapat terbang mundur", null, 0],
  ["TRV", "tf", "Panda raksasa secara biologis diklasifikasikan sebagai hewan karnivora meskipun memakan bambu", null, 0],
  ["TRV", "tf", "Struktur DNA manusia berbentuk untai ganda berpilin (double helix)", null, 0],
  ["TRV", "tf", "Lagu kebangsaan Indonesia Raya diciptakan oleh Ismail Marzuki", null, 1],
  ["TRV", "tf", "Air mendidih pada suhu lebih rendah di pegunungan tinggi dibanding di pantai", null, 0],
  ["TRV", "tf", "Benua Antartika dihuni secara permanen oleh jutaan warga sipil", null, 1],
  ["TRV", "tf", "Bintang fajar merupakan sebutan populer untuk planet Venus", null, 0],
  ["TRV", "tf", "Wortel pada awalnya dibudidayakan dengan warna ungu, bukan oranye", null, 0],

  /* ===== FILM (FLM) 50 soal ===== */
  ["FLM", "mc", "Siapakah sutradara film fiksi ilmiah 'Interstellar' dan trilogi 'The Dark Knight'?", ["Steven Spielberg", "Christopher Nolan", "James Cameron", "Quentin Tarantino"], 1],
  ["FLM", "mc", "Aktor manakah yang berperan sebagai Iron Man di Marvel Cinematic Universe?", ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"], 1],
  ["FLM", "mc", "Film animasi pertama buatan Disney yang berdurasi penuh (feature film) adalah...", ["Snow White and the Seven Dwarfs", "Pinocchio", "Fantasia", "Dumbo"], 0],
  ["FLM", "mc", "Apakah nama kerajaan fiktif tempat tinggal Elsa dan Anna di film 'Frozen'?", ["Arendelle", "Genovia", "Corona", "Alderaan"], 0],
  ["FLM", "mc", "Siapakah aktor utama yang memerankan karakter detektif Sherlock Holmes di film tahun 2009?", ["Benedict Cumberbatch", "Robert Downey Jr.", "Jude Law", "Johnny Depp"], 1],
  ["FLM", "mc", "Film manakah yang memenangkan Piala Oscar kategori Film Terbaik (Best Picture) pertama kali?", ["Wings (1927)", "Metropolis (1927)", "Sunrise (1927)", "The Jazz Singer (1927)"], 0],
  ["FLM", "mc", "Aktris manakah yang memerankan karakter utama Katniss Everdeen di film 'The Hunger Games'?", ["Emma Watson", "Jennifer Lawrence", "Kristen Stewart", "Shailene Woodley"], 1],
  ["FLM", "mc", "Film horor klasik tahun 1973 tentang kerasukan iblis pada anak kecil adalah...", ["The Exorcist", "The Shining", "Halloween", "Psycho"], 0],
  ["FLM", "mc", "Siapakah komposer musik di balik musik film 'Star Wars' dan 'Harry Potter'?", ["Hans Zimmer", "John Williams", "Danny Elfman", "Ennio Morricone"], 1],
  ["FLM", "mc", "Apakah judul film Indonesia pertama yang berhasil menembus seleksi Sundance Film Festival?", ["Laskar Pelangi", "The Raid", "Pintu Terlarang", "Arisan!"], 1],
  ["FLM", "mc", "Siapakah sutradara film Indonesia 'Pengabdi Setan' (2017) dan 'Gundala' (2019)?", ["Riri Riza", "Joko Anwar", "Hanung Bramantyo", "Timo Tjahjanto"], 1],
  ["FLM", "mc", "Dalam film 'The Matrix', pil warna apakah yang harus diminum Neo untuk mengetahui kebenaran?", ["Pil Merah", "Pil Biru", "Pil Hijau", "Pil Kuning"], 0],
  ["FLM", "mc", "Film terlaris sepanjang masa yang disutradarai oleh James Cameron adalah...", ["Avatar", "Titanic", "Terminator 2", "Aliens"], 0],
  ["FLM", "mc", "Karakter makhluk kecil hijau yang bijaksana di seri film 'Star Wars' bernama...", ["Yoda", "Luke", "Vader", "Obi-Wan"], 0],
  ["FLM", "mc", "Film animasi garapan Studio Ghibli tentang petualangan gadis kecil bernama Chihiro adalah...", ["My Neighbor Totoro", "Spirited Away", "Princess Mononoke", "Howl's Moving Castle"], 1],
  ["FLM", "mc", "Di film animasi Disney 'The Lion King', siapakah nama paman jahat Simba yang membunuh Mufasa?", ["Scar", "Rafiki", "Pumbaa", "Timon"], 0],
  ["FLM", "mc", "Aktor manakah yang memenangkan Oscar Aktor Terbaik berkat perannya sebagai Joker di film tahun 2019?", ["Heath Ledger", "Joaquin Phoenix", "Jared Leto", "Jack Nicholson"], 1],
  ["FLM", "mc", "Judul film fiksi ilmiah tentang dinosaurus yang dihidupkan kembali di taman rekreasi adalah...", ["Jurassic Park", "King Kong", "Godzilla", "Transformers"], 0],
  ["FLM", "mc", "Siapakah pengisi suara asli dari karakter koboi Sheriff Woody di film 'Toy Story'?", ["Tom Hanks", "Tim Allen", "Robin Williams", "Jim Carrey"], 0],
  ["FLM", "mc", "Siapakah sutradara legendaris asal Jepang yang menyutradarai film klasik 'Seven Samurai' (1954)?", ["Akira Kurosawa", "Hayao Miyazaki", "Yasujiro Ozu", "Takeshi Kitano"], 0],
  ["FLM", "tf", "Film 'Titanic' (1997) dibintangi oleh Leonardo DiCaprio dan Kate Winslet", null, 0],
  ["FLM", "tf", "Piala Oscar (Academy Awards) diselenggarakan secara rutin setiap tahun di kota London", null, 1],
  ["FLM", "tf", "Film animasi 'Shrek' diproduksi oleh Pixar Animation Studios", null, 1],
  ["FLM", "tf", "Daniel Craig adalah aktor yang paling lama memerankan karakter James Bond secara resmi", null, 0],
  ["FLM", "tf", "Film Indonesia 'KKN di Desa Penari' memegang rekor sebagai film Indonesia terlaris sepanjang masa", null, 0],
  ["FLM", "tf", "Perusahaan streaming Netflix didirikan setelah tahun 2010", null, 1],
  ["FLM", "tf", "Dalam film 'Harry Potter', Harry dikirim ke asrama Slytherin oleh Sorting Hat", null, 1],
  ["FLM", "tf", "Sutradara Steven Spielberg menyutradarai film 'Schindler's List' dan 'Saving Private Ryan'", null, 0],
  ["FLM", "tf", "Film 'Parasite' (2019) dari Korea Selatan memenangkan Oscar kategori Film Terbaik", null, 0],
  ["FLM", "tf", "Karakter superhero Spider-Man versi Tom Holland pertama kali muncul di film 'Captain America: Civil War'", null, 0],
  ["FLM", "tf", "Film 'Avatar' yang dirilis tahun 2009 berlatar di sebuah bulan bernama Pandora", null, 0],
  ["FLM", "tf", "Seri film 'The Lord of the Rings' diadaptasi dari novel karya penulis George R.R. Martin", null, 1],
  ["FLM", "tf", "Aktris Scarlett Johansson berperan sebagai Black Widow di jagat Marvel Cinematic Universe", null, 0],
  ["FLM", "tf", "Film 'The Godfather' dirilis pertama kali pada dekade 1970-an", null, 0],
  ["FLM", "tf", "Karakter animasi Minions menyukai buah jeruk di atas segalanya", null, 1],
  ["FLM", "tf", "Aktris Keira Knightley memerankan karakter utama Elizabeth Swann di seri film 'Pirates of the Caribbean'", null, 0],
  ["FLM", "tf", "Film 'La La Land' memenangkan Piala Oscar untuk kategori Film Terbaik pada tahun 2017", null, 1],
  ["FLM", "tf", "Studio animasi Pixar diakuisisi oleh The Walt Disney Company pada tahun 2006", null, 0],
  ["FLM", "tf", "Film horor Indonesia 'Kuntilanak' disutradarai oleh Joko Anwar", null, 1],
  ["FLM", "tf", "Karakter Luke Skywalker di film 'Star Wars' diperankan oleh aktor Mark Hamill", null, 0],
  ["FLM", "tf", "Sutradara Alfred Hitchcock dikenal luas sebagai 'Master of Suspense' dalam film horor klasik", null, 0],
  ["FLM", "tf", "Film 'Joker' (2019) adalah film berperingkat R pertama yang menembus pendapatan 1 miliar USD", null, 0],
  ["FLM", "tf", "Karakter animasi Nemo di film 'Finding Nemo' adalah seekor ikan badut", null, 0],
  ["FLM", "tf", "Aktris Gal Gadot memerankan karakter Captain Marvel di film Marvel", null, 1],
  ["FLM", "tf", "Film 'Inception' bercerita tentang pencurian informasi berharga dengan cara menyusup ke dalam mimpi", null, 0],
  ["FLM", "tf", "Film 'Pulp Fiction' dirilis sebelum tahun 1990", null, 1],
  ["FLM", "tf", "Film bisu digantikan oleh film bersuara pertama kali pada dekade 1920-an", null, 0],
  ["FLM", "tf", "Aktris Margot Robbie memerankan karakter utama Barbie di film 'Barbie' (2023)", null, 0],
  ["FLM", "tf", "Seri film animasi 'Toy Story' diproduksi menggunakan teknologi animasi gambar tangan tradisional", null, 1],
  ["FLM", "tf", "Sutradara Quentin Tarantino menyutradarai film 'Kill Bill' dan 'Django Unchained'", null, 0],

  /* ===== HEWAN (HWN) 50 soal ===== */
  ["HWN", "mc", "Hewan mamalia darat manakah yang dinobatkan sebagai hewan tercepat saat berlari?", ["Kuda", "Cheetah", "Singa", "Kelinci"], 1],
  ["HWN", "mc", "Apakah nama burung terbesar di dunia yang tidak memiliki kemampuan untuk terbang?", ["Kondor", "Albatros", "Burung Unta", "Kasuari"], 2],
  ["HWN", "mc", "Hewan mamalia air manakah yang memegang rekor sebagai makhluk hidup terbesar di bumi?", ["Paus Biru", "Hiu Paus", "Gurita Raksasa", "Lumba-lumba Orca"], 0],
  ["HWN", "mc", "Hewan melata komodo merupakan spesies kadal terbesar di dunia. Di negara manakah komodo hidup secara alami?", ["Australia", "Indonesia", "Afrika Selatan", "Madagaskar"], 1],
  ["HWN", "mc", "Kelompok hewan vertebrata yang hidup di dua alam (air dan darat) disebut...", ["Reptil", "Mamalia", "Amfibi", "Pisces"], 2],
  ["HWN", "mc", "Hewan manakah yang dikenal memiliki kantung di perutnya untuk membawa anaknya?", ["Kucing", "Kanguru", "Tupai", "Kelelawar"], 1],
  ["HWN", "mc", "Manakah di bawah ini yang merupakan satu-satunya burung yang dapat terbang mundur?", ["Burung Kolibri", "Burung Gereja", "Burung Elang", "Burung Hantu"], 0],
  ["HWN", "mc", "Serangga madu lebah berkomunikasi dengan anggota koloninya melalui...", ["Suara dengungan", "Tarian bergoyang (waggle dance)", "Bau feromon saja", "Sentuhan antena"], 1],
  ["HWN", "mc", "Hewan mamalia manakah yang memiliki cangkang keras di punggungnya untuk perlindungan?", ["Armadillo", "Landak", "Tupai tanah", "Platipus"], 0],
  ["HWN", "mc", "Hewan primata terbesar di dunia yang hidup di hutan hujan Afrika adalah...", ["Simpanse", "Gorila", "Orangutan", "Gibon"], 1],
  ["HWN", "mc", "Apakah makanan utama dari hewan panda raksasa di alam liar?", ["Daging", "Bambu", "Buah-buahan", "Serangga"], 1],
  ["HWN", "mc", "Hewan reptil manakah yang memiliki kemampuan untuk mengubah warna kulitnya?", ["Ular", "Buaya", "Bunglon", "Kura-kura"], 2],
  ["HWN", "mc", "Bagian tubuh gajah yang berfungsi seperti tangan untuk mengambil makanan adalah...", ["Gading", "Belalai", "Telinga", "Ekor"], 1],
  ["HWN", "mc", "Hewan yang memakan tumbuh-tumbuhan dikelompokkan ke dalam golongan...", ["Karnivora", "Herbivora", "Omnivora", "Insektivora"], 1],
  ["HWN", "mc", "Hewan laut manakah yang terkenal cerdas dan menggunakan sistem ekolokasi?", ["Hiu", "Paus Sperma", "Lumba-lumba", "Kepiting"], 2],
  ["HWN", "mc", "Serangga pembuat jaring sutra untuk menangkap mangsanya adalah...", ["Semut", "Laba-laba", "Lebah", "Belalang"], 1],
  ["HWN", "mc", "Hewan gurun unta beradaptasi dengan lingkungan kering melalui punuknya yang berisi...", ["Air", "Lemak", "Darah", "Daging"], 1],
  ["HWN", "mc", "Ular kobra membunuh mangsanya dengan cara menyuntikkan zat beracun yang disebut...", ["Bisa (venom)", "Racun perut", "Asam lambung", "Bakteri"], 0],
  ["HWN", "mc", "Hewan karnivora penguasa puncak rantai makanan di hutan Sumatera adalah...", ["Serigala", "Macan Tutul", "Harimau", "Singa"], 2],
  ["HWN", "mc", "Manakah di bawah ini yang merupakan contoh mamalia yang bertelur?", ["Kelelawar", "Koala", "Platipus", "Kanguru"], 2],
  ["HWN", "tf", "Gurita memiliki tiga buah jantung di dalam tubuhnya", null, 0],
  ["HWN", "tf", "Hiu putih raksasa termasuk dalam golongan mamalia air karena melahirkan anaknya", null, 1],
  ["HWN", "tf", "Kupu-kupu mengalami metamorfosis sempurna dari telur, ulat, kepompong, hingga menjadi kupu-kupu", null, 0],
  ["HWN", "tf", "Semua jenis burung memiliki kemampuan untuk terbang secara aktif di udara", null, 1],
  ["HWN", "tf", "Pinguin hidup secara alami hanya di belahan bumi selatan", null, 0],
  ["HWN", "tf", "Ubur-ubur memiliki sistem otak yang sangat kompleks untuk mengendalikan gerakannya", null, 1],
  ["HWN", "tf", "Hewan pengerat tikus dapat bertahan hidup tanpa air lebih lama daripada unta", null, 0],
  ["HWN", "tf", "Laba-laba dikelompokkan ke dalam kelas serangga (insecta)", null, 1],
  ["HWN", "tf", "Kucing memiliki pengelihatan yang sangat baik dalam kegelapan total tanpa cahaya sama sekali", null, 1],
  ["HWN", "tf", "Bunglon mengubah warna kulitnya terutama untuk menyesuaikan suhu tubuh dan berkomunikasi", null, 0],
  ["HWN", "tf", "Hewan koala menghabiskan sebagian besar waktunya untuk tidur, hingga 20-22 jam sehari", null, 0],
  ["HWN", "tf", "Semua jenis ular memiliki bisa (racun) yang mematikan bagi manusia", null, 1],
  ["HWN", "tf", "Hewan paus bernapas menggunakan paru-paru dan menghirup udara di permukaan laut", null, 0],
  ["HWN", "tf", "Kelelawar menggunakan ekolokasi untuk mendeteksi rintangan dan mangsa saat terbang", null, 0],
  ["HWN", "tf", "Burung hantu memiliki kemampuan untuk memutar kepalanya hingga 360 derajat penuh", null, 1],
  ["HWN", "tf", "Hewan singa betina yang lebih sering berburu mangsa daripada singa jantan", null, 0],
  ["HWN", "tf", "Jerapah memiliki jumlah ruas tulang leher yang lebih banyak daripada manusia", null, 1],
  ["HWN", "tf", "Hewan unta memiliki kelopak mata ketiga untuk melindungi mata dari pasir gurun", null, 0],
  ["HWN", "tf", "Semut tidak pernah tidur sepanjang hidupnya", null, 1],
  ["HWN", "tf", "Kulit beruang kutub sebenarnya berwarna hitam di balik bulunya yang tampak putih", null, 0],
  ["HWN", "tf", "Lumba-lumba tidur dengan menutup salah satu belahan otaknya dan membiarkan satu mata tetap terbuka", null, 0],
  ["HWN", "tf", "Hewan kuda dapat tidur sambil berdiri", null, 0],
  ["HWN", "tf", "Buaya air tawar dapat mengeluarkan lidahnya keluar dari mulutnya", null, 1],
  ["HWN", "tf", "Burung elang memiliki ketajaman pengelihatan hingga 4 sampai 8 kali lebih kuat dibanding manusia", null, 0],
  ["HWN", "tf", "Kura-kura dapat hidup hingga usia lebih dari 100 tahun", null, 0],
  ["HWN", "tf", "Hewan luak madu dikenal sebagai salah satu hewan paling pemberani di dunia", null, 0],
  ["HWN", "tf", "Ikan mas koki memiliki ingatan yang sangat pendek, yaitu hanya sekitar 3 detik", null, 1],
  ["HWN", "tf", "Hewan siput dapat tidur selama beberapa tahun dalam kondisi kekeringan ekstrem", null, 0],
  ["HWN", "tf", "Katak menyerap sebagian air dan oksigen melalui kulitnya yang tipis", null, 0],
  ["HWN", "tf", "Hewan harimau memiliki garis-garis belang tidak hanya pada bulunya saja, melainkan juga pada kulitnya", null, 0],
];
